// Code generated by fluent generator. DO NOT EDIT.

package sub_test

import (
	"bytes"
	"testing"

	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/hidden"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/sub"
)

func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(sub.New().RenderBytes())
	want := `<sub></sub>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(sub.New(sub.New()).RenderBytes())
	want = `<sub><sub></sub></sub>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(sub.Text("2").RenderBytes())
	want := `<sub>2</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(sub.Static("n").RenderBytes())
	want := `<sub>n</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(sub.RawText("<var>i</var>").RenderBytes())
	want := `<sub><var>i</var></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	index := 1
	got := string(sub.Textf("%d", index).RenderBytes())
	want := `<sub>1</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	varName := "x"
	got := string(sub.RawTextf("<var>%s</var>", varName).RenderBytes())
	want := `<sub><var>x</var></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(sub.New().Class("test").RenderBytes())
	want := `<sub class="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(sub.New().Class("one").Class("two").Class("three").RenderBytes())
	want := `<sub class="one two three"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(sub.New().ID("test").RenderBytes())
	want := `<sub id="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(sub.New().Style("test").RenderBytes())
	want := `<sub style="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(sub.New().Style("one").Style("two").Style("three").RenderBytes())
	want := `<sub style="one; two; three"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(sub.New().Title("test").RenderBytes())
	want := `<sub title="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(sub.New().Hidden(hidden.True).RenderBytes())
	want := `<sub hidden="true"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenCustom(t *testing.T) {
	got := string(sub.New().Hidden(hidden.Custom("custom-value")).RenderBytes())
	want := `<sub hidden="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(sub.New().TabIndex(42).RenderBytes())
	want := `<sub tabindex="42"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(sub.New().Role("test").RenderBytes())
	want := `<sub role="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(sub.New().Lang("test").RenderBytes())
	want := `<sub lang="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(sub.New().AccessKey("test").RenderBytes())
	want := `<sub accesskey="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(sub.New().AccessKey("one").AccessKey("two").AccessKey("three").RenderBytes())
	want := `<sub accesskey="one two three"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(sub.New().Anchor("test").RenderBytes())
	want := `<sub anchor="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(sub.New().AriaLabel("test").RenderBytes())
	want := `<sub aria-label="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(sub.New().SetAria("label", "test-value").RenderBytes())
	want := `<sub aria-label="test-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(sub.New().AutoCapitalize(autocapitalize.Off).RenderBytes())
	want := `<sub autocapitalize="off"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeCustom(t *testing.T) {
	got := string(sub.New().AutoCapitalize(autocapitalize.Custom("custom-value")).RenderBytes())
	want := `<sub autocapitalize="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(sub.New().AutoCorrect(autocorrect.On).RenderBytes())
	want := `<sub autocorrect="on"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectCustom(t *testing.T) {
	got := string(sub.New().AutoCorrect(autocorrect.Custom("custom-value")).RenderBytes())
	want := `<sub autocorrect="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(sub.New().AutoFocus().RenderBytes())
	want := `<sub autofocus></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusFalse(t *testing.T) {
	got := string(sub.New().AutoFocus().AutoFocus(false).RenderBytes())
	want := `<sub></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(sub.New().ContentEditable(contenteditable.True).RenderBytes())
	want := `<sub contenteditable="true"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableCustom(t *testing.T) {
	got := string(sub.New().ContentEditable(contenteditable.Custom("custom-value")).RenderBytes())
	want := `<sub contenteditable="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(sub.New().SetData("user-id", "test-value").RenderBytes())
	want := `<sub data-user-id="test-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(sub.New().Dir(dir.LeftToRight).RenderBytes())
	want := `<sub dir="ltr"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirCustom(t *testing.T) {
	got := string(sub.New().Dir(dir.Custom("custom-value")).RenderBytes())
	want := `<sub dir="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(sub.New().Draggable(true).RenderBytes())
	want := `<sub draggable="true"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(sub.New().EnterKeyHint(enterkeyhint.Enter).RenderBytes())
	want := `<sub enterkeyhint="enter"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintCustom(t *testing.T) {
	got := string(sub.New().EnterKeyHint(enterkeyhint.Custom("custom-value")).RenderBytes())
	want := `<sub enterkeyhint="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(sub.New().ExportParts("test").RenderBytes())
	want := `<sub exportparts="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(sub.New().Inert().RenderBytes())
	want := `<sub inert></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertFalse(t *testing.T) {
	got := string(sub.New().Inert().Inert(false).RenderBytes())
	want := `<sub></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(sub.New().InputMode(inputmode.None).RenderBytes())
	want := `<sub inputmode="none"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeCustom(t *testing.T) {
	got := string(sub.New().InputMode(inputmode.Custom("custom-value")).RenderBytes())
	want := `<sub inputmode="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(sub.New().Is("test").RenderBytes())
	want := `<sub is="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIDAttr(t *testing.T) {
	got := string(sub.New().ItemID("test").RenderBytes())
	want := `<sub itemid="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(sub.New().ItemProp("test").RenderBytes())
	want := `<sub itemprop="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(sub.New().ItemRef("test").RenderBytes())
	want := `<sub itemref="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(sub.New().ItemScope().RenderBytes())
	want := `<sub itemscope></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeFalse(t *testing.T) {
	got := string(sub.New().ItemScope().ItemScope(false).RenderBytes())
	want := `<sub></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(sub.New().ItemType("test").RenderBytes())
	want := `<sub itemtype="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(sub.New().Nonce("test").RenderBytes())
	want := `<sub nonce="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(sub.New().Part("test").RenderBytes())
	want := `<sub part="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(sub.New().Part("one").Part("two").Part("three").RenderBytes())
	want := `<sub part="one two three"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(sub.New().Popover(popover.Auto).RenderBytes())
	want := `<sub popover="auto"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverCustom(t *testing.T) {
	got := string(sub.New().Popover(popover.Custom("custom-value")).RenderBytes())
	want := `<sub popover="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(sub.New().Slot("test").RenderBytes())
	want := `<sub slot="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(sub.New().SpellCheck(spellcheck.True).RenderBytes())
	want := `<sub spellcheck="true"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckCustom(t *testing.T) {
	got := string(sub.New().SpellCheck(spellcheck.Custom("custom-value")).RenderBytes())
	want := `<sub spellcheck="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(sub.New().Translate(translate.Yes).RenderBytes())
	want := `<sub translate="yes"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateCustom(t *testing.T) {
	got := string(sub.New().Translate(translate.Custom("custom-value")).RenderBytes())
	want := `<sub translate="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(sub.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).RenderBytes())
	want := `<sub virtualkeyboardpolicy="auto"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyCustom(t *testing.T) {
	got := string(sub.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Custom("custom-value")).RenderBytes())
	want := `<sub virtualkeyboardpolicy="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(sub.New().WritingSuggestions(writingsuggestions.True).RenderBytes())
	want := `<sub writingsuggestions="true"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsCustom(t *testing.T) {
	got := string(sub.New().WritingSuggestions(writingsuggestions.Custom("custom-value")).RenderBytes())
	want := `<sub writingsuggestions="custom-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(sub.New().OnClick("test").RenderBytes())
	want := `<sub onclick="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(sub.New().OnChange("test").RenderBytes())
	want := `<sub onchange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(sub.New().OnInput("test").RenderBytes())
	want := `<sub oninput="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(sub.New().OnFocus("test").RenderBytes())
	want := `<sub onfocus="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(sub.New().OnBlur("test").RenderBytes())
	want := `<sub onblur="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(sub.New().OnSubmit("test").RenderBytes())
	want := `<sub onsubmit="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(sub.New().OnLoad("test").RenderBytes())
	want := `<sub onload="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(sub.New().OnError("test").RenderBytes())
	want := `<sub onerror="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(sub.New().SetEvent("onclick", "test-value").RenderBytes())
	want := `<sub onclick="test-value"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(sub.New().OnAbort("test").RenderBytes())
	want := `<sub onabort="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(sub.New().OnAutoComplete("test").RenderBytes())
	want := `<sub onautocomplete="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(sub.New().OnAutoCompleteError("test").RenderBytes())
	want := `<sub onautocompleteerror="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(sub.New().OnCancel("test").RenderBytes())
	want := `<sub oncancel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(sub.New().OnCanPlay("test").RenderBytes())
	want := `<sub oncanplay="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(sub.New().OnCanPlayThrough("test").RenderBytes())
	want := `<sub oncanplaythrough="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(sub.New().OnClose("test").RenderBytes())
	want := `<sub onclose="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(sub.New().OnContextMenu("test").RenderBytes())
	want := `<sub oncontextmenu="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(sub.New().OnCueChange("test").RenderBytes())
	want := `<sub oncuechange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(sub.New().OnDblClick("test").RenderBytes())
	want := `<sub ondblclick="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(sub.New().OnDrag("test").RenderBytes())
	want := `<sub ondrag="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(sub.New().OnDragEnd("test").RenderBytes())
	want := `<sub ondragend="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(sub.New().OnDragEnter("test").RenderBytes())
	want := `<sub ondragenter="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(sub.New().OnDragLeave("test").RenderBytes())
	want := `<sub ondragleave="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(sub.New().OnDragOver("test").RenderBytes())
	want := `<sub ondragover="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(sub.New().OnDragStart("test").RenderBytes())
	want := `<sub ondragstart="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(sub.New().OnDrop("test").RenderBytes())
	want := `<sub ondrop="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(sub.New().OnDurationChange("test").RenderBytes())
	want := `<sub ondurationchange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(sub.New().OnEmptied("test").RenderBytes())
	want := `<sub onemptied="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(sub.New().OnEnded("test").RenderBytes())
	want := `<sub onended="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(sub.New().OnInvalid("test").RenderBytes())
	want := `<sub oninvalid="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(sub.New().OnKeyDown("test").RenderBytes())
	want := `<sub onkeydown="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(sub.New().OnKeyPress("test").RenderBytes())
	want := `<sub onkeypress="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(sub.New().OnKeyUp("test").RenderBytes())
	want := `<sub onkeyup="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(sub.New().OnLoadedData("test").RenderBytes())
	want := `<sub onloadeddata="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(sub.New().OnLoadedMetadata("test").RenderBytes())
	want := `<sub onloadedmetadata="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(sub.New().OnLoadStart("test").RenderBytes())
	want := `<sub onloadstart="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(sub.New().OnMouseDown("test").RenderBytes())
	want := `<sub onmousedown="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(sub.New().OnMouseEnter("test").RenderBytes())
	want := `<sub onmouseenter="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(sub.New().OnMouseLeave("test").RenderBytes())
	want := `<sub onmouseleave="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(sub.New().OnMouseMove("test").RenderBytes())
	want := `<sub onmousemove="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(sub.New().OnMouseOut("test").RenderBytes())
	want := `<sub onmouseout="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(sub.New().OnMouseOver("test").RenderBytes())
	want := `<sub onmouseover="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(sub.New().OnMouseUp("test").RenderBytes())
	want := `<sub onmouseup="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(sub.New().OnMouseWheel("test").RenderBytes())
	want := `<sub onmousewheel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(sub.New().OnPause("test").RenderBytes())
	want := `<sub onpause="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(sub.New().OnPlay("test").RenderBytes())
	want := `<sub onplay="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(sub.New().OnPlaying("test").RenderBytes())
	want := `<sub onplaying="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(sub.New().OnProgress("test").RenderBytes())
	want := `<sub onprogress="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(sub.New().OnRateChange("test").RenderBytes())
	want := `<sub onratechange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(sub.New().OnReset("test").RenderBytes())
	want := `<sub onreset="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(sub.New().OnResize("test").RenderBytes())
	want := `<sub onresize="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(sub.New().OnScroll("test").RenderBytes())
	want := `<sub onscroll="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(sub.New().OnSeeked("test").RenderBytes())
	want := `<sub onseeked="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(sub.New().OnSeeking("test").RenderBytes())
	want := `<sub onseeking="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(sub.New().OnSelect("test").RenderBytes())
	want := `<sub onselect="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(sub.New().OnShow("test").RenderBytes())
	want := `<sub onshow="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(sub.New().OnSort("test").RenderBytes())
	want := `<sub onsort="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(sub.New().OnStalled("test").RenderBytes())
	want := `<sub onstalled="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(sub.New().OnSuspend("test").RenderBytes())
	want := `<sub onsuspend="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(sub.New().OnTimeUpdate("test").RenderBytes())
	want := `<sub ontimeupdate="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(sub.New().OnToggle("test").RenderBytes())
	want := `<sub ontoggle="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(sub.New().OnVolumeChange("test").RenderBytes())
	want := `<sub onvolumechange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(sub.New().OnWaiting("test").RenderBytes())
	want := `<sub onwaiting="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAuxClickAttr(t *testing.T) {
	got := string(sub.New().OnAuxClick("test").RenderBytes())
	want := `<sub onauxclick="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWheelAttr(t *testing.T) {
	got := string(sub.New().OnWheel("test").RenderBytes())
	want := `<sub onwheel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCopyAttr(t *testing.T) {
	got := string(sub.New().OnCopy("test").RenderBytes())
	want := `<sub oncopy="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCutAttr(t *testing.T) {
	got := string(sub.New().OnCut("test").RenderBytes())
	want := `<sub oncut="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPasteAttr(t *testing.T) {
	got := string(sub.New().OnPaste("test").RenderBytes())
	want := `<sub onpaste="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollEndAttr(t *testing.T) {
	got := string(sub.New().OnScrollEnd("test").RenderBytes())
	want := `<sub onscrollend="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFormDataAttr(t *testing.T) {
	got := string(sub.New().OnFormData("test").RenderBytes())
	want := `<sub onformdata="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationCancelAttr(t *testing.T) {
	got := string(sub.New().OnAnimationCancel("test").RenderBytes())
	want := `<sub onanimationcancel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationEndAttr(t *testing.T) {
	got := string(sub.New().OnAnimationEnd("test").RenderBytes())
	want := `<sub onanimationend="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationIterationAttr(t *testing.T) {
	got := string(sub.New().OnAnimationIteration("test").RenderBytes())
	want := `<sub onanimationiteration="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationStartAttr(t *testing.T) {
	got := string(sub.New().OnAnimationStart("test").RenderBytes())
	want := `<sub onanimationstart="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionCancelAttr(t *testing.T) {
	got := string(sub.New().OnTransitionCancel("test").RenderBytes())
	want := `<sub ontransitioncancel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionEndAttr(t *testing.T) {
	got := string(sub.New().OnTransitionEnd("test").RenderBytes())
	want := `<sub ontransitionend="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionRunAttr(t *testing.T) {
	got := string(sub.New().OnTransitionRun("test").RenderBytes())
	want := `<sub ontransitionrun="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionStartAttr(t *testing.T) {
	got := string(sub.New().OnTransitionStart("test").RenderBytes())
	want := `<sub ontransitionstart="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeToggleAttr(t *testing.T) {
	got := string(sub.New().OnBeforeToggle("test").RenderBytes())
	want := `<sub onbeforetoggle="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeInputAttr(t *testing.T) {
	got := string(sub.New().OnBeforeInput("test").RenderBytes())
	want := `<sub onbeforeinput="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeMatchAttr(t *testing.T) {
	got := string(sub.New().OnBeforeMatch("test").RenderBytes())
	want := `<sub onbeforematch="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCommandAttr(t *testing.T) {
	got := string(sub.New().OnCommand("test").RenderBytes())
	want := `<sub oncommand="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextLostAttr(t *testing.T) {
	got := string(sub.New().OnContextLost("test").RenderBytes())
	want := `<sub oncontextlost="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextRestoredAttr(t *testing.T) {
	got := string(sub.New().OnContextRestored("test").RenderBytes())
	want := `<sub oncontextrestored="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSecurityPolicyViolationAttr(t *testing.T) {
	got := string(sub.New().OnSecurityPolicyViolation("test").RenderBytes())
	want := `<sub onsecuritypolicyviolation="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSlotChangeAttr(t *testing.T) {
	got := string(sub.New().OnSlotChange("test").RenderBytes())
	want := `<sub onslotchange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerDownAttr(t *testing.T) {
	got := string(sub.New().OnPointerDown("test").RenderBytes())
	want := `<sub onpointerdown="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerUpAttr(t *testing.T) {
	got := string(sub.New().OnPointerUp("test").RenderBytes())
	want := `<sub onpointerup="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerMoveAttr(t *testing.T) {
	got := string(sub.New().OnPointerMove("test").RenderBytes())
	want := `<sub onpointermove="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerEnterAttr(t *testing.T) {
	got := string(sub.New().OnPointerEnter("test").RenderBytes())
	want := `<sub onpointerenter="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerLeaveAttr(t *testing.T) {
	got := string(sub.New().OnPointerLeave("test").RenderBytes())
	want := `<sub onpointerleave="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOverAttr(t *testing.T) {
	got := string(sub.New().OnPointerOver("test").RenderBytes())
	want := `<sub onpointerover="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOutAttr(t *testing.T) {
	got := string(sub.New().OnPointerOut("test").RenderBytes())
	want := `<sub onpointerout="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerCancelAttr(t *testing.T) {
	got := string(sub.New().OnPointerCancel("test").RenderBytes())
	want := `<sub onpointercancel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnGotPointerCaptureAttr(t *testing.T) {
	got := string(sub.New().OnGotPointerCapture("test").RenderBytes())
	want := `<sub ongotpointercapture="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLostPointerCaptureAttr(t *testing.T) {
	got := string(sub.New().OnLostPointerCapture("test").RenderBytes())
	want := `<sub onlostpointercapture="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchStartAttr(t *testing.T) {
	got := string(sub.New().OnTouchStart("test").RenderBytes())
	want := `<sub ontouchstart="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchEndAttr(t *testing.T) {
	got := string(sub.New().OnTouchEnd("test").RenderBytes())
	want := `<sub ontouchend="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchMoveAttr(t *testing.T) {
	got := string(sub.New().OnTouchMove("test").RenderBytes())
	want := `<sub ontouchmove="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchCancelAttr(t *testing.T) {
	got := string(sub.New().OnTouchCancel("test").RenderBytes())
	want := `<sub ontouchcancel="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectStartAttr(t *testing.T) {
	got := string(sub.New().OnSelectStart("test").RenderBytes())
	want := `<sub onselectstart="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectionChangeAttr(t *testing.T) {
	got := string(sub.New().OnSelectionChange("test").RenderBytes())
	want := `<sub onselectionchange="test"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(sub.New(sub.New(), sub.New()).RenderBytes())
	want := `<sub><sub></sub><sub></sub></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := sub.New().Add(sub.New(), sub.New())

	// Test rendered output
	got := string(element.RenderBytes())
	want := `<sub><sub></sub><sub></sub></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := sub.New(sub.New(), sub.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(sub.New())

	// Test rendered output
	got := string(element.RenderBytes())
	want := `<sub><sub></sub></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(sub.New().Text("hello").RenderBytes())
	want := `<sub>hello</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(sub.New().Textf("hello %s", "world").RenderBytes())
	want := `<sub>hello world</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(sub.New().Static("static content").RenderBytes())
	want := `<sub>static content</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(sub.New().RawText("<em>bold</em>").RenderBytes())
	want := `<sub><em>bold</em></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(sub.New().RawTextf("<%s>test</%s>", "span", "span").RenderBytes())
	want := `<sub><span>test</span></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(sub.New().Class("foo").Text("content").ID("bar").RenderBytes())
	want := `<sub class="foo" id="bar">content</sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicKey(t *testing.T) {
	got := string(sub.New().Dynamic("mykey").RenderBytes())
	want := `<sub data-fluent-key="mykey"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestMemoiseKey(t *testing.T) {
	el := sub.New()
	if el.MemoiseKey() != nil {
		t.Error("new element should have no memoise version")
	}
	el.Memoise(7)
	if el.MemoiseKey() != 7 {
		t.Errorf("MemoiseKey() = %v, want 7", el.MemoiseKey())
	}
}

func TestNotDynamic(t *testing.T) {
	el := sub.New()
	if el.IsDynamic() {
		t.Error("new element should not be dynamic")
	}
	if el.DynamicKey() != "" {
		t.Errorf("DynamicKey() should be empty, got %q", el.DynamicKey())
	}
}

func TestRenderMethodsMatch(t *testing.T) {
	el := sub.New()
	el.SetAttribute("data-check", "render")
	want := string(el.RenderBytes())

	var buf bytes.Buffer
	el.Render(&buf)
	if buf.String() != want {
		t.Errorf("Render: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	n, err := el.WriteTo(&buf)
	if err != nil {
		t.Fatalf("WriteTo: %v", err)
	}
	if buf.String() != want {
		t.Errorf("WriteTo: got %q, want %q", buf.String(), want)
	}
	if n != int64(len(want)) {
		t.Errorf("WriteTo returned %d bytes, want %d", n, len(want))
	}

	buf.Reset()
	el.RenderBuilder(&buf)
	if buf.String() != want {
		t.Errorf("RenderBuilder: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	el.RenderOpen(&buf)
	el.RenderClose(&buf)
	if buf.String() != want {
		t.Errorf("RenderOpen+RenderClose: got %q, want %q", buf.String(), want)
	}
}

func TestSetAttributeEscapes(t *testing.T) {
	el := sub.New()
	el.SetAttribute("data-sample", "\"><script>")
	got := string(el.RenderBytes())
	want := `<sub data-sample="&#34;&gt;&lt;script&gt;"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAttributeRaw(t *testing.T) {
	el := sub.New()
	// A pre-escaped entity must render verbatim; SetAttribute would double-escape it.
	el.SetAttributeRaw("data-sample", "a&amp;b")
	got := string(el.RenderBytes())
	want := `<sub data-sample="a&amp;b"></sub>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextNoBreakout(t *testing.T) {
	got := sub.Text("\"><script>").RenderBytes()
	if bytes.Contains(got, []byte("\"><script>")) {
		t.Errorf("hostile value reached the output unescaped: %s", got)
	}
}

func TestTextfNoBreakout(t *testing.T) {
	got := sub.Textf("\"><script>").RenderBytes()
	if bytes.Contains(got, []byte("\"><script>")) {
		t.Errorf("hostile value reached the output unescaped: %s", got)
	}
}
