// Code generated by fluent generator. DO NOT EDIT.

package embed_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/embed"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
)


func TestNewCtor(t *testing.T) {
	got := string(embed.New().Render())
	want := `<embed />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPDFCtor(t *testing.T) {
	got := string(embed.PDF("document.pdf", 800, 600).Render())
	want := `<embed src="document.pdf" type="application/pdf" width="800" height="600" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFlashCtor(t *testing.T) {
	got := string(embed.Flash("animation.swf", 640, 480).Render())
	want := `<embed src="animation.swf" type="application/x-shockwave-flash" width="640" height="480" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVideoCtor(t *testing.T) {
	got := string(embed.Video("movie.mp4", 640, 480).Render())
	want := `<embed src="movie.mp4" type="video/mp4" width="640" height="480" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAudioCtor(t *testing.T) {
	got := string(embed.Audio("song.mp3", 320, 50).Render())
	want := `<embed src="song.mp3" type="audio/mpeg" width="320" height="50" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSrcAttr(t *testing.T) {
	got := string(embed.New().Src("test").Render())
	want := `<embed src="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTypeAttr(t *testing.T) {
	got := string(embed.New().Type("test").Render())
	want := `<embed type="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWidthAttr(t *testing.T) {
	got := string(embed.New().Width(42).Render())
	want := `<embed width="42" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHeightAttr(t *testing.T) {
	got := string(embed.New().Height(42).Render())
	want := `<embed height="42" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(embed.New().Class("test").Render())
	want := `<embed class="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(embed.New().Class("one").Class("two").Class("three").Render())
	want := `<embed class="one two three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(embed.New().ID("test").Render())
	want := `<embed id="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(embed.New().Style("test").Render())
	want := `<embed style="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(embed.New().Style("one").Style("two").Style("three").Render())
	want := `<embed style="one; two; three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(embed.New().Title("test").Render())
	want := `<embed title="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(embed.New().Hidden().Render())
	want := `<embed hidden="hidden" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(embed.New().TabIndex(42).Render())
	want := `<embed tabindex="42" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(embed.New().Role("test").Render())
	want := `<embed role="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(embed.New().Lang("test").Render())
	want := `<embed lang="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(embed.New().AccessKey("test").Render())
	want := `<embed accesskey="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(embed.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<embed accesskey="one two three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(embed.New().Anchor("test").Render())
	want := `<embed anchor="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(embed.New().AriaLabel("test").Render())
	want := `<embed arialabel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(embed.New().SetAria("label", "test-value").Render())
	want := `<embed aria-label="test-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(embed.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<embed autocapitalize="off" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(embed.New().AutoCorrect(autocorrect.On).Render())
	want := `<embed autocorrect="on" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(embed.New().AutoFocus().Render())
	want := `<embed autofocus="autofocus" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(embed.New().ContentEditable(contenteditable.True).Render())
	want := `<embed contenteditable="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(embed.New().SetData("user-id", "test-value").Render())
	want := `<embed data-user-id="test-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(embed.New().Dir(dir.LeftToRight).Render())
	want := `<embed dir="ltr" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(embed.New().Draggable().Render())
	want := `<embed draggable="draggable" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(embed.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<embed enterkeyhint="enter" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(embed.New().ExportParts("test").Render())
	want := `<embed exportparts="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(embed.New().Inert().Render())
	want := `<embed inert="inert" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(embed.New().InputMode(inputmode.None).Render())
	want := `<embed inputmode="none" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(embed.New().Is("test").Render())
	want := `<embed is="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(embed.New().ItemId("test").Render())
	want := `<embed itemid="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(embed.New().ItemProp("test").Render())
	want := `<embed itemprop="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(embed.New().ItemRef("test").Render())
	want := `<embed itemref="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(embed.New().ItemScope().Render())
	want := `<embed itemscope="itemscope" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(embed.New().ItemType("test").Render())
	want := `<embed itemtype="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(embed.New().Nonce("test").Render())
	want := `<embed nonce="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(embed.New().Part("test").Render())
	want := `<embed part="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(embed.New().Part("one").Part("two").Part("three").Render())
	want := `<embed part="one two three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(embed.New().Popover(popover.Auto).Render())
	want := `<embed popover="auto" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(embed.New().Slot("test").Render())
	want := `<embed slot="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(embed.New().SpellCheck(spellcheck.True).Render())
	want := `<embed spellcheck="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(embed.New().Translate(translate.Yes).Render())
	want := `<embed translate="yes" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(embed.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<embed virtualkeyboardpolicy="auto" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(embed.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<embed writingsuggestions="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(embed.New().OnClick("test").Render())
	want := `<embed onclick="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(embed.New().OnChange("test").Render())
	want := `<embed onchange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(embed.New().OnInput("test").Render())
	want := `<embed oninput="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(embed.New().OnFocus("test").Render())
	want := `<embed onfocus="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(embed.New().OnBlur("test").Render())
	want := `<embed onblur="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(embed.New().OnSubmit("test").Render())
	want := `<embed onsubmit="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(embed.New().OnLoad("test").Render())
	want := `<embed onload="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(embed.New().OnError("test").Render())
	want := `<embed onerror="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(embed.New().SetEvent("onclick", "test-value").Render())
	want := `<embed onclick="test-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(embed.New().OnAbort("test").Render())
	want := `<embed onabort="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(embed.New().OnAutoComplete("test").Render())
	want := `<embed onautocomplete="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(embed.New().OnAutoCompleteError("test").Render())
	want := `<embed onautocompleteerror="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(embed.New().OnCancel("test").Render())
	want := `<embed oncancel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(embed.New().OnCanPlay("test").Render())
	want := `<embed oncanplay="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(embed.New().OnCanPlayThrough("test").Render())
	want := `<embed oncanplaythrough="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(embed.New().OnClose("test").Render())
	want := `<embed onclose="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(embed.New().OnContextMenu("test").Render())
	want := `<embed oncontextmenu="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(embed.New().OnCueChange("test").Render())
	want := `<embed oncuechange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(embed.New().OnDblClick("test").Render())
	want := `<embed ondblclick="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(embed.New().OnDrag("test").Render())
	want := `<embed ondrag="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(embed.New().OnDragEnd("test").Render())
	want := `<embed ondragend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(embed.New().OnDragEnter("test").Render())
	want := `<embed ondragenter="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(embed.New().OnDragLeave("test").Render())
	want := `<embed ondragleave="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(embed.New().OnDragOver("test").Render())
	want := `<embed ondragover="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(embed.New().OnDragStart("test").Render())
	want := `<embed ondragstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(embed.New().OnDrop("test").Render())
	want := `<embed ondrop="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(embed.New().OnDurationChange("test").Render())
	want := `<embed ondurationchange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(embed.New().OnEmptied("test").Render())
	want := `<embed onemptied="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(embed.New().OnEnded("test").Render())
	want := `<embed onended="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(embed.New().OnInvalid("test").Render())
	want := `<embed oninvalid="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(embed.New().OnKeyDown("test").Render())
	want := `<embed onkeydown="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(embed.New().OnKeyPress("test").Render())
	want := `<embed onkeypress="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(embed.New().OnKeyUp("test").Render())
	want := `<embed onkeyup="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(embed.New().OnLoadedData("test").Render())
	want := `<embed onloadeddata="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(embed.New().OnLoadedMetadata("test").Render())
	want := `<embed onloadedmetadata="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(embed.New().OnLoadStart("test").Render())
	want := `<embed onloadstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(embed.New().OnMouseDown("test").Render())
	want := `<embed onmousedown="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(embed.New().OnMouseEnter("test").Render())
	want := `<embed onmouseenter="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(embed.New().OnMouseLeave("test").Render())
	want := `<embed onmouseleave="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(embed.New().OnMouseMove("test").Render())
	want := `<embed onmousemove="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(embed.New().OnMouseOut("test").Render())
	want := `<embed onmouseout="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(embed.New().OnMouseOver("test").Render())
	want := `<embed onmouseover="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(embed.New().OnMouseUp("test").Render())
	want := `<embed onmouseup="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(embed.New().OnMouseWheel("test").Render())
	want := `<embed onmousewheel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(embed.New().OnPause("test").Render())
	want := `<embed onpause="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(embed.New().OnPlay("test").Render())
	want := `<embed onplay="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(embed.New().OnPlaying("test").Render())
	want := `<embed onplaying="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(embed.New().OnProgress("test").Render())
	want := `<embed onprogress="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(embed.New().OnRateChange("test").Render())
	want := `<embed onratechange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(embed.New().OnReset("test").Render())
	want := `<embed onreset="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(embed.New().OnResize("test").Render())
	want := `<embed onresize="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(embed.New().OnScroll("test").Render())
	want := `<embed onscroll="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(embed.New().OnSeeked("test").Render())
	want := `<embed onseeked="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(embed.New().OnSeeking("test").Render())
	want := `<embed onseeking="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(embed.New().OnSelect("test").Render())
	want := `<embed onselect="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(embed.New().OnShow("test").Render())
	want := `<embed onshow="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(embed.New().OnSort("test").Render())
	want := `<embed onsort="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(embed.New().OnStalled("test").Render())
	want := `<embed onstalled="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(embed.New().OnSuspend("test").Render())
	want := `<embed onsuspend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(embed.New().OnTimeUpdate("test").Render())
	want := `<embed ontimeupdate="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(embed.New().OnToggle("test").Render())
	want := `<embed ontoggle="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(embed.New().OnVolumeChange("test").Render())
	want := `<embed onvolumechange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(embed.New().OnWaiting("test").Render())
	want := `<embed onwaiting="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

