// Code generated by fluent generator. DO NOT EDIT.

// Package controlslist defines the [ControlsList] type and its predefined values.
//
// Controls which browser-native media controls to show or hide on video and audio elements.
// Multiple values can be specified to hide multiple controls.
package controlslist

import (
	"github.com/jpl-au/fluent/node"
)

// ControlsList is a typed value for the HTML controlslist attribute.
//
// Controls which browser-native media controls to show or hide on video and audio elements.
// Multiple values can be specified to hide multiple controls.
type ControlsList []byte

// Variables for ControlsList values
var (
	// NoDownload Hide the download button from the browser's native media controls.
	// Prevents users from downloading the media directly from the player.
	NoDownload = ControlsList("nodownload")

	// NoFullscreen Hide the fullscreen button from the browser's native media controls.
	// Useful when fullscreen viewing is not desired or appropriate.
	NoFullscreen = ControlsList("nofullscreen")

	// NoRemotePlayback Hide remote playback options (casting) from the browser's native media controls.
	// Prevents casting to devices like Chromecast or AirPlay from the player UI.
	NoRemotePlayback = ControlsList("noremoteplayback")
)

// Custom allows setting a custom ControlsList value for edge cases or future specifications.
// Use this when the predefined constants don't cover your specific use case.
func Custom(value string) ControlsList {
	return ControlsList(node.EscapeAttribute(value))
}
