// Code generated by fluent generator. DO NOT EDIT.

package h3_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/h3"
	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
)


func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(h3.New().Render())
	want := `<h3></h3>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(h3.New(h3.New()).Render())
	want = `<h3><h3></h3></h3>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(h3.Text("<u>Minor</u> Heading").Render())
	want := `<h3>&lt;u&gt;Minor&lt;/u&gt; Heading</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(h3.Static("Hello World").Render())
	want := `<h3>Hello World</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(h3.RawText("<u>Minor</u> Heading").Render())
	want := `<h3><u>Minor</u> Heading</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	got := string(h3.Textf("Hello %s", "World").Render())
	want := `<h3>Hello World</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	got := string(h3.RawTextf("Hello <em>%s</em>", "World").Render())
	want := `<h3>Hello <em>World</em></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(h3.New().Class("test").Render())
	want := `<h3 class="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(h3.New().Class("one").Class("two").Class("three").Render())
	want := `<h3 class="one two three"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(h3.New().ID("test").Render())
	want := `<h3 id="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(h3.New().Style("test").Render())
	want := `<h3 style="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(h3.New().Style("one").Style("two").Style("three").Render())
	want := `<h3 style="one; two; three"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(h3.New().Title("test").Render())
	want := `<h3 title="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(h3.New().Hidden().Render())
	want := `<h3 hidden="hidden"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(h3.New().TabIndex(42).Render())
	want := `<h3 tabindex="42"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(h3.New().Role("test").Render())
	want := `<h3 role="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(h3.New().Lang("test").Render())
	want := `<h3 lang="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(h3.New().AccessKey("test").Render())
	want := `<h3 accesskey="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(h3.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<h3 accesskey="one two three"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(h3.New().Anchor("test").Render())
	want := `<h3 anchor="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(h3.New().AriaLabel("test").Render())
	want := `<h3 arialabel="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(h3.New().SetAria("label", "test-value").Render())
	want := `<h3 aria-label="test-value"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(h3.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<h3 autocapitalize="off"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(h3.New().AutoCorrect(autocorrect.On).Render())
	want := `<h3 autocorrect="on"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(h3.New().AutoFocus().Render())
	want := `<h3 autofocus="autofocus"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(h3.New().ContentEditable(contenteditable.True).Render())
	want := `<h3 contenteditable="true"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(h3.New().SetData("user-id", "test-value").Render())
	want := `<h3 data-user-id="test-value"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(h3.New().Dir(dir.LeftToRight).Render())
	want := `<h3 dir="ltr"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(h3.New().Draggable().Render())
	want := `<h3 draggable="draggable"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(h3.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<h3 enterkeyhint="enter"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(h3.New().ExportParts("test").Render())
	want := `<h3 exportparts="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(h3.New().Inert().Render())
	want := `<h3 inert="inert"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(h3.New().InputMode(inputmode.None).Render())
	want := `<h3 inputmode="none"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(h3.New().Is("test").Render())
	want := `<h3 is="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(h3.New().ItemId("test").Render())
	want := `<h3 itemid="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(h3.New().ItemProp("test").Render())
	want := `<h3 itemprop="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(h3.New().ItemRef("test").Render())
	want := `<h3 itemref="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(h3.New().ItemScope().Render())
	want := `<h3 itemscope="itemscope"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(h3.New().ItemType("test").Render())
	want := `<h3 itemtype="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(h3.New().Nonce("test").Render())
	want := `<h3 nonce="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(h3.New().Part("test").Render())
	want := `<h3 part="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(h3.New().Part("one").Part("two").Part("three").Render())
	want := `<h3 part="one two three"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(h3.New().Popover(popover.Auto).Render())
	want := `<h3 popover="auto"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(h3.New().Slot("test").Render())
	want := `<h3 slot="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(h3.New().SpellCheck(spellcheck.True).Render())
	want := `<h3 spellcheck="true"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(h3.New().Translate(translate.Yes).Render())
	want := `<h3 translate="yes"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(h3.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<h3 virtualkeyboardpolicy="auto"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(h3.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<h3 writingsuggestions="true"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(h3.New().OnClick("test").Render())
	want := `<h3 onclick="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(h3.New().OnChange("test").Render())
	want := `<h3 onchange="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(h3.New().OnInput("test").Render())
	want := `<h3 oninput="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(h3.New().OnFocus("test").Render())
	want := `<h3 onfocus="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(h3.New().OnBlur("test").Render())
	want := `<h3 onblur="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(h3.New().OnSubmit("test").Render())
	want := `<h3 onsubmit="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(h3.New().OnLoad("test").Render())
	want := `<h3 onload="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(h3.New().OnError("test").Render())
	want := `<h3 onerror="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(h3.New().SetEvent("onclick", "test-value").Render())
	want := `<h3 onclick="test-value"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(h3.New().OnAbort("test").Render())
	want := `<h3 onabort="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(h3.New().OnAutoComplete("test").Render())
	want := `<h3 onautocomplete="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(h3.New().OnAutoCompleteError("test").Render())
	want := `<h3 onautocompleteerror="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(h3.New().OnCancel("test").Render())
	want := `<h3 oncancel="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(h3.New().OnCanPlay("test").Render())
	want := `<h3 oncanplay="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(h3.New().OnCanPlayThrough("test").Render())
	want := `<h3 oncanplaythrough="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(h3.New().OnClose("test").Render())
	want := `<h3 onclose="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(h3.New().OnContextMenu("test").Render())
	want := `<h3 oncontextmenu="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(h3.New().OnCueChange("test").Render())
	want := `<h3 oncuechange="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(h3.New().OnDblClick("test").Render())
	want := `<h3 ondblclick="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(h3.New().OnDrag("test").Render())
	want := `<h3 ondrag="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(h3.New().OnDragEnd("test").Render())
	want := `<h3 ondragend="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(h3.New().OnDragEnter("test").Render())
	want := `<h3 ondragenter="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(h3.New().OnDragLeave("test").Render())
	want := `<h3 ondragleave="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(h3.New().OnDragOver("test").Render())
	want := `<h3 ondragover="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(h3.New().OnDragStart("test").Render())
	want := `<h3 ondragstart="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(h3.New().OnDrop("test").Render())
	want := `<h3 ondrop="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(h3.New().OnDurationChange("test").Render())
	want := `<h3 ondurationchange="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(h3.New().OnEmptied("test").Render())
	want := `<h3 onemptied="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(h3.New().OnEnded("test").Render())
	want := `<h3 onended="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(h3.New().OnInvalid("test").Render())
	want := `<h3 oninvalid="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(h3.New().OnKeyDown("test").Render())
	want := `<h3 onkeydown="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(h3.New().OnKeyPress("test").Render())
	want := `<h3 onkeypress="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(h3.New().OnKeyUp("test").Render())
	want := `<h3 onkeyup="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(h3.New().OnLoadedData("test").Render())
	want := `<h3 onloadeddata="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(h3.New().OnLoadedMetadata("test").Render())
	want := `<h3 onloadedmetadata="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(h3.New().OnLoadStart("test").Render())
	want := `<h3 onloadstart="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(h3.New().OnMouseDown("test").Render())
	want := `<h3 onmousedown="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(h3.New().OnMouseEnter("test").Render())
	want := `<h3 onmouseenter="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(h3.New().OnMouseLeave("test").Render())
	want := `<h3 onmouseleave="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(h3.New().OnMouseMove("test").Render())
	want := `<h3 onmousemove="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(h3.New().OnMouseOut("test").Render())
	want := `<h3 onmouseout="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(h3.New().OnMouseOver("test").Render())
	want := `<h3 onmouseover="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(h3.New().OnMouseUp("test").Render())
	want := `<h3 onmouseup="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(h3.New().OnMouseWheel("test").Render())
	want := `<h3 onmousewheel="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(h3.New().OnPause("test").Render())
	want := `<h3 onpause="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(h3.New().OnPlay("test").Render())
	want := `<h3 onplay="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(h3.New().OnPlaying("test").Render())
	want := `<h3 onplaying="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(h3.New().OnProgress("test").Render())
	want := `<h3 onprogress="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(h3.New().OnRateChange("test").Render())
	want := `<h3 onratechange="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(h3.New().OnReset("test").Render())
	want := `<h3 onreset="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(h3.New().OnResize("test").Render())
	want := `<h3 onresize="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(h3.New().OnScroll("test").Render())
	want := `<h3 onscroll="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(h3.New().OnSeeked("test").Render())
	want := `<h3 onseeked="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(h3.New().OnSeeking("test").Render())
	want := `<h3 onseeking="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(h3.New().OnSelect("test").Render())
	want := `<h3 onselect="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(h3.New().OnShow("test").Render())
	want := `<h3 onshow="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(h3.New().OnSort("test").Render())
	want := `<h3 onsort="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(h3.New().OnStalled("test").Render())
	want := `<h3 onstalled="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(h3.New().OnSuspend("test").Render())
	want := `<h3 onsuspend="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(h3.New().OnTimeUpdate("test").Render())
	want := `<h3 ontimeupdate="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(h3.New().OnToggle("test").Render())
	want := `<h3 ontoggle="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(h3.New().OnVolumeChange("test").Render())
	want := `<h3 onvolumechange="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(h3.New().OnWaiting("test").Render())
	want := `<h3 onwaiting="test"></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(h3.New(h3.New(), h3.New()).Render())
	want := `<h3><h3></h3><h3></h3></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := h3.New().Add(h3.New(), h3.New())

	// Test rendered output
	got := string(element.Render())
	want := `<h3><h3></h3><h3></h3></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := h3.New(h3.New(), h3.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(h3.New())

	// Test rendered output
	got := string(element.Render())
	want := `<h3><h3></h3></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(h3.New().Text("hello").Render())
	want := `<h3>hello</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(h3.New().Textf("hello %s", "world").Render())
	want := `<h3>hello world</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(h3.New().Static("static content").Render())
	want := `<h3>static content</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(h3.New().RawText("<em>bold</em>").Render())
	want := `<h3><em>bold</em></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(h3.New().RawTextf("<%s>test</%s>", "span", "span").Render())
	want := `<h3><span>test</span></h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(h3.New().Class("foo").Text("content").ID("bar").Render())
	want := `<h3 class="foo" id="bar">content</h3>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

