// Code generated by fluent generator. DO NOT EDIT.

package svg

import (
	"bytes"
	"io"
	"strings"
	"sync/atomic"

	"github.com/jpl-au/fluent"
	"github.com/jpl-au/fluent/html5/attr/strokelinecap"
	"github.com/jpl-au/fluent/html5/attr/strokelinejoin"
	"github.com/jpl-au/fluent/node"
)

// Element represents the <svg> SVG element.
type Element struct {
	bufferhint          atomic.Int64
	nodes               []node.Node
	dynamic             string
	height              string
	memoise             any
	preserveAspectRatio string
	viewBox             string
	width               string
	xmlns               string
	attr                *[]node.Attribute
	sa                  *svgAttrs
}

// svg returns the shared svg attributes, initialising if nil.
func (e *Element) svg() *svgAttrs {
	if e.sa == nil {
		e.sa = &svgAttrs{}
	}
	return e.sa
}

// New creates the root <svg> element. It renders the SVG namespace
// (xmlns="http://www.w3.org/2000/svg") by default and accepts SVG shapes as
// children.
func New(children ...Shape) *Element {
	nodes := make([]node.Node, len(children))
	for i, child := range children {
		nodes[i] = child
	}
	return &Element{
		nodes: nodes,
		xmlns: "http://www.w3.org/2000/svg",
	}
}

// Width sets the width attribute.
func (e *Element) Width(value string) *Element {
	e.width = value
	return e
}

// Height sets the height attribute.
func (e *Element) Height(value string) *Element {
	e.height = value
	return e
}

// ViewBox sets the viewBox attribute.
func (e *Element) ViewBox(value string) *Element {
	e.viewBox = value
	return e
}

// PreserveAspectRatio sets the preserveAspectRatio attribute.
func (e *Element) PreserveAspectRatio(value string) *Element {
	e.preserveAspectRatio = value
	return e
}

// Xmlns sets the xmlns attribute.
func (e *Element) Xmlns(value string) *Element {
	e.xmlns = value
	return e
}

// ID sets the id attribute.
func (e *Element) ID(id string) *Element {
	e.svg().ID = id
	return e
}

// Class appends to the space-separated class attribute.
func (e *Element) Class(class string) *Element {
	if e.svg().Class == "" {
		e.svg().Class = class
	} else {
		e.svg().Class = strings.Join([]string{e.svg().Class, class}, " ")
	}
	return e
}

// Style sets the style attribute.
func (e *Element) Style(css string) *Element {
	e.svg().Style = css
	return e
}

// Transform sets the transform attribute.
func (e *Element) Transform(transform string) *Element {
	e.svg().Transform = transform
	return e
}

// TabIndex sets the tabindex attribute.
func (e *Element) TabIndex(index string) *Element {
	e.svg().TabIndex = index
	return e
}

// Role sets the role attribute.
func (e *Element) Role(role string) *Element {
	e.svg().Role = role
	return e
}

// SetAria sets an aria-* attribute. The key is prefixed with "aria-".
func (e *Element) SetAria(key string, value string) *Element {
	e.SetAttribute("aria-"+key, value)
	return e
}

// Fill sets the fill attribute.
func (e *Element) Fill(fill string) *Element {
	e.svg().Fill = fill
	return e
}

// Stroke sets the stroke attribute.
func (e *Element) Stroke(stroke string) *Element {
	e.svg().Stroke = stroke
	return e
}

// StrokeWidth sets the stroke-width attribute.
func (e *Element) StrokeWidth(width string) *Element {
	e.svg().StrokeWidth = width
	return e
}

// StrokeLineCap sets the stroke-linecap attribute.
func (e *Element) StrokeLineCap(linecap strokelinecap.StrokeLineCap) *Element {
	e.svg().StrokeLineCap = linecap
	return e
}

// StrokeLineJoin sets the stroke-linejoin attribute.
func (e *Element) StrokeLineJoin(join strokelinejoin.StrokeLineJoin) *Element {
	e.svg().StrokeLineJoin = join
	return e
}

// StrokeDashArray sets the stroke-dasharray attribute.
func (e *Element) StrokeDashArray(dashes string) *Element {
	e.svg().StrokeDashArray = dashes
	return e
}

// Opacity sets the opacity attribute.
func (e *Element) Opacity(opacity string) *Element {
	e.svg().Opacity = opacity
	return e
}

// FillOpacity sets the fill-opacity attribute.
func (e *Element) FillOpacity(opacity string) *Element {
	e.svg().FillOpacity = opacity
	return e
}

// StrokeOpacity sets the stroke-opacity attribute.
func (e *Element) StrokeOpacity(opacity string) *Element {
	e.svg().StrokeOpacity = opacity
	return e
}

// OnClick sets the onclick attribute.
func (e *Element) OnClick(handler string) *Element {
	e.svg().OnClick = handler
	return e
}

// OnMouseDown sets the onmousedown attribute.
func (e *Element) OnMouseDown(handler string) *Element {
	e.svg().OnMouseDown = handler
	return e
}

// OnMouseUp sets the onmouseup attribute.
func (e *Element) OnMouseUp(handler string) *Element {
	e.svg().OnMouseUp = handler
	return e
}

// OnMouseMove sets the onmousemove attribute.
func (e *Element) OnMouseMove(handler string) *Element {
	e.svg().OnMouseMove = handler
	return e
}

// OnMouseOver sets the onmouseover attribute.
func (e *Element) OnMouseOver(handler string) *Element {
	e.svg().OnMouseOver = handler
	return e
}

// OnMouseOut sets the onmouseout attribute.
func (e *Element) OnMouseOut(handler string) *Element {
	e.svg().OnMouseOut = handler
	return e
}

// OnFocus sets the onfocus attribute.
func (e *Element) OnFocus(handler string) *Element {
	e.svg().OnFocus = handler
	return e
}

// OnBlur sets the onblur attribute.
func (e *Element) OnBlur(handler string) *Element {
	e.svg().OnBlur = handler
	return e
}

// SetAttribute sets a custom attribute on the element
func (e *Element) SetAttribute(key string, value string) {
	if e.attr == nil {
		e.attr = &[]node.Attribute{}
	}
	// Update existing attribute or add new one
	for i, attr := range *e.attr {
		if attr.Key == key {
			(*e.attr)[i].Value = value
			return
		}
	}
	*e.attr = append(*e.attr, node.Attribute{Key: key, Value: value})
}

// Add appends children to the element.
func (e *Element) Add(children ...Shape) *Element {
	for _, child := range children {
		e.nodes = append(e.nodes, child)
	}
	return e
}

// Replace replaces all children with the provided ones.
func (e *Element) Replace(children ...Shape) *Element {
	e.nodes = make([]node.Node, len(children))
	for i, child := range children {
		e.nodes[i] = child
	}
	return e
}

// Dynamic marks this element for reactive tracking by the diff engine.
// The key is the element's stable identity across renders: the diff engine
// matches on it to detect changes and send targeted patches, so it must be
// unique within a render tree and must not change between renders. It is
// emitted as the data-fluent-key attribute.
func (e *Element) Dynamic(key string) *Element {
	e.dynamic = key
	return e
}

// IsDynamic reports whether this element has been marked for reactive tracking.
func (e *Element) IsDynamic() bool {
	return e.dynamic != ""
}

// DynamicKey returns the developer-assigned key for diff engine tracking.
// Returns an empty string if the element has not been marked as dynamic.
func (e *Element) DynamicKey() string {
	return e.dynamic
}

// Memoise sets the cache version for this element's subtree. The diff
// engine's memoisation layer (fluent-jit) skips rendering and diffing the
// subtree when the version matches the previous render. Opposite lifecycle
// to the Dynamic key: the key is stable identity, the version changes
// whenever the content does. Plain rendering ignores it entirely.
func (e *Element) Memoise(version any) *Element {
	e.memoise = version
	return e
}

// MemoiseKey returns the cache version set by Memoise, or nil when the
// element is not memoised. Satisfies the memoisation interface consumed
// by fluent-jit.
func (e *Element) MemoiseKey() any {
	return e.memoise
}

// Node interface implementation

// BufferHint seeds the buffer size used for pool allocation and returns
// the element, so it chains. A hint of zero or less is ignored. The next
// render's measured size replaces the hint - see RenderedSize.
func (e *Element) BufferHint(hint int) *Element {
	if hint > 0 {
		e.bufferhint.Store(int64(hint))
	}
	return e
}

// RenderedSize returns the most recent render's measured size in bytes,
// or the BufferHint value before the first render. Every render records
// its size, so a retained element self-tunes: the next render draws a
// right-sized buffer from the pool.
func (e *Element) RenderedSize() int {
	return int(e.bufferhint.Load())
}

// Render writes the element's HTML to w. Write errors are deliberately
// discarded - use WriteTo to observe them.
func (e *Element) Render(w io.Writer) {
	_, _ = e.WriteTo(w)
}

// WriteTo renders into a pooled buffer sized by the last measured render
// (or BufferHint before the first) and writes it to w, returning the byte
// count and any write error. Satisfies io.WriterTo. The size is measured
// before the buffer drains into w, so a retained element self-tunes.
func (e *Element) WriteTo(w io.Writer) (int64, error) {
	buf := fluent.NewBuffer(int(e.bufferhint.Load()))
	e.RenderBuilder(buf)
	e.bufferhint.Store(int64(buf.Len()))
	n, err := buf.WriteTo(w)
	fluent.PutBuffer(buf)
	return n, err
}

// RenderBytes returns the element's HTML as a byte slice, recording the
// measured size for later renders like WriteTo does.
func (e *Element) RenderBytes() []byte {
	buf := bytes.NewBuffer(make([]byte, 0, int(e.bufferhint.Load())))
	e.RenderBuilder(buf)
	e.bufferhint.Store(int64(buf.Len()))
	return buf.Bytes()
}

// AttributeBuilder writes all attributes for the element to the buffer.
func (e *Element) AttributeBuilder(buf *bytes.Buffer) {
	if e.width != "" {
		buf.Write(AttrWidth)
		buf.WriteString(e.width)
		buf.Write(MarkupQuote)
	}
	if e.height != "" {
		buf.Write(AttrHeight)
		buf.WriteString(e.height)
		buf.Write(MarkupQuote)
	}
	if e.viewBox != "" {
		buf.Write(AttrViewBox)
		buf.WriteString(e.viewBox)
		buf.Write(MarkupQuote)
	}
	if e.preserveAspectRatio != "" {
		buf.Write(AttrPreserveAspectRatio)
		buf.WriteString(e.preserveAspectRatio)
		buf.Write(MarkupQuote)
	}
	if e.xmlns != "" {
		buf.Write(AttrXmlns)
		buf.WriteString(e.xmlns)
		buf.Write(MarkupQuote)
	}

	if e.dynamic != "" {
		buf.WriteString(` data-fluent-key="`)
		buf.WriteString(e.dynamic)
		buf.Write(MarkupQuote)
	}

	if e.attr != nil {
		for _, attr := range *e.attr {
			buf.Write(MarkupSpace)
			buf.WriteString(attr.Key)
			buf.Write(MarkupEquals)
			buf.Write(MarkupQuote)
			buf.WriteString(attr.Value)
			buf.Write(MarkupQuote)
		}
	}

	if e.sa != nil {
		e.sa.AttributeBuilder(buf)
	}
}

// RenderBuilder writes the SVG representation directly to a buffer.
func (e *Element) RenderBuilder(buf *bytes.Buffer) {
	buf.Write(TagSvg)
	e.AttributeBuilder(buf)
	buf.Write(MarkupCloseTag)
	for _, child := range e.nodes {
		if child != nil {
			child.RenderBuilder(buf)
		}
	}
	buf.Write(TagSvgClose)
}

// RenderOpen writes the opening tag and attributes to the buffer.
func (e *Element) RenderOpen(buf *bytes.Buffer) {
	buf.Write(TagSvg)
	e.AttributeBuilder(buf)
	buf.Write(MarkupCloseTag)
}

// RenderClose writes the closing tag to the buffer.
func (e *Element) RenderClose(buf *bytes.Buffer) {
	buf.Write(TagSvgClose)
}

// Nodes returns a slice of child nodes.
func (e *Element) Nodes() []node.Node {
	return e.nodes
}

// Attributes returns a pointer to the underlying attributes slice for direct attribute manipulation.
func (e *Element) Attributes() *[]node.Attribute {
	if e.attr == nil {
		slice := make([]node.Attribute, 0, 1)
		e.attr = &slice
	}
	return e.attr
}

// isSVGShape seals Element as an SVG Shape.
func (*Element) isSVGShape() {}
