// Code generated by fluent generator. DO NOT EDIT.

package svg

import (
	"bytes"
	"io"
	"strings"
	"sync/atomic"

	"github.com/jpl-au/fluent"
	"github.com/jpl-au/fluent/html5/attr/strokelinecap"
	"github.com/jpl-au/fluent/html5/attr/strokelinejoin"
	"github.com/jpl-au/fluent/node"
)

// ellipse represents the <ellipse> SVG element.
type ellipse struct {
	bufferhint atomic.Int64
	cx         string
	cy         string
	dynamic    string
	memoise    any
	rx         string
	ry         string
	attr       *[]node.Attribute
	sa         *svgAttrs
}

// svg returns the shared svg attributes, initialising if nil.
func (e *ellipse) svg() *svgAttrs {
	if e.sa == nil {
		e.sa = &svgAttrs{}
	}
	return e.sa
}

// Ellipse defines an ellipse centred at (cx,cy) with radii rx and ry.
func Ellipse() *ellipse {
	return &ellipse{}
}

// Cx sets the cx attribute.
func (e *ellipse) Cx(value string) *ellipse {
	e.cx = node.EscapeAttribute(value)
	return e
}

// Cy sets the cy attribute.
func (e *ellipse) Cy(value string) *ellipse {
	e.cy = node.EscapeAttribute(value)
	return e
}

// Rx sets the rx attribute.
func (e *ellipse) Rx(value string) *ellipse {
	e.rx = node.EscapeAttribute(value)
	return e
}

// Ry sets the ry attribute.
func (e *ellipse) Ry(value string) *ellipse {
	e.ry = node.EscapeAttribute(value)
	return e
}

// ID sets the id attribute.
func (e *ellipse) ID(id string) *ellipse {
	e.svg().ID = node.EscapeAttribute(id)
	return e
}

// Class appends to the space-separated class attribute.
func (e *ellipse) Class(class string) *ellipse {
	class = node.EscapeAttribute(class)
	if e.svg().Class == "" {
		e.svg().Class = class
	} else {
		e.svg().Class = strings.Join([]string{e.svg().Class, class}, " ")
	}
	return e
}

// Style sets the style attribute.
func (e *ellipse) Style(css string) *ellipse {
	e.svg().Style = node.EscapeAttribute(css)
	return e
}

// Transform sets the transform attribute.
func (e *ellipse) Transform(transform string) *ellipse {
	e.svg().Transform = node.EscapeAttribute(transform)
	return e
}

// TabIndex sets the tabindex attribute.
func (e *ellipse) TabIndex(index string) *ellipse {
	e.svg().TabIndex = node.EscapeAttribute(index)
	return e
}

// Role sets the role attribute.
func (e *ellipse) Role(role string) *ellipse {
	e.svg().Role = node.EscapeAttribute(role)
	return e
}

// SetAria sets an aria-* attribute. The key is prefixed with "aria-".
//
// The prefixed key is written to the rendered output verbatim. It is code, not data: pass a fixed,
// developer-controlled key. Never build the key from user input - a key containing a space, quote,
// "=", "/" or ">" changes the markup structure. The value is escaped; the key is not.
func (e *ellipse) SetAria(key string, value string) *ellipse {
	e.SetAttribute("aria-"+key, value)
	return e
}

// Fill sets the fill attribute.
func (e *ellipse) Fill(fill string) *ellipse {
	e.svg().Fill = node.EscapeAttribute(fill)
	return e
}

// Stroke sets the stroke attribute.
func (e *ellipse) Stroke(stroke string) *ellipse {
	e.svg().Stroke = node.EscapeAttribute(stroke)
	return e
}

// StrokeWidth sets the stroke-width attribute.
func (e *ellipse) StrokeWidth(width string) *ellipse {
	e.svg().StrokeWidth = node.EscapeAttribute(width)
	return e
}

// StrokeLineCap sets the stroke-linecap attribute.
func (e *ellipse) StrokeLineCap(linecap strokelinecap.StrokeLineCap) *ellipse {
	e.svg().StrokeLineCap = linecap
	return e
}

// StrokeLineJoin sets the stroke-linejoin attribute.
func (e *ellipse) StrokeLineJoin(join strokelinejoin.StrokeLineJoin) *ellipse {
	e.svg().StrokeLineJoin = join
	return e
}

// StrokeDashArray sets the stroke-dasharray attribute.
func (e *ellipse) StrokeDashArray(dashes string) *ellipse {
	e.svg().StrokeDashArray = node.EscapeAttribute(dashes)
	return e
}

// Opacity sets the opacity attribute.
func (e *ellipse) Opacity(opacity string) *ellipse {
	e.svg().Opacity = node.EscapeAttribute(opacity)
	return e
}

// FillOpacity sets the fill-opacity attribute.
func (e *ellipse) FillOpacity(opacity string) *ellipse {
	e.svg().FillOpacity = node.EscapeAttribute(opacity)
	return e
}

// StrokeOpacity sets the stroke-opacity attribute.
func (e *ellipse) StrokeOpacity(opacity string) *ellipse {
	e.svg().StrokeOpacity = node.EscapeAttribute(opacity)
	return e
}

// OnClick sets the onclick attribute.
func (e *ellipse) OnClick(handler string) *ellipse {
	e.svg().OnClick = node.EscapeAttribute(handler)
	return e
}

// OnMouseDown sets the onmousedown attribute.
func (e *ellipse) OnMouseDown(handler string) *ellipse {
	e.svg().OnMouseDown = node.EscapeAttribute(handler)
	return e
}

// OnMouseUp sets the onmouseup attribute.
func (e *ellipse) OnMouseUp(handler string) *ellipse {
	e.svg().OnMouseUp = node.EscapeAttribute(handler)
	return e
}

// OnMouseMove sets the onmousemove attribute.
func (e *ellipse) OnMouseMove(handler string) *ellipse {
	e.svg().OnMouseMove = node.EscapeAttribute(handler)
	return e
}

// OnMouseOver sets the onmouseover attribute.
func (e *ellipse) OnMouseOver(handler string) *ellipse {
	e.svg().OnMouseOver = node.EscapeAttribute(handler)
	return e
}

// OnMouseOut sets the onmouseout attribute.
func (e *ellipse) OnMouseOut(handler string) *ellipse {
	e.svg().OnMouseOut = node.EscapeAttribute(handler)
	return e
}

// OnFocus sets the onfocus attribute.
func (e *ellipse) OnFocus(handler string) *ellipse {
	e.svg().OnFocus = node.EscapeAttribute(handler)
	return e
}

// OnBlur sets the onblur attribute.
func (e *ellipse) OnBlur(handler string) *ellipse {
	e.svg().OnBlur = node.EscapeAttribute(handler)
	return e
}

// SetAttribute sets a custom attribute on the element, escaping the value.
// For a pre-trusted value that must render verbatim, use SetAttributeRaw.
//
// The key is written to the rendered output verbatim. It is code, not
// data: pass a fixed, developer-controlled key. Never build the key from
// user input - a key containing a space, quote, "=", "/" or ">" changes
// the markup structure. The value is escaped; the key is not.
func (e *ellipse) SetAttribute(key string, value string) {
	value = node.EscapeAttribute(value)
	if e.attr == nil {
		e.attr = &[]node.Attribute{}
	}
	// Update existing attribute or add new one
	for i, attr := range *e.attr {
		if attr.Key == key {
			(*e.attr)[i].Value = value
			return
		}
	}
	*e.attr = append(*e.attr, node.Attribute{Key: key, Value: value})
}

// SetAttributeRaw sets a custom attribute without escaping its value. Use only
// with trusted values (mirrors RawText); prefer SetAttribute, which escapes.
// The key is written verbatim, as on SetAttribute; here the value is too.
func (e *ellipse) SetAttributeRaw(key string, value string) {
	if e.attr == nil {
		e.attr = &[]node.Attribute{}
	}
	for i, attr := range *e.attr {
		if attr.Key == key {
			(*e.attr)[i].Value = value
			return
		}
	}
	*e.attr = append(*e.attr, node.Attribute{Key: key, Value: value})
}

// Dynamic marks this element for reactive tracking by the diff engine.
// The key is the element's stable identity across renders: the diff engine
// matches on it to detect changes and send targeted patches, so it must be
// unique within a render tree and must not change between renders. It is
// emitted, escaped, as the data-fluent-key attribute.
func (e *ellipse) Dynamic(key string) *ellipse {
	e.dynamic = key
	return e
}

// IsDynamic reports whether this element has been marked for reactive tracking.
func (e *ellipse) IsDynamic() bool {
	return e.dynamic != ""
}

// DynamicKey returns the developer-assigned key for diff engine tracking.
// Returns an empty string if the element has not been marked as dynamic.
func (e *ellipse) DynamicKey() string {
	return e.dynamic
}

// Memoise sets the cache version for this element's subtree. The diff
// engine's memoisation layer (fluent-jit) skips rendering and diffing the
// subtree when the version matches the previous render. Opposite lifecycle
// to the Dynamic key: the key is stable identity, the version changes
// whenever the content does. Plain rendering ignores it entirely.
func (e *ellipse) Memoise(version any) *ellipse {
	e.memoise = version
	return e
}

// MemoiseKey returns the cache version set by Memoise, or nil when the
// element is not memoised. Satisfies the memoisation interface consumed
// by fluent-jit.
func (e *ellipse) MemoiseKey() any {
	return e.memoise
}

// Node interface implementation

// BufferHint seeds the buffer size used for pool allocation and returns
// the element, so it chains. A hint of zero or less is ignored. The next
// render's measured size replaces the hint - see RenderedSize.
func (e *ellipse) BufferHint(hint int) *ellipse {
	if hint > 0 {
		e.bufferhint.Store(int64(hint))
	}
	return e
}

// RenderedSize returns the most recent render's measured size in bytes,
// or the BufferHint value before the first render. Every render records
// its size, so a retained element self-tunes: the next render draws a
// right-sized buffer from the pool.
func (e *ellipse) RenderedSize() int {
	return int(e.bufferhint.Load())
}

// Render writes the element's HTML to w. Write errors are deliberately
// discarded - use WriteTo to observe them.
func (e *ellipse) Render(w io.Writer) {
	_, _ = e.WriteTo(w)
}

// WriteTo renders into a pooled buffer sized by the last measured render
// (or BufferHint before the first) and writes it to w, returning the byte
// count and any write error. Satisfies io.WriterTo. The size is measured
// before the buffer drains into w, so a retained element self-tunes.
func (e *ellipse) WriteTo(w io.Writer) (int64, error) {
	buf := fluent.NewBuffer(int(e.bufferhint.Load()))
	e.RenderBuilder(buf)
	e.bufferhint.Store(int64(buf.Len()))
	n, err := buf.WriteTo(w)
	fluent.PutBuffer(buf)
	return n, err
}

// RenderBytes returns the element's HTML as a byte slice, recording the
// measured size for later renders like WriteTo does.
func (e *ellipse) RenderBytes() []byte {
	buf := bytes.NewBuffer(make([]byte, 0, int(e.bufferhint.Load())))
	e.RenderBuilder(buf)
	e.bufferhint.Store(int64(buf.Len()))
	return buf.Bytes()
}

// AttributeBuilder writes all attributes for the element to the buffer.
func (e *ellipse) AttributeBuilder(buf *bytes.Buffer) {
	if e.cx != "" {
		buf.Write(AttrCx)
		buf.WriteString(e.cx)
		buf.Write(MarkupQuote)
	}
	if e.cy != "" {
		buf.Write(AttrCy)
		buf.WriteString(e.cy)
		buf.Write(MarkupQuote)
	}
	if e.rx != "" {
		buf.Write(AttrRx)
		buf.WriteString(e.rx)
		buf.Write(MarkupQuote)
	}
	if e.ry != "" {
		buf.Write(AttrRy)
		buf.WriteString(e.ry)
		buf.Write(MarkupQuote)
	}

	if e.dynamic != "" {
		buf.WriteString(` data-fluent-key="`)
		buf.WriteString(node.EscapeAttribute(e.dynamic))
		buf.Write(MarkupQuote)
	}

	if e.attr != nil {
		for _, attr := range *e.attr {
			buf.Write(MarkupSpace)
			buf.WriteString(attr.Key)
			buf.Write(MarkupEquals)
			buf.Write(MarkupQuote)
			buf.WriteString(attr.Value)
			buf.Write(MarkupQuote)
		}
	}

	if e.sa != nil {
		e.sa.AttributeBuilder(buf)
	}
}

// RenderBuilder writes the SVG representation directly to a buffer.
func (e *ellipse) RenderBuilder(buf *bytes.Buffer) {
	buf.Write(TagEllipse)
	e.AttributeBuilder(buf)
	buf.Write(MarkupSelfCloseTag)
}

// RenderOpen writes the opening tag and attributes to the buffer.
func (e *ellipse) RenderOpen(buf *bytes.Buffer) {
	buf.Write(TagEllipse)
	e.AttributeBuilder(buf)
	buf.Write(MarkupSelfCloseTag)
}

// RenderClose writes nothing. A self-closing SVG element has no closing tag.
func (e *ellipse) RenderClose(buf *bytes.Buffer) {
}

// Nodes returns nil. A self-closing SVG element holds no children.
func (e *ellipse) Nodes() []node.Node {
	return nil
}

// Attributes returns a pointer to the underlying attributes slice for direct attribute manipulation.
func (e *ellipse) Attributes() *[]node.Attribute {
	if e.attr == nil {
		slice := make([]node.Attribute, 0, 1)
		e.attr = &slice
	}
	return e.attr
}

// isSVGShape seals ellipse as an SVG Shape.
func (*ellipse) isSVGShape() {}
