// Code generated by fluent generator. DO NOT EDIT.

// Package popover defines the [Popover] type and its predefined values.
//
// Popover behavior for elements designated as popover content. Controls how popovers
// are managed, dismissed, and interact with other page elements.
package popover

import (
	"github.com/jpl-au/fluent/node"
)

// Popover is a typed value for the HTML popover attribute.
//
// Popover behavior for elements designated as popover content. Controls how popovers
// are managed, dismissed, and interact with other page elements.
type Popover []byte

// Variables for Popover values
var (
	// Auto Automatic popover management with light dismiss behavior. Popover closes when
	// user clicks outside, presses Escape, or opens another auto popover.
	Auto = Popover("auto")

	// Manual Manual popover management requiring explicit close actions. Popover only closes
	// when specifically commanded via JavaScript or popover target actions.
	Manual = Popover("manual")
)

// Custom allows setting a custom Popover value for edge cases or future specifications.
// Use this when the predefined constants don't cover your specific use case.
func Custom(value string) Popover {
	return Popover(node.EscapeAttribute(value))
}
