// Code generated by fluent generator. DO NOT EDIT.

// Package dot provides convenience wrappers for fluent HTML element constructors.
//
// This package is designed to be used with Go's dot import feature, allowing
// you to write HTML generation code without package prefixes:
//
//	import (
//	    . "github.com/jpl-au/fluent/dot"
//	    "github.com/jpl-au/fluent/html5/meta"
//	)
//
//	func render() node.Node {
//	    return Html(
//	        Head(
//	            meta.UTF8(),
//	            Title().Text("My Page"),
//	            Style().RawText("body { font-family: sans-serif; }"),
//	        ),
//	        Body(
//	            Div(
//	                H1().Text("Welcome"),
//	                P().Text("Hello, world!"),
//	            ).Class("container"),
//	        ),
//	    )
//	}
//
// # Function Naming
//
// Each HTML element has a wrapper function matching its tag name:
//   - Div(children ...node.Node) - creates a <div> element
//   - H1(children ...node.Node) - creates an <h1> element
//   - etc.
//
// Specialised constructors (like meta.UTF8()) require importing
// the element package directly.
//
// # Adding Content
//
// Use the .Text() method chain to add text content:
//
//	P().Text("Hello, world!")
//	H1().Class("title").Text("Welcome")
//	Style().RawText("body { color: red; }")
//
// Content methods available:
//   - .Text(s) - adds escaped text content
//   - .Textf(format, args...) - adds formatted escaped text
//   - .Static(s) - adds static text (JIT-optimisable)
//   - .RawText(s) - adds unescaped HTML content
//   - .RawTextf(format, args...) - adds formatted unescaped HTML
//
// # Alternative: Package Imports
//
// If you prefer explicit package prefixes, import element packages directly:
//
//	import "github.com/jpl-au/fluent/html5/div"
//
//	el := div.New().Class("container").Text("Hello")
package dot

import (
	"github.com/jpl-au/fluent/html5/thead"
	"github.com/jpl-au/fluent/html5/col"
	"github.com/jpl-au/fluent/html5/svg"
	"github.com/jpl-au/fluent/html5/fieldset"
	"github.com/jpl-au/fluent/html5/mark"
	"github.com/jpl-au/fluent/html5/button"
	"github.com/jpl-au/fluent/html5/tr"
	"github.com/jpl-au/fluent/html5/dropdown"
	"github.com/jpl-au/fluent/html5/summary"
	"github.com/jpl-au/fluent/html5/td"
	"github.com/jpl-au/fluent/html5/variable"
	"github.com/jpl-au/fluent/html5/wbr"
	"github.com/jpl-au/fluent/html5/input"
	"github.com/jpl-au/fluent/html5/a"
	"github.com/jpl-au/fluent/html5/datalist"
	"github.com/jpl-au/fluent/html5/meter"
	"github.com/jpl-au/fluent/html5/q"
	"github.com/jpl-au/fluent/html5/sub"
	"github.com/jpl-au/fluent/html5/dialog"
	"github.com/jpl-au/fluent/html5/figure"
	"github.com/jpl-au/fluent/html5/ins"
	"github.com/jpl-au/fluent/html5/section"
	"github.com/jpl-au/fluent/html5/area"
	"github.com/jpl-au/fluent/html5/html"
	"github.com/jpl-au/fluent/html5/nav"
	"github.com/jpl-au/fluent/html5/u"
	"github.com/jpl-au/fluent/html5/bdi"
	"github.com/jpl-au/fluent/html5/source"
	"github.com/jpl-au/fluent/html5/textarea"
	"github.com/jpl-au/fluent/html5/code"
	"github.com/jpl-au/fluent/html5/em"
	"github.com/jpl-au/fluent/html5/p"
	"github.com/jpl-au/fluent/html5/pre"
	"github.com/jpl-au/fluent/node"
	"github.com/jpl-au/fluent/html5/caption"
	"github.com/jpl-au/fluent/html5/b"
	"github.com/jpl-au/fluent/html5/hr"
	"github.com/jpl-au/fluent/html5/span"
	"github.com/jpl-au/fluent/html5/slot"
	"github.com/jpl-au/fluent/html5/template"
	"github.com/jpl-au/fluent/html5/div"
	"github.com/jpl-au/fluent/html5/dl"
	"github.com/jpl-au/fluent/html5/del"
	"github.com/jpl-au/fluent/html5/legend"
	"github.com/jpl-au/fluent/html5/script"
	"github.com/jpl-au/fluent/html5/track"
	"github.com/jpl-au/fluent/html5/article"
	"github.com/jpl-au/fluent/html5/footer"
	"github.com/jpl-au/fluent/html5/h1"
	"github.com/jpl-au/fluent/html5/h2"
	"github.com/jpl-au/fluent/html5/link"
	"github.com/jpl-au/fluent/html5/math"
	"github.com/jpl-au/fluent/html5/title"
	"github.com/jpl-au/fluent/html5/address"
	"github.com/jpl-au/fluent/html5/aside"
	"github.com/jpl-au/fluent/html5/picture"
	"github.com/jpl-au/fluent/html5/tbody"
	"github.com/jpl-au/fluent/html5/body"
	"github.com/jpl-au/fluent/html5/dd"
	"github.com/jpl-au/fluent/html5/optgroup"
	"github.com/jpl-au/fluent/html5/search"
	"github.com/jpl-au/fluent/html5/style"
	"github.com/jpl-au/fluent/html5/small"
	"github.com/jpl-au/fluent/html5/strong"
	"github.com/jpl-au/fluent/html5/data"
	"github.com/jpl-au/fluent/html5/img"
	"github.com/jpl-au/fluent/html5/kbd"
	"github.com/jpl-au/fluent/html5/ol"
	"github.com/jpl-au/fluent/html5/table"
	"github.com/jpl-au/fluent/html5/hgroup"
	"github.com/jpl-au/fluent/html5/i"
	"github.com/jpl-au/fluent/html5/blockquote"
	"github.com/jpl-au/fluent/html5/object"
	"github.com/jpl-au/fluent/html5/output"
	"github.com/jpl-au/fluent/html5/samp"
	"github.com/jpl-au/fluent/html5/time"
	"github.com/jpl-au/fluent/html5/bdo"
	"github.com/jpl-au/fluent/html5/h3"
	"github.com/jpl-au/fluent/html5/base"
	"github.com/jpl-au/fluent/html5/dt"
	"github.com/jpl-au/fluent/html5/primary"
	"github.com/jpl-au/fluent/html5/noscript"
	"github.com/jpl-au/fluent/html5/embed"
	"github.com/jpl-au/fluent/html5/rp"
	"github.com/jpl-au/fluent/html5/s"
	"github.com/jpl-au/fluent/html5/ul"
	"github.com/jpl-au/fluent/html5/abbr"
	"github.com/jpl-au/fluent/html5/dfn"
	"github.com/jpl-au/fluent/html5/h5"
	"github.com/jpl-au/fluent/html5/h6"
	"github.com/jpl-au/fluent/html5/option"
	"github.com/jpl-au/fluent/html5/sup"
	"github.com/jpl-au/fluent/html5/audio"
	"github.com/jpl-au/fluent/html5/br"
	"github.com/jpl-au/fluent/html5/imagemap"
	"github.com/jpl-au/fluent/html5/menu"
	"github.com/jpl-au/fluent/html5/progress"
	"github.com/jpl-au/fluent/html5/rt"
	"github.com/jpl-au/fluent/html5/ruby"
	"github.com/jpl-au/fluent/html5/canvas"
	"github.com/jpl-au/fluent/html5/figcaption"
	"github.com/jpl-au/fluent/html5/h4"
	"github.com/jpl-au/fluent/html5/meta"
	"github.com/jpl-au/fluent/html5/tfoot"
	"github.com/jpl-au/fluent/html5/th"
	"github.com/jpl-au/fluent/html5/header"
	"github.com/jpl-au/fluent/html5/iframe"
	"github.com/jpl-au/fluent/html5/colgroup"
	"github.com/jpl-au/fluent/html5/form"
	"github.com/jpl-au/fluent/html5/head"
	"github.com/jpl-au/fluent/html5/cite"
	"github.com/jpl-au/fluent/html5/label"
	"github.com/jpl-au/fluent/html5/li"
	"github.com/jpl-au/fluent/html5/video"
	"github.com/jpl-au/fluent/html5/details"
)

// A Creates a new anchor element without any initial attributes.
// Example: a.New(text.Text("Click here")).Href("https://example.com")
// Renders: <a href="https://example.com">Click here</a>
func A(nodes ...node.Node) *a.Element {
	return a.New(nodes...)
}

// Abbr Creates a new abbreviation element without any initial attributes. Use for basic abbreviations
// where semantic markup is needed.
// Example: abbr.New()
// Renders: <abbr></abbr>
func Abbr(nodes ...node.Node) *abbr.Element {
	return abbr.New(nodes...)
}

// Address Creates a new address element without any initial attributes. Use for basic contact information where semantic markup is needed.
// Example: address.New()
// Renders: <address></address>
func Address(nodes ...node.Node) *address.Element {
	return address.New(nodes...)
}

// Area Creates a new area element without any initial attributes.
// Example: area.New()
// Renders: <area />
func Area() *area.Element {
	return area.New()
}

// Article Creates a new article element with optional child nodes
// Example: article.New()
// Renders: <article></article>
func Article(nodes ...node.Node) *article.Element {
	return article.New(nodes...)
}

// Aside Creates a new aside element with the given child nodes.
// Example: aside.New()
// Renders: <aside></aside>
func Aside(nodes ...node.Node) *aside.Element {
	return aside.New(nodes...)
}

// Audio Creates a new audio element without any initial attributes.
// Example: audio.New()
// Renders: <audio></audio>
func Audio(nodes ...node.Node) *audio.Element {
	return audio.New(nodes...)
}

// B Creates a new b element with the given child nodes.
// Example: b.New(text.Text("This text is important."))
// Renders: <b>This text is important.</b>
func B(nodes ...node.Node) *b.Element {
	return b.New(nodes...)
}

// Base Creates a new base element without any initial attributes.
// Example: base.New().Href("/docs/")
// Renders: <base href="/docs/" />
func Base() *base.Element {
	return base.New()
}

// Bdi Creates a new bdi element with the given child nodes.
// Example: bdi.New(text.Text("username"))
// Renders: <bdi>username</bdi>
func Bdi(nodes ...node.Node) *bdi.Element {
	return bdi.New(nodes...)
}

// Bdo Creates a new bdo element with child nodes.
// Example: bdo.New(text.Text("Hello"))
// Renders: <bdo>Hello</bdo>
func Bdo(nodes ...node.Node) *bdo.Element {
	return bdo.New(nodes...)
}

// Blockquote Creates a new blockquote element with the given child nodes.
// Example: blockquote.New(blockquote.New())
// Renders: <blockquote><blockquote></blockquote></blockquote>
func Blockquote(nodes ...node.Node) *blockquote.Element {
	return blockquote.New(nodes...)
}

// Body Creates a new body element with the given child nodes.
// Example: body.New(p.New(text.Text("Hello, World!")))
// Renders: <body><p>Hello, World!</p></body>
func Body(nodes ...node.Node) *body.Element {
	return body.New(nodes...)
}

// Br Creates a new br element without any initial attributes.
// Example: br.New()
// Renders: <br />
func Br() *br.Element {
	return br.New()
}

// Button Creates a new button element with the given child nodes.
// Example: button.New(text.Text("Click Me"))
// Renders: <button>Click Me</button>
func Button(nodes ...node.Node) *button.Element {
	return button.New(nodes...)
}

// Canvas Creates a new canvas element with child nodes for fallback content.
// Example: canvas.New(text.Text("Your browser does not support canvas."))
// Renders: <canvas>Your browser does not support canvas.</canvas>
func Canvas(nodes ...node.Node) *canvas.Element {
	return canvas.New(nodes...)
}

// Caption Creates a new caption element with the given child nodes.
// Example: caption.New(text.Text("My Table Caption"))
// Renders: <caption>My Table Caption</caption>
func Caption(nodes ...node.Node) *caption.Element {
	return caption.New(nodes...)
}

// Cite Creates a new cite element with the given child nodes.
// Example: cite.New(text.Text("Nineteen Eighty-Four"))
// Renders: <cite>Nineteen Eighty-Four</cite>
func Cite(nodes ...node.Node) *cite.Element {
	return cite.New(nodes...)
}

// Code Creates a new code element with the given child nodes.
// Example: code.New(text.Text("console.log('Hello, World!');"))
// Renders: <code>console.log('Hello, World!');</code>
func Code(nodes ...node.Node) *code.Element {
	return code.New(nodes...)
}

// Col Creates a new col element without any initial attributes.
// Example: col.New()
// Renders: <col />
func Col() *col.Element {
	return col.New()
}

// Colgroup Creates a new colgroup element with the given child nodes (typically <col> elements).
// Example: colgroup.New(col.New(), col.New().Span(2))
// Renders: <colgroup><col /><col span="2" /></colgroup>
func Colgroup(nodes ...node.Node) *colgroup.Element {
	return colgroup.New(nodes...)
}

// Data Creates a new data element with the given child nodes.
// Example: data.New(text.Text("Mini Ketchup"))
// Renders: <data>Mini Ketchup</data>
func Data(nodes ...node.Node) *data.Element {
	return data.New(nodes...)
}

// Datalist Creates a new datalist element with child nodes (typically <option> elements).
// Example: datalist.New(option.New().Value("Chocolate"), option.New().Value("Vanilla"))
// Renders: <datalist><option value="Chocolate"><option value="Vanilla"></datalist>
func Datalist(nodes ...node.Node) *datalist.Element {
	return datalist.New(nodes...)
}

// Dd Creates a new dd element with child nodes.
// Example: dd.New(text.Text("A large feline inhabiting Bodmin Moor."))
// Renders: <dd>A large feline inhabiting Bodmin Moor.</dd>
func Dd(nodes ...node.Node) *dd.Element {
	return dd.New(nodes...)
}

// Del Creates a new del element with optional child nodes.
// Example: del.New()
// Renders: <del></del>
func Del(nodes ...node.Node) *del.Element {
	return del.New(nodes...)
}

// Details Creates a new details element with the given child nodes.
// Example: details.New(summary.New(text.Text("Details")), text.Text("Something small enough to escape casual notice."))
// Renders: <details><summary>Details</summary>Something small enough to escape casual notice.</details>
func Details(nodes ...node.Node) *details.Element {
	return details.New(nodes...)
}

// Dfn Creates a new dfn element with the given child nodes.
// Example: dfn.New(text.Text("validator"))
// Renders: <dfn>validator</dfn>
func Dfn(nodes ...node.Node) *dfn.Element {
	return dfn.New(nodes...)
}

// Dialog Creates a new dialog element with the given child nodes.
// Example: dialog.New(p.New(text.Text("Greetings, one and all!")))
// Renders: <dialog><p>Greetings, one and all!</p></dialog>
func Dialog(nodes ...node.Node) *dialog.Element {
	return dialog.New(nodes...)
}

// Div Creates a new div element with child nodes.
// Example: div.New(p.New(text.Text("Any kind of content here.")))
// Renders: <div><p>Any kind of content here.</p></div>
func Div(nodes ...node.Node) *div.Element {
	return div.New(nodes...)
}

// Dl Creates a new dl element with the given child nodes (typically <dt> and <dd> elements).
// Example: dl.New(dt.New(text.Text("Term")), dd.New(text.Text("Description")))
// Renders: <dl><dt>Term</dt><dd>Description</dd></dl>
func Dl(nodes ...node.Node) *dl.Element {
	return dl.New(nodes...)
}

// Dt Creates a new dt element with the given child nodes.
// Example: dt.New(text.Text("Term"))
// Renders: <dt>Term</dt>
func Dt(nodes ...node.Node) *dt.Element {
	return dt.New(nodes...)
}

// Em Creates a new em element with the given child nodes.
// Example: em.New(text.Text("now"))
// Renders: <em>now</em>
func Em(nodes ...node.Node) *em.Element {
	return em.New(nodes...)
}

// Embed Creates a new embed element without any initial attributes.
// Example: embed.New()
// Renders: <embed />
func Embed() *embed.Element {
	return embed.New()
}

// Fieldset Creates a new fieldset element with child nodes.
// Example: fieldset.New(legend.New(text.Text("Choose your favorite monster")))
// Renders: <fieldset><legend>Choose your favorite monster</legend></fieldset>
func Fieldset(nodes ...node.Node) *fieldset.Element {
	return fieldset.New(nodes...)
}

// Figcaption Creates a new figcaption element with child nodes.
// Example: figcaption.New(text.Text("An elephant at sunset"))
// Renders: <figcaption>An elephant at sunset</figcaption>
func Figcaption(nodes ...node.Node) *figcaption.Element {
	return figcaption.New(nodes...)
}

// Figure Creates a new figure element with the given child nodes.
// Example: figure.New(img.New().Src("elephant.jpg"), figcaption.New(text.Text("An elephant at sunset")))
// Renders: <figure><img src="elephant.jpg" /><figcaption>An elephant at sunset</figcaption></figure>
func Figure(nodes ...node.Node) *figure.Element {
	return figure.New(nodes...)
}

// Footer Creates a new footer element with the given child nodes.
// Example: footer.New(p.New(text.Text("© 2023 My Website")))
// Renders: <footer><p>© 2023 My Website</p></footer>
func Footer(nodes ...node.Node) *footer.Element {
	return footer.New(nodes...)
}

// Form Creates a new form element with child nodes.
// Example: form.New(form.New())
// Renders: <form><form></form></form>
func Form(nodes ...node.Node) *form.Element {
	return form.New(nodes...)
}

// H1 Creates a new h1 element with the given child nodes.
// Example: h1.New(text.Text("Page Title"))
// Renders: <h1>Page Title</h1>
func H1(nodes ...node.Node) *h1.Element {
	return h1.New(nodes...)
}

// H2 Creates a new h2 element with the given child nodes.
// Example: h2.New(text.Text("Section Title"))
// Renders: <h2>Section Title</h2>
func H2(nodes ...node.Node) *h2.Element {
	return h2.New(nodes...)
}

// H3 Creates a new h3 element with the given child nodes.
// Example: h3.New(text.Text("Subsection Title"))
// Renders: <h3>Subsection Title</h3>
func H3(nodes ...node.Node) *h3.Element {
	return h3.New(nodes...)
}

// H4 Creates a new h4 element with the given child nodes.
// Example: h4.New(text.Text("Detailed Point"))
// Renders: <h4>Detailed Point</h4>
func H4(nodes ...node.Node) *h4.Element {
	return h4.New(nodes...)
}

// H5 Creates a new h5 element with the given child nodes.
// Example: h5.New(text.Text("Sub-point"))
// Renders: <h5>Sub-point</h5>
func H5(nodes ...node.Node) *h5.Element {
	return h5.New(nodes...)
}

// H6 Creates a new h6 element with the given child nodes.
// Example: h6.New(text.Text("Footnote Title"))
// Renders: <h6>Footnote Title</h6>
func H6(nodes ...node.Node) *h6.Element {
	return h6.New(nodes...)
}

// Head Creates a new head element with the given child nodes (metadata content).
// Example: head.New(title.New(text.Text("My Page")), meta.Charset("UTF-8"))
// Renders: <head><title>My Page</title><meta charset="UTF-8" /></head>
func Head(nodes ...node.Node) *head.Element {
	return head.New(nodes...)
}

// Header Creates a new header element with the given child nodes.
// Example: header.New(h1.Text("Welcome"), p.Text("A brief introduction"))
// Renders: <header><h1>Welcome</h1><p>A brief introduction</p></header>
func Header(nodes ...node.Node) *header.Element {
	return header.New(nodes...)
}

// Hgroup Creates a new hgroup element with optional child nodes.
// Example: hgroup.New()
// Renders: <hgroup></hgroup>
func Hgroup(nodes ...node.Node) *hgroup.Element {
	return hgroup.New(nodes...)
}

// Hr Creates a new hr element without any initial attributes.
// Example: hr.New()
// Renders: <hr />
func Hr() *hr.Element {
	return hr.New()
}

// Html Creates a complete HTML5 document with DOCTYPE declaration
// Example: html.New()
// Renders: <!DOCTYPE html><html></html>
func Html(nodes ...node.Node) *html.Element {
	return html.New(nodes...)
}

// I Creates a new italic element with optional child nodes.
// Example: i.New()
// Renders: <i></i>
func I(nodes ...node.Node) *i.Element {
	return i.New(nodes...)
}

// Iframe Creates a new iframe element with optional fallback content.
// Example: iframe.New().Src("/page.html")
// Renders: <iframe src="/page.html"></iframe>
func Iframe(nodes ...node.Node) *iframe.Element {
	return iframe.New(nodes...)
}

// Img Creates a new img element without any initial attributes.
// Example: img.New().Src("photo.jpg").Alt("A beautiful sunset")
// Renders: <img src="photo.jpg" alt="A beautiful sunset" />
func Img() *img.Element {
	return img.New()
}

// Input Creates a new input element without any initial attributes.
// Example: input.New().Type(inputtype.Text).Name("username")
// Renders: <input name="username" type="text" />
func Input() *input.Element {
	return input.New()
}

// Ins Creates a new ins element with optional child nodes.
// Example: ins.New()
// Renders: <ins></ins>
func Ins(nodes ...node.Node) *ins.Element {
	return ins.New(nodes...)
}

// Kbd Creates a new kbd element with optional child nodes.
// Example: kbd.New()
// Renders: <kbd></kbd>
func Kbd(nodes ...node.Node) *kbd.Element {
	return kbd.New(nodes...)
}

// Label Creates a new label element with child nodes.
// Example: label.New()
// Renders: <label></label>
func Label(nodes ...node.Node) *label.Element {
	return label.New(nodes...)
}

// Legend Creates a new legend element with optional child nodes.
// Example: legend.New()
// Renders: <legend></legend>
func Legend(nodes ...node.Node) *legend.Element {
	return legend.New(nodes...)
}

// Li Creates a new list item element with optional child nodes.
// Example: li.New()
// Renders: <li></li>
func Li(nodes ...node.Node) *li.Element {
	return li.New(nodes...)
}

// Link Creates a new link element without any initial attributes.
// Example: link.New()
// Renders: <link />
func Link() *link.Element {
	return link.New()
}

// Primary Creates a new main element with optional child nodes
// Example: primary.New()
// Renders: <main></main>
func Primary(nodes ...node.Node) *primary.Element {
	return primary.New(nodes...)
}

// Imagemap Creates a new map element with optional child nodes.
// Example: map.New()
// Renders: <map></map>
func Imagemap(nodes ...node.Node) *imagemap.Element {
	return imagemap.New(nodes...)
}

// Mark Creates a new mark element with the given child nodes.
// Example: mark.New(text.Text("highlighted text"))
// Renders: <mark>highlighted text</mark>
func Mark(nodes ...node.Node) *mark.Element {
	return mark.New(nodes...)
}

// Math Creates a new math element with optional child nodes.
// Example: math.New()
// Renders: <math></math>
func Math(nodes ...node.Node) *math.Element {
	return math.New(nodes...)
}

// Menu Creates a new menu element with optional child nodes.
// Example: menu.New()
// Renders: <menu></menu>
func Menu(nodes ...node.Node) *menu.Element {
	return menu.New(nodes...)
}

// Meta Creates a new meta element without any initial attributes.
// Example: meta.New()
// Renders: <meta />
func Meta() *meta.Element {
	return meta.New()
}

// Meter Creates a new meter element with optional child nodes
// Example: meter.New()
// Renders: <meter></meter>
func Meter(nodes ...node.Node) *meter.Element {
	return meter.New(nodes...)
}

// Nav Creates a new nav element with optional child nodes
// Example: nav.New()
// Renders: <nav></nav>
func Nav(nodes ...node.Node) *nav.Element {
	return nav.New(nodes...)
}

// Noscript Creates a new noscript element with optional child nodes
// Example: noscript.New()
// Renders: <noscript></noscript>
func Noscript(nodes ...node.Node) *noscript.Element {
	return noscript.New(nodes...)
}

// Object Creates a new object element with optional child nodes
// Example: object.New()
// Renders: <object></object>
func Object(nodes ...node.Node) *object.Element {
	return object.New(nodes...)
}

// Ol Creates a new ordered list element with optional child nodes (typically li elements)
// Example: ol.New()
// Renders: <ol></ol>
func Ol(nodes ...node.Node) *ol.Element {
	return ol.New(nodes...)
}

// Optgroup Creates a new optgroup element with optional child nodes
// Example: optgroup.New()
// Renders: <optgroup></optgroup>
func Optgroup(nodes ...node.Node) *optgroup.Element {
	return optgroup.New(nodes...)
}

// Option Creates a new option element with optional child nodes
// Example: option.New()
// Renders: <option></option>
func Option(nodes ...node.Node) *option.Element {
	return option.New(nodes...)
}

// Output Creates a new output element with optional child nodes
// Example: output.New()
// Renders: <output></output>
func Output(nodes ...node.Node) *output.Element {
	return output.New(nodes...)
}

// P Creates a new paragraph element with optional child nodes
// Example: p.New(text.Text("Hello"))
// Renders: <p>Hello</p>
func P(nodes ...node.Node) *p.Element {
	return p.New(nodes...)
}

// Picture Creates a new picture element with child nodes (typically <source> and <img> elements).
// Example: picture.New(source.New().Srcset("large.jpg").Media("(min-width: 800px)"), img.New().Src("small.jpg"))
// Renders: <picture><source srcset="large.jpg" media="(min-width: 800px)"><img src="small.jpg"></picture>
func Picture(nodes ...node.Node) *picture.Element {
	return picture.New(nodes...)
}

// Pre Creates a new pre element with the given child nodes
// Example: pre.New(text.Text("Code"))
// Renders: <pre>Code</pre>
func Pre(nodes ...node.Node) *pre.Element {
	return pre.New(nodes...)
}

// Progress Creates a new progress element with optional child nodes for fallback content.
// Example: progress.New()
// Renders: <progress></progress>
func Progress(nodes ...node.Node) *progress.Element {
	return progress.New(nodes...)
}

// Q Creates a new q element with optional child nodes.
// Example: q.New(text.Text("To be or not to be"))
// Renders: <q>To be or not to be</q>
func Q(nodes ...node.Node) *q.Element {
	return q.New(nodes...)
}

// Rp Creates a new rp element with optional child nodes.
// Example: rp.New(text.Text("("))
// Renders: <rp>(</rp>
func Rp(nodes ...node.Node) *rp.Element {
	return rp.New(nodes...)
}

// Rt Creates a new rt element with optional child nodes
// Example: rt.New(text.Text("kan"))
// Renders: <rt>kan</rt>
func Rt(nodes ...node.Node) *rt.Element {
	return rt.New(nodes...)
}

// Ruby Creates a new ruby element with optional child nodes
// Example: ruby.New(text.Text("漢字"))
// Renders: <ruby>漢字</ruby>
func Ruby(nodes ...node.Node) *ruby.Element {
	return ruby.New(nodes...)
}

// S Creates a new s element with optional child nodes.
// Examples:
// s.New() renders <s></s>
// s.New(text.Text("Old price: $100")) renders <s>Old price: $100</s>
func S(nodes ...node.Node) *s.Element {
	return s.New(nodes...)
}

// Samp Creates a new samp element with optional child nodes
// Example: samp.New(text.Text("Output"))
// Renders: <samp>Output</samp>
func Samp(nodes ...node.Node) *samp.Element {
	return samp.New(nodes...)
}

// Script Creates a new script element without any initial attributes
// Example: script.New()
// Renders: <script></script>
func Script(nodes ...node.Node) *script.Element {
	return script.New(nodes...)
}

// Search Creates a new search element with optional child nodes
// Example: search.New()
// Renders: <search></search>
func Search(nodes ...node.Node) *search.Element {
	return search.New(nodes...)
}

// Section Creates a new section element with optional child nodes
// Example: section.New()
// Renders: <section></section>
func Section(nodes ...node.Node) *section.Element {
	return section.New(nodes...)
}

// Dropdown Creates a new select element with optional child nodes
// Example: dropdown.New()
// Renders: <select></select>
func Dropdown(nodes ...node.Node) *dropdown.Element {
	return dropdown.New(nodes...)
}

// Slot Creates a new slot element with optional child nodes.
// Example: slot.New()
// Renders: <slot></slot>
func Slot(nodes ...node.Node) *slot.Element {
	return slot.New(nodes...)
}

// Small Creates a new small element with the given child nodes.
// Example: small.New(text.Text("© 2024 Company Name"))
// Renders: <small>© 2024 Company Name</small>
func Small(nodes ...node.Node) *small.Element {
	return small.New(nodes...)
}

// Source Creates a new source element without any initial attributes.
// Example: source.New().Src("image.webp").Type("image/webp")
// Renders: <source src="image.webp" type="image/webp" />
func Source() *source.Element {
	return source.New()
}

// Span Creates a new span element with optional child nodes.
// Example: span.New()
// Renders: <span></span>
func Span(nodes ...node.Node) *span.Element {
	return span.New(nodes...)
}

// Strong Creates a new strong element with optional child nodes.
// Example: strong.New()
// Renders: <strong></strong>
func Strong(nodes ...node.Node) *strong.Element {
	return strong.New(nodes...)
}

// Style Creates a new style element without any initial attributes.
// Example: style.New()
// Renders: <style></style>
func Style(nodes ...node.Node) *style.Element {
	return style.New(nodes...)
}

// Sub Creates a new sub element with the given child nodes.
// Example: sub.New(text.Text("2"))
// Renders: <sub>2</sub>
func Sub(nodes ...node.Node) *sub.Element {
	return sub.New(nodes...)
}

// Summary Creates a new summary element with optional child nodes.
// Example: summary.New()
// Renders: <summary></summary>
func Summary(nodes ...node.Node) *summary.Element {
	return summary.New(nodes...)
}

// Sup Creates a new sup element with the given child nodes.
// Example: sup.New(text.Text("2"))
// Renders: <sup>2</sup>
func Sup(nodes ...node.Node) *sup.Element {
	return sup.New(nodes...)
}

// Svg Creates a new svg element with optional child nodes.
// Example: svg.New()
// Renders: <svg></svg>
func Svg(nodes ...node.Node) *svg.Element {
	return svg.New(nodes...)
}

// Table Creates a new table element with optional child nodes (typically thead, tbody, tfoot, tr elements).
// Example: table.New()
// Renders: <table></table>
func Table(nodes ...node.Node) *table.Element {
	return table.New(nodes...)
}

// Tbody Creates a new tbody element with optional child nodes (typically tr elements).
// Example: tbody.New()
// Renders: <tbody></tbody>
func Tbody(nodes ...node.Node) *tbody.Element {
	return tbody.New(nodes...)
}

// Td Creates a new table data cell element with optional child nodes.
// Example: td.New()
// Renders: <td></td>
func Td(nodes ...node.Node) *td.Element {
	return td.New(nodes...)
}

// Template Creates a new template element with optional child nodes.
// Example: template.New()
// Renders: <template></template>
func Template(nodes ...node.Node) *template.Element {
	return template.New(nodes...)
}

// Textarea Creates a new textarea element with optional child nodes
// Example: textarea.New()
// Renders: <textarea></textarea>
func Textarea(nodes ...node.Node) *textarea.Element {
	return textarea.New(nodes...)
}

// Tfoot Creates a new tfoot element with optional child nodes.
// Example: tfoot.New()
// Renders: <tfoot></tfoot>
func Tfoot(nodes ...node.Node) *tfoot.Element {
	return tfoot.New(nodes...)
}

// Th Creates a new th element with optional child nodes.
// Example: th.New()
// Renders: <th></th>
func Th(nodes ...node.Node) *th.Element {
	return th.New(nodes...)
}

// Thead Creates a new thead element with optional child nodes.
// Example: thead.New()
// Renders: <thead></thead>
func Thead(nodes ...node.Node) *thead.Element {
	return thead.New(nodes...)
}

// Time Creates a new time element with optional child nodes
// Example: time.New()
// Renders: <time></time>
func Time(nodes ...node.Node) *time.Element {
	return time.New(nodes...)
}

// Title Creates a new title element with text content
// Example: title.New()
// Renders: <title></title>
func Title(nodes ...node.Node) *title.Element {
	return title.New(nodes...)
}

// Tr Creates a new table row element with optional child nodes (typically td or th elements).
// Example: tr.New()
// Renders: <tr></tr>
func Tr(nodes ...node.Node) *tr.Element {
	return tr.New(nodes...)
}

// Track Creates a new track element without any initial attributes.
// Example: track.New()
// Renders: <track />
func Track() *track.Element {
	return track.New()
}

// U Creates a new u element with the given child nodes.
// Example: u.New(text.Text("misspelled"))
func U(nodes ...node.Node) *u.Element {
	return u.New(nodes...)
}

// Ul Creates a new unordered list element with optional child nodes (typically li elements).
// Example: ul.New()
// Renders: <ul></ul>
func Ul(nodes ...node.Node) *ul.Element {
	return ul.New(nodes...)
}

// Variable Creates a new var element with optional child nodes.
// Example: variable.New()
// Renders: <var></var>
func Variable(nodes ...node.Node) *variable.Element {
	return variable.New(nodes...)
}

// Video Creates a new video element with optional child nodes
// Example: video.New()
// Renders: <video></video>
func Video(nodes ...node.Node) *video.Element {
	return video.New(nodes...)
}

// Wbr Creates a new wbr element without any initial attributes.
// Example: wbr.New()
// Renders: <wbr />
func Wbr() *wbr.Element {
	return wbr.New()
}

