// Code generated by fluent generator. DO NOT EDIT.

package col_test

import (
	"bytes"
	"testing"

	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/hidden"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/col"
)

func TestNewCtor(t *testing.T) {
	got := string(col.New().RenderBytes())
	want := `<col />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpanCtor(t *testing.T) {
	got := string(col.Span(3).RenderBytes())
	want := `<col span="3" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpanAttr(t *testing.T) {
	got := string(col.New().Span(42).RenderBytes())
	want := `<col span="42" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(col.New().Class("test").RenderBytes())
	want := `<col class="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(col.New().Class("one").Class("two").Class("three").RenderBytes())
	want := `<col class="one two three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(col.New().ID("test").RenderBytes())
	want := `<col id="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(col.New().Style("test").RenderBytes())
	want := `<col style="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(col.New().Style("one").Style("two").Style("three").RenderBytes())
	want := `<col style="one; two; three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(col.New().Title("test").RenderBytes())
	want := `<col title="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(col.New().Hidden(hidden.True).RenderBytes())
	want := `<col hidden="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenCustom(t *testing.T) {
	got := string(col.New().Hidden(hidden.Custom("custom-value")).RenderBytes())
	want := `<col hidden="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(col.New().TabIndex(42).RenderBytes())
	want := `<col tabindex="42" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(col.New().Role("test").RenderBytes())
	want := `<col role="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(col.New().Lang("test").RenderBytes())
	want := `<col lang="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(col.New().AccessKey("test").RenderBytes())
	want := `<col accesskey="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(col.New().AccessKey("one").AccessKey("two").AccessKey("three").RenderBytes())
	want := `<col accesskey="one two three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(col.New().Anchor("test").RenderBytes())
	want := `<col anchor="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(col.New().AriaLabel("test").RenderBytes())
	want := `<col aria-label="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(col.New().SetAria("label", "test-value").RenderBytes())
	want := `<col aria-label="test-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(col.New().AutoCapitalize(autocapitalize.Off).RenderBytes())
	want := `<col autocapitalize="off" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeCustom(t *testing.T) {
	got := string(col.New().AutoCapitalize(autocapitalize.Custom("custom-value")).RenderBytes())
	want := `<col autocapitalize="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(col.New().AutoCorrect(autocorrect.On).RenderBytes())
	want := `<col autocorrect="on" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectCustom(t *testing.T) {
	got := string(col.New().AutoCorrect(autocorrect.Custom("custom-value")).RenderBytes())
	want := `<col autocorrect="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(col.New().AutoFocus().RenderBytes())
	want := `<col autofocus />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusFalse(t *testing.T) {
	got := string(col.New().AutoFocus().AutoFocus(false).RenderBytes())
	want := `<col />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(col.New().ContentEditable(contenteditable.True).RenderBytes())
	want := `<col contenteditable="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableCustom(t *testing.T) {
	got := string(col.New().ContentEditable(contenteditable.Custom("custom-value")).RenderBytes())
	want := `<col contenteditable="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(col.New().SetData("user-id", "test-value").RenderBytes())
	want := `<col data-user-id="test-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(col.New().Dir(dir.LeftToRight).RenderBytes())
	want := `<col dir="ltr" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirCustom(t *testing.T) {
	got := string(col.New().Dir(dir.Custom("custom-value")).RenderBytes())
	want := `<col dir="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(col.New().Draggable(true).RenderBytes())
	want := `<col draggable="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(col.New().EnterKeyHint(enterkeyhint.Enter).RenderBytes())
	want := `<col enterkeyhint="enter" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintCustom(t *testing.T) {
	got := string(col.New().EnterKeyHint(enterkeyhint.Custom("custom-value")).RenderBytes())
	want := `<col enterkeyhint="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(col.New().ExportParts("test").RenderBytes())
	want := `<col exportparts="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(col.New().Inert().RenderBytes())
	want := `<col inert />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertFalse(t *testing.T) {
	got := string(col.New().Inert().Inert(false).RenderBytes())
	want := `<col />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(col.New().InputMode(inputmode.None).RenderBytes())
	want := `<col inputmode="none" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeCustom(t *testing.T) {
	got := string(col.New().InputMode(inputmode.Custom("custom-value")).RenderBytes())
	want := `<col inputmode="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(col.New().Is("test").RenderBytes())
	want := `<col is="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(col.New().ItemId("test").RenderBytes())
	want := `<col itemid="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(col.New().ItemProp("test").RenderBytes())
	want := `<col itemprop="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(col.New().ItemRef("test").RenderBytes())
	want := `<col itemref="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(col.New().ItemScope().RenderBytes())
	want := `<col itemscope />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeFalse(t *testing.T) {
	got := string(col.New().ItemScope().ItemScope(false).RenderBytes())
	want := `<col />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(col.New().ItemType("test").RenderBytes())
	want := `<col itemtype="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(col.New().Nonce("test").RenderBytes())
	want := `<col nonce="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(col.New().Part("test").RenderBytes())
	want := `<col part="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(col.New().Part("one").Part("two").Part("three").RenderBytes())
	want := `<col part="one two three" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(col.New().Popover(popover.Auto).RenderBytes())
	want := `<col popover="auto" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverCustom(t *testing.T) {
	got := string(col.New().Popover(popover.Custom("custom-value")).RenderBytes())
	want := `<col popover="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(col.New().Slot("test").RenderBytes())
	want := `<col slot="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(col.New().SpellCheck(spellcheck.True).RenderBytes())
	want := `<col spellcheck="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckCustom(t *testing.T) {
	got := string(col.New().SpellCheck(spellcheck.Custom("custom-value")).RenderBytes())
	want := `<col spellcheck="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(col.New().Translate(translate.Yes).RenderBytes())
	want := `<col translate="yes" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateCustom(t *testing.T) {
	got := string(col.New().Translate(translate.Custom("custom-value")).RenderBytes())
	want := `<col translate="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(col.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).RenderBytes())
	want := `<col virtualkeyboardpolicy="auto" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyCustom(t *testing.T) {
	got := string(col.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Custom("custom-value")).RenderBytes())
	want := `<col virtualkeyboardpolicy="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(col.New().WritingSuggestions(writingsuggestions.True).RenderBytes())
	want := `<col writingsuggestions="true" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsCustom(t *testing.T) {
	got := string(col.New().WritingSuggestions(writingsuggestions.Custom("custom-value")).RenderBytes())
	want := `<col writingsuggestions="custom-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(col.New().OnClick("test").RenderBytes())
	want := `<col onclick="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(col.New().OnChange("test").RenderBytes())
	want := `<col onchange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(col.New().OnInput("test").RenderBytes())
	want := `<col oninput="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(col.New().OnFocus("test").RenderBytes())
	want := `<col onfocus="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(col.New().OnBlur("test").RenderBytes())
	want := `<col onblur="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(col.New().OnSubmit("test").RenderBytes())
	want := `<col onsubmit="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(col.New().OnLoad("test").RenderBytes())
	want := `<col onload="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(col.New().OnError("test").RenderBytes())
	want := `<col onerror="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(col.New().SetEvent("onclick", "test-value").RenderBytes())
	want := `<col onclick="test-value" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(col.New().OnAbort("test").RenderBytes())
	want := `<col onabort="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(col.New().OnAutoComplete("test").RenderBytes())
	want := `<col onautocomplete="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(col.New().OnAutoCompleteError("test").RenderBytes())
	want := `<col onautocompleteerror="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(col.New().OnCancel("test").RenderBytes())
	want := `<col oncancel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(col.New().OnCanPlay("test").RenderBytes())
	want := `<col oncanplay="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(col.New().OnCanPlayThrough("test").RenderBytes())
	want := `<col oncanplaythrough="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(col.New().OnClose("test").RenderBytes())
	want := `<col onclose="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(col.New().OnContextMenu("test").RenderBytes())
	want := `<col oncontextmenu="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(col.New().OnCueChange("test").RenderBytes())
	want := `<col oncuechange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(col.New().OnDblClick("test").RenderBytes())
	want := `<col ondblclick="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(col.New().OnDrag("test").RenderBytes())
	want := `<col ondrag="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(col.New().OnDragEnd("test").RenderBytes())
	want := `<col ondragend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(col.New().OnDragEnter("test").RenderBytes())
	want := `<col ondragenter="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(col.New().OnDragLeave("test").RenderBytes())
	want := `<col ondragleave="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(col.New().OnDragOver("test").RenderBytes())
	want := `<col ondragover="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(col.New().OnDragStart("test").RenderBytes())
	want := `<col ondragstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(col.New().OnDrop("test").RenderBytes())
	want := `<col ondrop="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(col.New().OnDurationChange("test").RenderBytes())
	want := `<col ondurationchange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(col.New().OnEmptied("test").RenderBytes())
	want := `<col onemptied="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(col.New().OnEnded("test").RenderBytes())
	want := `<col onended="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(col.New().OnInvalid("test").RenderBytes())
	want := `<col oninvalid="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(col.New().OnKeyDown("test").RenderBytes())
	want := `<col onkeydown="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(col.New().OnKeyPress("test").RenderBytes())
	want := `<col onkeypress="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(col.New().OnKeyUp("test").RenderBytes())
	want := `<col onkeyup="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(col.New().OnLoadedData("test").RenderBytes())
	want := `<col onloadeddata="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(col.New().OnLoadedMetadata("test").RenderBytes())
	want := `<col onloadedmetadata="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(col.New().OnLoadStart("test").RenderBytes())
	want := `<col onloadstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(col.New().OnMouseDown("test").RenderBytes())
	want := `<col onmousedown="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(col.New().OnMouseEnter("test").RenderBytes())
	want := `<col onmouseenter="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(col.New().OnMouseLeave("test").RenderBytes())
	want := `<col onmouseleave="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(col.New().OnMouseMove("test").RenderBytes())
	want := `<col onmousemove="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(col.New().OnMouseOut("test").RenderBytes())
	want := `<col onmouseout="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(col.New().OnMouseOver("test").RenderBytes())
	want := `<col onmouseover="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(col.New().OnMouseUp("test").RenderBytes())
	want := `<col onmouseup="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(col.New().OnMouseWheel("test").RenderBytes())
	want := `<col onmousewheel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(col.New().OnPause("test").RenderBytes())
	want := `<col onpause="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(col.New().OnPlay("test").RenderBytes())
	want := `<col onplay="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(col.New().OnPlaying("test").RenderBytes())
	want := `<col onplaying="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(col.New().OnProgress("test").RenderBytes())
	want := `<col onprogress="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(col.New().OnRateChange("test").RenderBytes())
	want := `<col onratechange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(col.New().OnReset("test").RenderBytes())
	want := `<col onreset="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(col.New().OnResize("test").RenderBytes())
	want := `<col onresize="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(col.New().OnScroll("test").RenderBytes())
	want := `<col onscroll="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(col.New().OnSeeked("test").RenderBytes())
	want := `<col onseeked="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(col.New().OnSeeking("test").RenderBytes())
	want := `<col onseeking="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(col.New().OnSelect("test").RenderBytes())
	want := `<col onselect="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(col.New().OnShow("test").RenderBytes())
	want := `<col onshow="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(col.New().OnSort("test").RenderBytes())
	want := `<col onsort="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(col.New().OnStalled("test").RenderBytes())
	want := `<col onstalled="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(col.New().OnSuspend("test").RenderBytes())
	want := `<col onsuspend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(col.New().OnTimeUpdate("test").RenderBytes())
	want := `<col ontimeupdate="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(col.New().OnToggle("test").RenderBytes())
	want := `<col ontoggle="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(col.New().OnVolumeChange("test").RenderBytes())
	want := `<col onvolumechange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(col.New().OnWaiting("test").RenderBytes())
	want := `<col onwaiting="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAuxClickAttr(t *testing.T) {
	got := string(col.New().OnAuxClick("test").RenderBytes())
	want := `<col onauxclick="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWheelAttr(t *testing.T) {
	got := string(col.New().OnWheel("test").RenderBytes())
	want := `<col onwheel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCopyAttr(t *testing.T) {
	got := string(col.New().OnCopy("test").RenderBytes())
	want := `<col oncopy="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCutAttr(t *testing.T) {
	got := string(col.New().OnCut("test").RenderBytes())
	want := `<col oncut="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPasteAttr(t *testing.T) {
	got := string(col.New().OnPaste("test").RenderBytes())
	want := `<col onpaste="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollEndAttr(t *testing.T) {
	got := string(col.New().OnScrollEnd("test").RenderBytes())
	want := `<col onscrollend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFormDataAttr(t *testing.T) {
	got := string(col.New().OnFormData("test").RenderBytes())
	want := `<col onformdata="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationCancelAttr(t *testing.T) {
	got := string(col.New().OnAnimationCancel("test").RenderBytes())
	want := `<col onanimationcancel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationEndAttr(t *testing.T) {
	got := string(col.New().OnAnimationEnd("test").RenderBytes())
	want := `<col onanimationend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationIterationAttr(t *testing.T) {
	got := string(col.New().OnAnimationIteration("test").RenderBytes())
	want := `<col onanimationiteration="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationStartAttr(t *testing.T) {
	got := string(col.New().OnAnimationStart("test").RenderBytes())
	want := `<col onanimationstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionCancelAttr(t *testing.T) {
	got := string(col.New().OnTransitionCancel("test").RenderBytes())
	want := `<col ontransitioncancel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionEndAttr(t *testing.T) {
	got := string(col.New().OnTransitionEnd("test").RenderBytes())
	want := `<col ontransitionend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionRunAttr(t *testing.T) {
	got := string(col.New().OnTransitionRun("test").RenderBytes())
	want := `<col ontransitionrun="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionStartAttr(t *testing.T) {
	got := string(col.New().OnTransitionStart("test").RenderBytes())
	want := `<col ontransitionstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeToggleAttr(t *testing.T) {
	got := string(col.New().OnBeforeToggle("test").RenderBytes())
	want := `<col onbeforetoggle="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeInputAttr(t *testing.T) {
	got := string(col.New().OnBeforeInput("test").RenderBytes())
	want := `<col onbeforeinput="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeMatchAttr(t *testing.T) {
	got := string(col.New().OnBeforeMatch("test").RenderBytes())
	want := `<col onbeforematch="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCommandAttr(t *testing.T) {
	got := string(col.New().OnCommand("test").RenderBytes())
	want := `<col oncommand="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextLostAttr(t *testing.T) {
	got := string(col.New().OnContextLost("test").RenderBytes())
	want := `<col oncontextlost="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextRestoredAttr(t *testing.T) {
	got := string(col.New().OnContextRestored("test").RenderBytes())
	want := `<col oncontextrestored="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSecurityPolicyViolationAttr(t *testing.T) {
	got := string(col.New().OnSecurityPolicyViolation("test").RenderBytes())
	want := `<col onsecuritypolicyviolation="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSlotChangeAttr(t *testing.T) {
	got := string(col.New().OnSlotChange("test").RenderBytes())
	want := `<col onslotchange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerDownAttr(t *testing.T) {
	got := string(col.New().OnPointerDown("test").RenderBytes())
	want := `<col onpointerdown="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerUpAttr(t *testing.T) {
	got := string(col.New().OnPointerUp("test").RenderBytes())
	want := `<col onpointerup="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerMoveAttr(t *testing.T) {
	got := string(col.New().OnPointerMove("test").RenderBytes())
	want := `<col onpointermove="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerEnterAttr(t *testing.T) {
	got := string(col.New().OnPointerEnter("test").RenderBytes())
	want := `<col onpointerenter="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerLeaveAttr(t *testing.T) {
	got := string(col.New().OnPointerLeave("test").RenderBytes())
	want := `<col onpointerleave="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOverAttr(t *testing.T) {
	got := string(col.New().OnPointerOver("test").RenderBytes())
	want := `<col onpointerover="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOutAttr(t *testing.T) {
	got := string(col.New().OnPointerOut("test").RenderBytes())
	want := `<col onpointerout="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerCancelAttr(t *testing.T) {
	got := string(col.New().OnPointerCancel("test").RenderBytes())
	want := `<col onpointercancel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnGotPointerCaptureAttr(t *testing.T) {
	got := string(col.New().OnGotPointerCapture("test").RenderBytes())
	want := `<col ongotpointercapture="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLostPointerCaptureAttr(t *testing.T) {
	got := string(col.New().OnLostPointerCapture("test").RenderBytes())
	want := `<col onlostpointercapture="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchStartAttr(t *testing.T) {
	got := string(col.New().OnTouchStart("test").RenderBytes())
	want := `<col ontouchstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchEndAttr(t *testing.T) {
	got := string(col.New().OnTouchEnd("test").RenderBytes())
	want := `<col ontouchend="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchMoveAttr(t *testing.T) {
	got := string(col.New().OnTouchMove("test").RenderBytes())
	want := `<col ontouchmove="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchCancelAttr(t *testing.T) {
	got := string(col.New().OnTouchCancel("test").RenderBytes())
	want := `<col ontouchcancel="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectStartAttr(t *testing.T) {
	got := string(col.New().OnSelectStart("test").RenderBytes())
	want := `<col onselectstart="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectionChangeAttr(t *testing.T) {
	got := string(col.New().OnSelectionChange("test").RenderBytes())
	want := `<col onselectionchange="test" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicKey(t *testing.T) {
	got := string(col.New().Dynamic("mykey").RenderBytes())
	want := `<col data-fluent-key="mykey" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestMemoiseKey(t *testing.T) {
	el := col.New()
	if el.MemoiseKey() != nil {
		t.Error("new element should have no memoise version")
	}
	el.Memoise(7)
	if el.MemoiseKey() != 7 {
		t.Errorf("MemoiseKey() = %v, want 7", el.MemoiseKey())
	}
}

func TestNotDynamic(t *testing.T) {
	el := col.New()
	if el.IsDynamic() {
		t.Error("new element should not be dynamic")
	}
	if el.DynamicKey() != "" {
		t.Errorf("DynamicKey() should be empty, got %q", el.DynamicKey())
	}
}

func TestRenderMethodsMatch(t *testing.T) {
	el := col.New()
	el.SetAttribute("data-check", "render")
	want := string(el.RenderBytes())

	var buf bytes.Buffer
	el.Render(&buf)
	if buf.String() != want {
		t.Errorf("Render: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	n, err := el.WriteTo(&buf)
	if err != nil {
		t.Fatalf("WriteTo: %v", err)
	}
	if buf.String() != want {
		t.Errorf("WriteTo: got %q, want %q", buf.String(), want)
	}
	if n != int64(len(want)) {
		t.Errorf("WriteTo returned %d bytes, want %d", n, len(want))
	}

	buf.Reset()
	el.RenderBuilder(&buf)
	if buf.String() != want {
		t.Errorf("RenderBuilder: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	el.RenderOpen(&buf)
	el.RenderClose(&buf)
	if buf.String() != want {
		t.Errorf("RenderOpen+RenderClose: got %q, want %q", buf.String(), want)
	}
}

func TestSetAttributeEscapes(t *testing.T) {
	el := col.New()
	el.SetAttribute("data-sample", "\"><script>")
	got := string(el.RenderBytes())
	want := `<col data-sample="&#34;&gt;&lt;script&gt;" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAttributeRaw(t *testing.T) {
	el := col.New()
	// A pre-escaped entity must render verbatim; SetAttribute would double-escape it.
	el.SetAttributeRaw("data-sample", "a&amp;b")
	got := string(el.RenderBytes())
	want := `<col data-sample="a&amp;b" />`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}
