// Code generated by fluent generator. DO NOT EDIT.

package tr_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/hidden"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/td"
	"github.com/jpl-au/fluent/html5/th"
	"github.com/jpl-au/fluent/html5/tr"
)

func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(tr.New().Render())
	want := `<tr></tr>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(tr.New(tr.New()).Render())
	want = `<tr><tr></tr></tr>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestCellsCtor(t *testing.T) {
	got := string(tr.Cells(td.Text("a"), td.Text("b")).Render())
	want := `<tr><td>a</td><td>b</td></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHeadersCtor(t *testing.T) {
	got := string(tr.Headers(th.Col("Name"), th.Col("Age")).Render())
	want := `<tr><th scope="col">Name</th><th scope="col">Age</th></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAlignAttr(t *testing.T) {
	got := string(tr.New().Align("test").Render())
	want := `<tr align="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestBgColorAttr(t *testing.T) {
	got := string(tr.New().BgColor("test").Render())
	want := `<tr bgcolor="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestCharAttr(t *testing.T) {
	got := string(tr.New().Char("test").Render())
	want := `<tr char="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestCharOffAttr(t *testing.T) {
	got := string(tr.New().CharOff("test").Render())
	want := `<tr charoff="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVAlignAttr(t *testing.T) {
	got := string(tr.New().VAlign("test").Render())
	want := `<tr valign="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(tr.New().Class("test").Render())
	want := `<tr class="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(tr.New().Class("one").Class("two").Class("three").Render())
	want := `<tr class="one two three"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(tr.New().ID("test").Render())
	want := `<tr id="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(tr.New().Style("test").Render())
	want := `<tr style="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(tr.New().Style("one").Style("two").Style("three").Render())
	want := `<tr style="one; two; three"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(tr.New().Title("test").Render())
	want := `<tr title="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(tr.New().Hidden(hidden.True).Render())
	want := `<tr hidden="true"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(tr.New().TabIndex(42).Render())
	want := `<tr tabindex="42"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(tr.New().Role("test").Render())
	want := `<tr role="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(tr.New().Lang("test").Render())
	want := `<tr lang="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(tr.New().AccessKey("test").Render())
	want := `<tr accesskey="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(tr.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<tr accesskey="one two three"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(tr.New().Anchor("test").Render())
	want := `<tr anchor="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(tr.New().AriaLabel("test").Render())
	want := `<tr aria-label="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(tr.New().SetAria("label", "test-value").Render())
	want := `<tr aria-label="test-value"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(tr.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<tr autocapitalize="off"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(tr.New().AutoCorrect(autocorrect.On).Render())
	want := `<tr autocorrect="on"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(tr.New().AutoFocus().Render())
	want := `<tr autofocus></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(tr.New().ContentEditable(contenteditable.True).Render())
	want := `<tr contenteditable="true"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(tr.New().SetData("user-id", "test-value").Render())
	want := `<tr data-user-id="test-value"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(tr.New().Dir(dir.LeftToRight).Render())
	want := `<tr dir="ltr"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(tr.New().Draggable().Render())
	want := `<tr draggable></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(tr.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<tr enterkeyhint="enter"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(tr.New().ExportParts("test").Render())
	want := `<tr exportparts="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(tr.New().Inert().Render())
	want := `<tr inert></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(tr.New().InputMode(inputmode.None).Render())
	want := `<tr inputmode="none"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(tr.New().Is("test").Render())
	want := `<tr is="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(tr.New().ItemId("test").Render())
	want := `<tr itemid="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(tr.New().ItemProp("test").Render())
	want := `<tr itemprop="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(tr.New().ItemRef("test").Render())
	want := `<tr itemref="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(tr.New().ItemScope().Render())
	want := `<tr itemscope></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(tr.New().ItemType("test").Render())
	want := `<tr itemtype="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(tr.New().Nonce("test").Render())
	want := `<tr nonce="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(tr.New().Part("test").Render())
	want := `<tr part="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(tr.New().Part("one").Part("two").Part("three").Render())
	want := `<tr part="one two three"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(tr.New().Popover(popover.Auto).Render())
	want := `<tr popover="auto"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(tr.New().Slot("test").Render())
	want := `<tr slot="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(tr.New().SpellCheck(spellcheck.True).Render())
	want := `<tr spellcheck="true"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(tr.New().Translate(translate.Yes).Render())
	want := `<tr translate="yes"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(tr.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<tr virtualkeyboardpolicy="auto"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(tr.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<tr writingsuggestions="true"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(tr.New().OnClick("test").Render())
	want := `<tr onclick="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(tr.New().OnChange("test").Render())
	want := `<tr onchange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(tr.New().OnInput("test").Render())
	want := `<tr oninput="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(tr.New().OnFocus("test").Render())
	want := `<tr onfocus="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(tr.New().OnBlur("test").Render())
	want := `<tr onblur="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(tr.New().OnSubmit("test").Render())
	want := `<tr onsubmit="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(tr.New().OnLoad("test").Render())
	want := `<tr onload="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(tr.New().OnError("test").Render())
	want := `<tr onerror="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(tr.New().SetEvent("onclick", "test-value").Render())
	want := `<tr onclick="test-value"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(tr.New().OnAbort("test").Render())
	want := `<tr onabort="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(tr.New().OnAutoComplete("test").Render())
	want := `<tr onautocomplete="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(tr.New().OnAutoCompleteError("test").Render())
	want := `<tr onautocompleteerror="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(tr.New().OnCancel("test").Render())
	want := `<tr oncancel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(tr.New().OnCanPlay("test").Render())
	want := `<tr oncanplay="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(tr.New().OnCanPlayThrough("test").Render())
	want := `<tr oncanplaythrough="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(tr.New().OnClose("test").Render())
	want := `<tr onclose="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(tr.New().OnContextMenu("test").Render())
	want := `<tr oncontextmenu="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(tr.New().OnCueChange("test").Render())
	want := `<tr oncuechange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(tr.New().OnDblClick("test").Render())
	want := `<tr ondblclick="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(tr.New().OnDrag("test").Render())
	want := `<tr ondrag="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(tr.New().OnDragEnd("test").Render())
	want := `<tr ondragend="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(tr.New().OnDragEnter("test").Render())
	want := `<tr ondragenter="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(tr.New().OnDragLeave("test").Render())
	want := `<tr ondragleave="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(tr.New().OnDragOver("test").Render())
	want := `<tr ondragover="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(tr.New().OnDragStart("test").Render())
	want := `<tr ondragstart="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(tr.New().OnDrop("test").Render())
	want := `<tr ondrop="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(tr.New().OnDurationChange("test").Render())
	want := `<tr ondurationchange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(tr.New().OnEmptied("test").Render())
	want := `<tr onemptied="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(tr.New().OnEnded("test").Render())
	want := `<tr onended="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(tr.New().OnInvalid("test").Render())
	want := `<tr oninvalid="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(tr.New().OnKeyDown("test").Render())
	want := `<tr onkeydown="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(tr.New().OnKeyPress("test").Render())
	want := `<tr onkeypress="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(tr.New().OnKeyUp("test").Render())
	want := `<tr onkeyup="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(tr.New().OnLoadedData("test").Render())
	want := `<tr onloadeddata="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(tr.New().OnLoadedMetadata("test").Render())
	want := `<tr onloadedmetadata="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(tr.New().OnLoadStart("test").Render())
	want := `<tr onloadstart="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(tr.New().OnMouseDown("test").Render())
	want := `<tr onmousedown="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(tr.New().OnMouseEnter("test").Render())
	want := `<tr onmouseenter="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(tr.New().OnMouseLeave("test").Render())
	want := `<tr onmouseleave="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(tr.New().OnMouseMove("test").Render())
	want := `<tr onmousemove="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(tr.New().OnMouseOut("test").Render())
	want := `<tr onmouseout="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(tr.New().OnMouseOver("test").Render())
	want := `<tr onmouseover="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(tr.New().OnMouseUp("test").Render())
	want := `<tr onmouseup="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(tr.New().OnMouseWheel("test").Render())
	want := `<tr onmousewheel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(tr.New().OnPause("test").Render())
	want := `<tr onpause="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(tr.New().OnPlay("test").Render())
	want := `<tr onplay="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(tr.New().OnPlaying("test").Render())
	want := `<tr onplaying="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(tr.New().OnProgress("test").Render())
	want := `<tr onprogress="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(tr.New().OnRateChange("test").Render())
	want := `<tr onratechange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(tr.New().OnReset("test").Render())
	want := `<tr onreset="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(tr.New().OnResize("test").Render())
	want := `<tr onresize="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(tr.New().OnScroll("test").Render())
	want := `<tr onscroll="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(tr.New().OnSeeked("test").Render())
	want := `<tr onseeked="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(tr.New().OnSeeking("test").Render())
	want := `<tr onseeking="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(tr.New().OnSelect("test").Render())
	want := `<tr onselect="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(tr.New().OnShow("test").Render())
	want := `<tr onshow="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(tr.New().OnSort("test").Render())
	want := `<tr onsort="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(tr.New().OnStalled("test").Render())
	want := `<tr onstalled="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(tr.New().OnSuspend("test").Render())
	want := `<tr onsuspend="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(tr.New().OnTimeUpdate("test").Render())
	want := `<tr ontimeupdate="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(tr.New().OnToggle("test").Render())
	want := `<tr ontoggle="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(tr.New().OnVolumeChange("test").Render())
	want := `<tr onvolumechange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(tr.New().OnWaiting("test").Render())
	want := `<tr onwaiting="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAuxClickAttr(t *testing.T) {
	got := string(tr.New().OnAuxClick("test").Render())
	want := `<tr onauxclick="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWheelAttr(t *testing.T) {
	got := string(tr.New().OnWheel("test").Render())
	want := `<tr onwheel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCopyAttr(t *testing.T) {
	got := string(tr.New().OnCopy("test").Render())
	want := `<tr oncopy="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCutAttr(t *testing.T) {
	got := string(tr.New().OnCut("test").Render())
	want := `<tr oncut="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPasteAttr(t *testing.T) {
	got := string(tr.New().OnPaste("test").Render())
	want := `<tr onpaste="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollEndAttr(t *testing.T) {
	got := string(tr.New().OnScrollEnd("test").Render())
	want := `<tr onscrollend="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFormDataAttr(t *testing.T) {
	got := string(tr.New().OnFormData("test").Render())
	want := `<tr onformdata="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationCancelAttr(t *testing.T) {
	got := string(tr.New().OnAnimationCancel("test").Render())
	want := `<tr onanimationcancel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationEndAttr(t *testing.T) {
	got := string(tr.New().OnAnimationEnd("test").Render())
	want := `<tr onanimationend="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationIterationAttr(t *testing.T) {
	got := string(tr.New().OnAnimationIteration("test").Render())
	want := `<tr onanimationiteration="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationStartAttr(t *testing.T) {
	got := string(tr.New().OnAnimationStart("test").Render())
	want := `<tr onanimationstart="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionCancelAttr(t *testing.T) {
	got := string(tr.New().OnTransitionCancel("test").Render())
	want := `<tr ontransitioncancel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionEndAttr(t *testing.T) {
	got := string(tr.New().OnTransitionEnd("test").Render())
	want := `<tr ontransitionend="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionRunAttr(t *testing.T) {
	got := string(tr.New().OnTransitionRun("test").Render())
	want := `<tr ontransitionrun="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionStartAttr(t *testing.T) {
	got := string(tr.New().OnTransitionStart("test").Render())
	want := `<tr ontransitionstart="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeToggleAttr(t *testing.T) {
	got := string(tr.New().OnBeforeToggle("test").Render())
	want := `<tr onbeforetoggle="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeInputAttr(t *testing.T) {
	got := string(tr.New().OnBeforeInput("test").Render())
	want := `<tr onbeforeinput="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeMatchAttr(t *testing.T) {
	got := string(tr.New().OnBeforeMatch("test").Render())
	want := `<tr onbeforematch="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCommandAttr(t *testing.T) {
	got := string(tr.New().OnCommand("test").Render())
	want := `<tr oncommand="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextLostAttr(t *testing.T) {
	got := string(tr.New().OnContextLost("test").Render())
	want := `<tr oncontextlost="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextRestoredAttr(t *testing.T) {
	got := string(tr.New().OnContextRestored("test").Render())
	want := `<tr oncontextrestored="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSecurityPolicyViolationAttr(t *testing.T) {
	got := string(tr.New().OnSecurityPolicyViolation("test").Render())
	want := `<tr onsecuritypolicyviolation="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSlotChangeAttr(t *testing.T) {
	got := string(tr.New().OnSlotChange("test").Render())
	want := `<tr onslotchange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerDownAttr(t *testing.T) {
	got := string(tr.New().OnPointerDown("test").Render())
	want := `<tr onpointerdown="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerUpAttr(t *testing.T) {
	got := string(tr.New().OnPointerUp("test").Render())
	want := `<tr onpointerup="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerMoveAttr(t *testing.T) {
	got := string(tr.New().OnPointerMove("test").Render())
	want := `<tr onpointermove="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerEnterAttr(t *testing.T) {
	got := string(tr.New().OnPointerEnter("test").Render())
	want := `<tr onpointerenter="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerLeaveAttr(t *testing.T) {
	got := string(tr.New().OnPointerLeave("test").Render())
	want := `<tr onpointerleave="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOverAttr(t *testing.T) {
	got := string(tr.New().OnPointerOver("test").Render())
	want := `<tr onpointerover="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOutAttr(t *testing.T) {
	got := string(tr.New().OnPointerOut("test").Render())
	want := `<tr onpointerout="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerCancelAttr(t *testing.T) {
	got := string(tr.New().OnPointerCancel("test").Render())
	want := `<tr onpointercancel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnGotPointerCaptureAttr(t *testing.T) {
	got := string(tr.New().OnGotPointerCapture("test").Render())
	want := `<tr ongotpointercapture="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLostPointerCaptureAttr(t *testing.T) {
	got := string(tr.New().OnLostPointerCapture("test").Render())
	want := `<tr onlostpointercapture="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchStartAttr(t *testing.T) {
	got := string(tr.New().OnTouchStart("test").Render())
	want := `<tr ontouchstart="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchEndAttr(t *testing.T) {
	got := string(tr.New().OnTouchEnd("test").Render())
	want := `<tr ontouchend="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchMoveAttr(t *testing.T) {
	got := string(tr.New().OnTouchMove("test").Render())
	want := `<tr ontouchmove="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchCancelAttr(t *testing.T) {
	got := string(tr.New().OnTouchCancel("test").Render())
	want := `<tr ontouchcancel="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectStartAttr(t *testing.T) {
	got := string(tr.New().OnSelectStart("test").Render())
	want := `<tr onselectstart="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectionChangeAttr(t *testing.T) {
	got := string(tr.New().OnSelectionChange("test").Render())
	want := `<tr onselectionchange="test"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(tr.New(tr.New(), tr.New()).Render())
	want := `<tr><tr></tr><tr></tr></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := tr.New().Add(tr.New(), tr.New())

	// Test rendered output
	got := string(element.Render())
	want := `<tr><tr></tr><tr></tr></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := tr.New(tr.New(), tr.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(tr.New())

	// Test rendered output
	got := string(element.Render())
	want := `<tr><tr></tr></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(tr.New().Text("hello").Render())
	want := `<tr>hello</tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(tr.New().Textf("hello %s", "world").Render())
	want := `<tr>hello world</tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(tr.New().Static("static content").Render())
	want := `<tr>static content</tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(tr.New().RawText("<em>bold</em>").Render())
	want := `<tr><em>bold</em></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(tr.New().RawTextf("<%s>test</%s>", "span", "span").Render())
	want := `<tr><span>test</span></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(tr.New().Class("foo").Text("content").ID("bar").Render())
	want := `<tr class="foo" id="bar">content</tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicKey(t *testing.T) {
	got := string(tr.New().Dynamic("mykey").Render())
	want := `<tr data-tether-key="mykey"></tr>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicNoKey(t *testing.T) {
	el := tr.New().Dynamic()
	if !el.IsDynamic() {
		t.Error("element should be dynamic after calling Dynamic()")
	}
	if el.DynamicKey() != "_" {
		t.Errorf("DynamicKey() should be \"_\", got %q", el.DynamicKey())
	}
	got := string(el.Render())
	want := `<tr></tr>`
	if got != want {
		t.Errorf("Dynamic() without key should not render data-tether-key: got %q, want %q", got, want)
	}
}

func TestNotDynamic(t *testing.T) {
	el := tr.New()
	if el.IsDynamic() {
		t.Error("new element should not be dynamic")
	}
	if el.DynamicKey() != "" {
		t.Errorf("DynamicKey() should be empty, got %q", el.DynamicKey())
	}
}
