// Code generated by fluent generator. DO NOT EDIT.

package slot_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/slot"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
)


func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(slot.New().Render())
	want := `<slot></slot>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(slot.New(slot.New()).Render())
	want = `<slot><slot></slot></slot>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(slot.Text("Default content").Render())
	want := `<slot>Default content</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(slot.Static("Hello World").Render())
	want := `<slot>Hello World</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(slot.RawText("<em>Default</em> content").Render())
	want := `<slot><em>Default</em> content</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	got := string(slot.Textf("%s content", "Default").Render())
	want := `<slot>Default content</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	got := string(slot.RawTextf("<em>%s</em> content", "Default").Render())
	want := `<slot><em>Default</em> content</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNameAttr(t *testing.T) {
	got := string(slot.New().Name("test").Render())
	want := `<slot name="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(slot.New().Class("test").Render())
	want := `<slot class="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(slot.New().Class("one").Class("two").Class("three").Render())
	want := `<slot class="one two three"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(slot.New().ID("test").Render())
	want := `<slot id="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(slot.New().Style("test").Render())
	want := `<slot style="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(slot.New().Style("one").Style("two").Style("three").Render())
	want := `<slot style="one; two; three"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(slot.New().Title("test").Render())
	want := `<slot title="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(slot.New().Hidden().Render())
	want := `<slot hidden="hidden"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(slot.New().TabIndex(42).Render())
	want := `<slot tabindex="42"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(slot.New().Role("test").Render())
	want := `<slot role="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(slot.New().Lang("test").Render())
	want := `<slot lang="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(slot.New().AccessKey("test").Render())
	want := `<slot accesskey="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(slot.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<slot accesskey="one two three"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(slot.New().Anchor("test").Render())
	want := `<slot anchor="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(slot.New().AriaLabel("test").Render())
	want := `<slot arialabel="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(slot.New().SetAria("label", "test-value").Render())
	want := `<slot aria-label="test-value"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(slot.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<slot autocapitalize="off"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(slot.New().AutoCorrect(autocorrect.On).Render())
	want := `<slot autocorrect="on"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(slot.New().AutoFocus().Render())
	want := `<slot autofocus="autofocus"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(slot.New().ContentEditable(contenteditable.True).Render())
	want := `<slot contenteditable="true"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(slot.New().SetData("user-id", "test-value").Render())
	want := `<slot data-user-id="test-value"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(slot.New().Dir(dir.LeftToRight).Render())
	want := `<slot dir="ltr"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(slot.New().Draggable().Render())
	want := `<slot draggable="draggable"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(slot.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<slot enterkeyhint="enter"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(slot.New().ExportParts("test").Render())
	want := `<slot exportparts="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(slot.New().Inert().Render())
	want := `<slot inert="inert"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(slot.New().InputMode(inputmode.None).Render())
	want := `<slot inputmode="none"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(slot.New().Is("test").Render())
	want := `<slot is="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(slot.New().ItemId("test").Render())
	want := `<slot itemid="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(slot.New().ItemProp("test").Render())
	want := `<slot itemprop="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(slot.New().ItemRef("test").Render())
	want := `<slot itemref="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(slot.New().ItemScope().Render())
	want := `<slot itemscope="itemscope"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(slot.New().ItemType("test").Render())
	want := `<slot itemtype="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(slot.New().Nonce("test").Render())
	want := `<slot nonce="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(slot.New().Part("test").Render())
	want := `<slot part="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(slot.New().Part("one").Part("two").Part("three").Render())
	want := `<slot part="one two three"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(slot.New().Popover(popover.Auto).Render())
	want := `<slot popover="auto"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(slot.New().Slot("test").Render())
	want := `<slot slot="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(slot.New().SpellCheck(spellcheck.True).Render())
	want := `<slot spellcheck="true"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(slot.New().Translate(translate.Yes).Render())
	want := `<slot translate="yes"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(slot.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<slot virtualkeyboardpolicy="auto"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(slot.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<slot writingsuggestions="true"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(slot.New().OnClick("test").Render())
	want := `<slot onclick="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(slot.New().OnChange("test").Render())
	want := `<slot onchange="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(slot.New().OnInput("test").Render())
	want := `<slot oninput="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(slot.New().OnFocus("test").Render())
	want := `<slot onfocus="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(slot.New().OnBlur("test").Render())
	want := `<slot onblur="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(slot.New().OnSubmit("test").Render())
	want := `<slot onsubmit="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(slot.New().OnLoad("test").Render())
	want := `<slot onload="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(slot.New().OnError("test").Render())
	want := `<slot onerror="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(slot.New().SetEvent("onclick", "test-value").Render())
	want := `<slot onclick="test-value"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(slot.New().OnAbort("test").Render())
	want := `<slot onabort="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(slot.New().OnAutoComplete("test").Render())
	want := `<slot onautocomplete="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(slot.New().OnAutoCompleteError("test").Render())
	want := `<slot onautocompleteerror="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(slot.New().OnCancel("test").Render())
	want := `<slot oncancel="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(slot.New().OnCanPlay("test").Render())
	want := `<slot oncanplay="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(slot.New().OnCanPlayThrough("test").Render())
	want := `<slot oncanplaythrough="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(slot.New().OnClose("test").Render())
	want := `<slot onclose="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(slot.New().OnContextMenu("test").Render())
	want := `<slot oncontextmenu="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(slot.New().OnCueChange("test").Render())
	want := `<slot oncuechange="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(slot.New().OnDblClick("test").Render())
	want := `<slot ondblclick="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(slot.New().OnDrag("test").Render())
	want := `<slot ondrag="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(slot.New().OnDragEnd("test").Render())
	want := `<slot ondragend="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(slot.New().OnDragEnter("test").Render())
	want := `<slot ondragenter="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(slot.New().OnDragLeave("test").Render())
	want := `<slot ondragleave="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(slot.New().OnDragOver("test").Render())
	want := `<slot ondragover="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(slot.New().OnDragStart("test").Render())
	want := `<slot ondragstart="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(slot.New().OnDrop("test").Render())
	want := `<slot ondrop="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(slot.New().OnDurationChange("test").Render())
	want := `<slot ondurationchange="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(slot.New().OnEmptied("test").Render())
	want := `<slot onemptied="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(slot.New().OnEnded("test").Render())
	want := `<slot onended="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(slot.New().OnInvalid("test").Render())
	want := `<slot oninvalid="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(slot.New().OnKeyDown("test").Render())
	want := `<slot onkeydown="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(slot.New().OnKeyPress("test").Render())
	want := `<slot onkeypress="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(slot.New().OnKeyUp("test").Render())
	want := `<slot onkeyup="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(slot.New().OnLoadedData("test").Render())
	want := `<slot onloadeddata="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(slot.New().OnLoadedMetadata("test").Render())
	want := `<slot onloadedmetadata="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(slot.New().OnLoadStart("test").Render())
	want := `<slot onloadstart="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(slot.New().OnMouseDown("test").Render())
	want := `<slot onmousedown="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(slot.New().OnMouseEnter("test").Render())
	want := `<slot onmouseenter="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(slot.New().OnMouseLeave("test").Render())
	want := `<slot onmouseleave="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(slot.New().OnMouseMove("test").Render())
	want := `<slot onmousemove="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(slot.New().OnMouseOut("test").Render())
	want := `<slot onmouseout="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(slot.New().OnMouseOver("test").Render())
	want := `<slot onmouseover="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(slot.New().OnMouseUp("test").Render())
	want := `<slot onmouseup="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(slot.New().OnMouseWheel("test").Render())
	want := `<slot onmousewheel="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(slot.New().OnPause("test").Render())
	want := `<slot onpause="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(slot.New().OnPlay("test").Render())
	want := `<slot onplay="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(slot.New().OnPlaying("test").Render())
	want := `<slot onplaying="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(slot.New().OnProgress("test").Render())
	want := `<slot onprogress="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(slot.New().OnRateChange("test").Render())
	want := `<slot onratechange="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(slot.New().OnReset("test").Render())
	want := `<slot onreset="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(slot.New().OnResize("test").Render())
	want := `<slot onresize="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(slot.New().OnScroll("test").Render())
	want := `<slot onscroll="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(slot.New().OnSeeked("test").Render())
	want := `<slot onseeked="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(slot.New().OnSeeking("test").Render())
	want := `<slot onseeking="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(slot.New().OnSelect("test").Render())
	want := `<slot onselect="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(slot.New().OnShow("test").Render())
	want := `<slot onshow="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(slot.New().OnSort("test").Render())
	want := `<slot onsort="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(slot.New().OnStalled("test").Render())
	want := `<slot onstalled="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(slot.New().OnSuspend("test").Render())
	want := `<slot onsuspend="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(slot.New().OnTimeUpdate("test").Render())
	want := `<slot ontimeupdate="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(slot.New().OnToggle("test").Render())
	want := `<slot ontoggle="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(slot.New().OnVolumeChange("test").Render())
	want := `<slot onvolumechange="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(slot.New().OnWaiting("test").Render())
	want := `<slot onwaiting="test"></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(slot.New(slot.New(), slot.New()).Render())
	want := `<slot><slot></slot><slot></slot></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := slot.New().Add(slot.New(), slot.New())

	// Test rendered output
	got := string(element.Render())
	want := `<slot><slot></slot><slot></slot></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := slot.New(slot.New(), slot.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(slot.New())

	// Test rendered output
	got := string(element.Render())
	want := `<slot><slot></slot></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(slot.New().Text("hello").Render())
	want := `<slot>hello</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(slot.New().Textf("hello %s", "world").Render())
	want := `<slot>hello world</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(slot.New().Static("static content").Render())
	want := `<slot>static content</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(slot.New().RawText("<em>bold</em>").Render())
	want := `<slot><em>bold</em></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(slot.New().RawTextf("<%s>test</%s>", "span", "span").Render())
	want := `<slot><span>test</span></slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(slot.New().Class("foo").Text("content").ID("bar").Render())
	want := `<slot class="foo" id="bar">content</slot>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

