// Code generated by fluent generator. DO NOT EDIT.

package primary_test

import (
	"bytes"
	"testing"

	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/hidden"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/primary"
)

func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(primary.New().RenderBytes())
	want := `<main></main>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(primary.New(primary.New()).RenderBytes())
	want = `<main><main></main></main>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(primary.Text("Main content area").RenderBytes())
	want := `<main>Main content area</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(primary.Static("Welcome").RenderBytes())
	want := `<main>Welcome</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(primary.RawText("<h1>Title</h1><p>Content</p>").RenderBytes())
	want := `<main><h1>Title</h1><p>Content</p></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	name := "Mary"
	got := string(primary.Textf("Welcome, %s", name).RenderBytes())
	want := `<main>Welcome, Mary</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	title := "Dashboard"
	got := string(primary.RawTextf("<h1>%s</h1>", title).RenderBytes())
	want := `<main><h1>Dashboard</h1></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(primary.New().Class("test").RenderBytes())
	want := `<main class="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(primary.New().Class("one").Class("two").Class("three").RenderBytes())
	want := `<main class="one two three"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(primary.New().ID("test").RenderBytes())
	want := `<main id="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(primary.New().Style("test").RenderBytes())
	want := `<main style="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(primary.New().Style("one").Style("two").Style("three").RenderBytes())
	want := `<main style="one; two; three"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(primary.New().Title("test").RenderBytes())
	want := `<main title="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(primary.New().Hidden(hidden.True).RenderBytes())
	want := `<main hidden="true"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenCustom(t *testing.T) {
	got := string(primary.New().Hidden(hidden.Custom("custom-value")).RenderBytes())
	want := `<main hidden="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(primary.New().TabIndex(42).RenderBytes())
	want := `<main tabindex="42"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(primary.New().Role("test").RenderBytes())
	want := `<main role="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(primary.New().Lang("test").RenderBytes())
	want := `<main lang="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(primary.New().AccessKey("test").RenderBytes())
	want := `<main accesskey="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(primary.New().AccessKey("one").AccessKey("two").AccessKey("three").RenderBytes())
	want := `<main accesskey="one two three"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(primary.New().Anchor("test").RenderBytes())
	want := `<main anchor="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(primary.New().AriaLabel("test").RenderBytes())
	want := `<main aria-label="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(primary.New().SetAria("label", "test-value").RenderBytes())
	want := `<main aria-label="test-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(primary.New().AutoCapitalize(autocapitalize.Off).RenderBytes())
	want := `<main autocapitalize="off"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeCustom(t *testing.T) {
	got := string(primary.New().AutoCapitalize(autocapitalize.Custom("custom-value")).RenderBytes())
	want := `<main autocapitalize="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(primary.New().AutoCorrect(autocorrect.On).RenderBytes())
	want := `<main autocorrect="on"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectCustom(t *testing.T) {
	got := string(primary.New().AutoCorrect(autocorrect.Custom("custom-value")).RenderBytes())
	want := `<main autocorrect="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(primary.New().AutoFocus().RenderBytes())
	want := `<main autofocus></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusFalse(t *testing.T) {
	got := string(primary.New().AutoFocus().AutoFocus(false).RenderBytes())
	want := `<main></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(primary.New().ContentEditable(contenteditable.True).RenderBytes())
	want := `<main contenteditable="true"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableCustom(t *testing.T) {
	got := string(primary.New().ContentEditable(contenteditable.Custom("custom-value")).RenderBytes())
	want := `<main contenteditable="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(primary.New().SetData("user-id", "test-value").RenderBytes())
	want := `<main data-user-id="test-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(primary.New().Dir(dir.LeftToRight).RenderBytes())
	want := `<main dir="ltr"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirCustom(t *testing.T) {
	got := string(primary.New().Dir(dir.Custom("custom-value")).RenderBytes())
	want := `<main dir="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(primary.New().Draggable(true).RenderBytes())
	want := `<main draggable="true"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(primary.New().EnterKeyHint(enterkeyhint.Enter).RenderBytes())
	want := `<main enterkeyhint="enter"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintCustom(t *testing.T) {
	got := string(primary.New().EnterKeyHint(enterkeyhint.Custom("custom-value")).RenderBytes())
	want := `<main enterkeyhint="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(primary.New().ExportParts("test").RenderBytes())
	want := `<main exportparts="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(primary.New().Inert().RenderBytes())
	want := `<main inert></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertFalse(t *testing.T) {
	got := string(primary.New().Inert().Inert(false).RenderBytes())
	want := `<main></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(primary.New().InputMode(inputmode.None).RenderBytes())
	want := `<main inputmode="none"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeCustom(t *testing.T) {
	got := string(primary.New().InputMode(inputmode.Custom("custom-value")).RenderBytes())
	want := `<main inputmode="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(primary.New().Is("test").RenderBytes())
	want := `<main is="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIDAttr(t *testing.T) {
	got := string(primary.New().ItemID("test").RenderBytes())
	want := `<main itemid="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(primary.New().ItemProp("test").RenderBytes())
	want := `<main itemprop="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(primary.New().ItemRef("test").RenderBytes())
	want := `<main itemref="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(primary.New().ItemScope().RenderBytes())
	want := `<main itemscope></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeFalse(t *testing.T) {
	got := string(primary.New().ItemScope().ItemScope(false).RenderBytes())
	want := `<main></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(primary.New().ItemType("test").RenderBytes())
	want := `<main itemtype="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(primary.New().Nonce("test").RenderBytes())
	want := `<main nonce="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(primary.New().Part("test").RenderBytes())
	want := `<main part="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(primary.New().Part("one").Part("two").Part("three").RenderBytes())
	want := `<main part="one two three"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(primary.New().Popover(popover.Auto).RenderBytes())
	want := `<main popover="auto"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverCustom(t *testing.T) {
	got := string(primary.New().Popover(popover.Custom("custom-value")).RenderBytes())
	want := `<main popover="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(primary.New().Slot("test").RenderBytes())
	want := `<main slot="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(primary.New().SpellCheck(spellcheck.True).RenderBytes())
	want := `<main spellcheck="true"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckCustom(t *testing.T) {
	got := string(primary.New().SpellCheck(spellcheck.Custom("custom-value")).RenderBytes())
	want := `<main spellcheck="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(primary.New().Translate(translate.Yes).RenderBytes())
	want := `<main translate="yes"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateCustom(t *testing.T) {
	got := string(primary.New().Translate(translate.Custom("custom-value")).RenderBytes())
	want := `<main translate="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(primary.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).RenderBytes())
	want := `<main virtualkeyboardpolicy="auto"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyCustom(t *testing.T) {
	got := string(primary.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Custom("custom-value")).RenderBytes())
	want := `<main virtualkeyboardpolicy="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(primary.New().WritingSuggestions(writingsuggestions.True).RenderBytes())
	want := `<main writingsuggestions="true"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsCustom(t *testing.T) {
	got := string(primary.New().WritingSuggestions(writingsuggestions.Custom("custom-value")).RenderBytes())
	want := `<main writingsuggestions="custom-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(primary.New().OnClick("test").RenderBytes())
	want := `<main onclick="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(primary.New().OnChange("test").RenderBytes())
	want := `<main onchange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(primary.New().OnInput("test").RenderBytes())
	want := `<main oninput="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(primary.New().OnFocus("test").RenderBytes())
	want := `<main onfocus="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(primary.New().OnBlur("test").RenderBytes())
	want := `<main onblur="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(primary.New().OnSubmit("test").RenderBytes())
	want := `<main onsubmit="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(primary.New().OnLoad("test").RenderBytes())
	want := `<main onload="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(primary.New().OnError("test").RenderBytes())
	want := `<main onerror="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(primary.New().SetEvent("onclick", "test-value").RenderBytes())
	want := `<main onclick="test-value"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(primary.New().OnAbort("test").RenderBytes())
	want := `<main onabort="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(primary.New().OnAutoComplete("test").RenderBytes())
	want := `<main onautocomplete="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(primary.New().OnAutoCompleteError("test").RenderBytes())
	want := `<main onautocompleteerror="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(primary.New().OnCancel("test").RenderBytes())
	want := `<main oncancel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(primary.New().OnCanPlay("test").RenderBytes())
	want := `<main oncanplay="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(primary.New().OnCanPlayThrough("test").RenderBytes())
	want := `<main oncanplaythrough="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(primary.New().OnClose("test").RenderBytes())
	want := `<main onclose="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(primary.New().OnContextMenu("test").RenderBytes())
	want := `<main oncontextmenu="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(primary.New().OnCueChange("test").RenderBytes())
	want := `<main oncuechange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(primary.New().OnDblClick("test").RenderBytes())
	want := `<main ondblclick="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(primary.New().OnDrag("test").RenderBytes())
	want := `<main ondrag="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(primary.New().OnDragEnd("test").RenderBytes())
	want := `<main ondragend="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(primary.New().OnDragEnter("test").RenderBytes())
	want := `<main ondragenter="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(primary.New().OnDragLeave("test").RenderBytes())
	want := `<main ondragleave="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(primary.New().OnDragOver("test").RenderBytes())
	want := `<main ondragover="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(primary.New().OnDragStart("test").RenderBytes())
	want := `<main ondragstart="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(primary.New().OnDrop("test").RenderBytes())
	want := `<main ondrop="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(primary.New().OnDurationChange("test").RenderBytes())
	want := `<main ondurationchange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(primary.New().OnEmptied("test").RenderBytes())
	want := `<main onemptied="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(primary.New().OnEnded("test").RenderBytes())
	want := `<main onended="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(primary.New().OnInvalid("test").RenderBytes())
	want := `<main oninvalid="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(primary.New().OnKeyDown("test").RenderBytes())
	want := `<main onkeydown="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(primary.New().OnKeyPress("test").RenderBytes())
	want := `<main onkeypress="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(primary.New().OnKeyUp("test").RenderBytes())
	want := `<main onkeyup="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(primary.New().OnLoadedData("test").RenderBytes())
	want := `<main onloadeddata="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(primary.New().OnLoadedMetadata("test").RenderBytes())
	want := `<main onloadedmetadata="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(primary.New().OnLoadStart("test").RenderBytes())
	want := `<main onloadstart="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(primary.New().OnMouseDown("test").RenderBytes())
	want := `<main onmousedown="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(primary.New().OnMouseEnter("test").RenderBytes())
	want := `<main onmouseenter="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(primary.New().OnMouseLeave("test").RenderBytes())
	want := `<main onmouseleave="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(primary.New().OnMouseMove("test").RenderBytes())
	want := `<main onmousemove="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(primary.New().OnMouseOut("test").RenderBytes())
	want := `<main onmouseout="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(primary.New().OnMouseOver("test").RenderBytes())
	want := `<main onmouseover="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(primary.New().OnMouseUp("test").RenderBytes())
	want := `<main onmouseup="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(primary.New().OnMouseWheel("test").RenderBytes())
	want := `<main onmousewheel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(primary.New().OnPause("test").RenderBytes())
	want := `<main onpause="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(primary.New().OnPlay("test").RenderBytes())
	want := `<main onplay="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(primary.New().OnPlaying("test").RenderBytes())
	want := `<main onplaying="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(primary.New().OnProgress("test").RenderBytes())
	want := `<main onprogress="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(primary.New().OnRateChange("test").RenderBytes())
	want := `<main onratechange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(primary.New().OnReset("test").RenderBytes())
	want := `<main onreset="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(primary.New().OnResize("test").RenderBytes())
	want := `<main onresize="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(primary.New().OnScroll("test").RenderBytes())
	want := `<main onscroll="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(primary.New().OnSeeked("test").RenderBytes())
	want := `<main onseeked="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(primary.New().OnSeeking("test").RenderBytes())
	want := `<main onseeking="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(primary.New().OnSelect("test").RenderBytes())
	want := `<main onselect="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(primary.New().OnShow("test").RenderBytes())
	want := `<main onshow="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(primary.New().OnSort("test").RenderBytes())
	want := `<main onsort="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(primary.New().OnStalled("test").RenderBytes())
	want := `<main onstalled="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(primary.New().OnSuspend("test").RenderBytes())
	want := `<main onsuspend="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(primary.New().OnTimeUpdate("test").RenderBytes())
	want := `<main ontimeupdate="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(primary.New().OnToggle("test").RenderBytes())
	want := `<main ontoggle="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(primary.New().OnVolumeChange("test").RenderBytes())
	want := `<main onvolumechange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(primary.New().OnWaiting("test").RenderBytes())
	want := `<main onwaiting="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAuxClickAttr(t *testing.T) {
	got := string(primary.New().OnAuxClick("test").RenderBytes())
	want := `<main onauxclick="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWheelAttr(t *testing.T) {
	got := string(primary.New().OnWheel("test").RenderBytes())
	want := `<main onwheel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCopyAttr(t *testing.T) {
	got := string(primary.New().OnCopy("test").RenderBytes())
	want := `<main oncopy="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCutAttr(t *testing.T) {
	got := string(primary.New().OnCut("test").RenderBytes())
	want := `<main oncut="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPasteAttr(t *testing.T) {
	got := string(primary.New().OnPaste("test").RenderBytes())
	want := `<main onpaste="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollEndAttr(t *testing.T) {
	got := string(primary.New().OnScrollEnd("test").RenderBytes())
	want := `<main onscrollend="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFormDataAttr(t *testing.T) {
	got := string(primary.New().OnFormData("test").RenderBytes())
	want := `<main onformdata="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationCancelAttr(t *testing.T) {
	got := string(primary.New().OnAnimationCancel("test").RenderBytes())
	want := `<main onanimationcancel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationEndAttr(t *testing.T) {
	got := string(primary.New().OnAnimationEnd("test").RenderBytes())
	want := `<main onanimationend="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationIterationAttr(t *testing.T) {
	got := string(primary.New().OnAnimationIteration("test").RenderBytes())
	want := `<main onanimationiteration="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationStartAttr(t *testing.T) {
	got := string(primary.New().OnAnimationStart("test").RenderBytes())
	want := `<main onanimationstart="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionCancelAttr(t *testing.T) {
	got := string(primary.New().OnTransitionCancel("test").RenderBytes())
	want := `<main ontransitioncancel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionEndAttr(t *testing.T) {
	got := string(primary.New().OnTransitionEnd("test").RenderBytes())
	want := `<main ontransitionend="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionRunAttr(t *testing.T) {
	got := string(primary.New().OnTransitionRun("test").RenderBytes())
	want := `<main ontransitionrun="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionStartAttr(t *testing.T) {
	got := string(primary.New().OnTransitionStart("test").RenderBytes())
	want := `<main ontransitionstart="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeToggleAttr(t *testing.T) {
	got := string(primary.New().OnBeforeToggle("test").RenderBytes())
	want := `<main onbeforetoggle="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeInputAttr(t *testing.T) {
	got := string(primary.New().OnBeforeInput("test").RenderBytes())
	want := `<main onbeforeinput="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeMatchAttr(t *testing.T) {
	got := string(primary.New().OnBeforeMatch("test").RenderBytes())
	want := `<main onbeforematch="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCommandAttr(t *testing.T) {
	got := string(primary.New().OnCommand("test").RenderBytes())
	want := `<main oncommand="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextLostAttr(t *testing.T) {
	got := string(primary.New().OnContextLost("test").RenderBytes())
	want := `<main oncontextlost="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextRestoredAttr(t *testing.T) {
	got := string(primary.New().OnContextRestored("test").RenderBytes())
	want := `<main oncontextrestored="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSecurityPolicyViolationAttr(t *testing.T) {
	got := string(primary.New().OnSecurityPolicyViolation("test").RenderBytes())
	want := `<main onsecuritypolicyviolation="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSlotChangeAttr(t *testing.T) {
	got := string(primary.New().OnSlotChange("test").RenderBytes())
	want := `<main onslotchange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerDownAttr(t *testing.T) {
	got := string(primary.New().OnPointerDown("test").RenderBytes())
	want := `<main onpointerdown="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerUpAttr(t *testing.T) {
	got := string(primary.New().OnPointerUp("test").RenderBytes())
	want := `<main onpointerup="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerMoveAttr(t *testing.T) {
	got := string(primary.New().OnPointerMove("test").RenderBytes())
	want := `<main onpointermove="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerEnterAttr(t *testing.T) {
	got := string(primary.New().OnPointerEnter("test").RenderBytes())
	want := `<main onpointerenter="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerLeaveAttr(t *testing.T) {
	got := string(primary.New().OnPointerLeave("test").RenderBytes())
	want := `<main onpointerleave="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOverAttr(t *testing.T) {
	got := string(primary.New().OnPointerOver("test").RenderBytes())
	want := `<main onpointerover="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOutAttr(t *testing.T) {
	got := string(primary.New().OnPointerOut("test").RenderBytes())
	want := `<main onpointerout="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerCancelAttr(t *testing.T) {
	got := string(primary.New().OnPointerCancel("test").RenderBytes())
	want := `<main onpointercancel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnGotPointerCaptureAttr(t *testing.T) {
	got := string(primary.New().OnGotPointerCapture("test").RenderBytes())
	want := `<main ongotpointercapture="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLostPointerCaptureAttr(t *testing.T) {
	got := string(primary.New().OnLostPointerCapture("test").RenderBytes())
	want := `<main onlostpointercapture="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchStartAttr(t *testing.T) {
	got := string(primary.New().OnTouchStart("test").RenderBytes())
	want := `<main ontouchstart="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchEndAttr(t *testing.T) {
	got := string(primary.New().OnTouchEnd("test").RenderBytes())
	want := `<main ontouchend="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchMoveAttr(t *testing.T) {
	got := string(primary.New().OnTouchMove("test").RenderBytes())
	want := `<main ontouchmove="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchCancelAttr(t *testing.T) {
	got := string(primary.New().OnTouchCancel("test").RenderBytes())
	want := `<main ontouchcancel="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectStartAttr(t *testing.T) {
	got := string(primary.New().OnSelectStart("test").RenderBytes())
	want := `<main onselectstart="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectionChangeAttr(t *testing.T) {
	got := string(primary.New().OnSelectionChange("test").RenderBytes())
	want := `<main onselectionchange="test"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(primary.New(primary.New(), primary.New()).RenderBytes())
	want := `<main><main></main><main></main></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := primary.New().Add(primary.New(), primary.New())

	// Test rendered output
	got := string(element.RenderBytes())
	want := `<main><main></main><main></main></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := primary.New(primary.New(), primary.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(primary.New())

	// Test rendered output
	got := string(element.RenderBytes())
	want := `<main><main></main></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(primary.New().Text("hello").RenderBytes())
	want := `<main>hello</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(primary.New().Textf("hello %s", "world").RenderBytes())
	want := `<main>hello world</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(primary.New().Static("static content").RenderBytes())
	want := `<main>static content</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(primary.New().RawText("<em>bold</em>").RenderBytes())
	want := `<main><em>bold</em></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(primary.New().RawTextf("<%s>test</%s>", "span", "span").RenderBytes())
	want := `<main><span>test</span></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(primary.New().Class("foo").Text("content").ID("bar").RenderBytes())
	want := `<main class="foo" id="bar">content</main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicKey(t *testing.T) {
	got := string(primary.New().Dynamic("mykey").RenderBytes())
	want := `<main data-fluent-key="mykey"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestMemoiseKey(t *testing.T) {
	el := primary.New()
	if el.MemoiseKey() != nil {
		t.Error("new element should have no memoise version")
	}
	el.Memoise(7)
	if el.MemoiseKey() != 7 {
		t.Errorf("MemoiseKey() = %v, want 7", el.MemoiseKey())
	}
}

func TestNotDynamic(t *testing.T) {
	el := primary.New()
	if el.IsDynamic() {
		t.Error("new element should not be dynamic")
	}
	if el.DynamicKey() != "" {
		t.Errorf("DynamicKey() should be empty, got %q", el.DynamicKey())
	}
}

func TestRenderMethodsMatch(t *testing.T) {
	el := primary.New()
	el.SetAttribute("data-check", "render")
	want := string(el.RenderBytes())

	var buf bytes.Buffer
	el.Render(&buf)
	if buf.String() != want {
		t.Errorf("Render: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	n, err := el.WriteTo(&buf)
	if err != nil {
		t.Fatalf("WriteTo: %v", err)
	}
	if buf.String() != want {
		t.Errorf("WriteTo: got %q, want %q", buf.String(), want)
	}
	if n != int64(len(want)) {
		t.Errorf("WriteTo returned %d bytes, want %d", n, len(want))
	}

	buf.Reset()
	el.RenderBuilder(&buf)
	if buf.String() != want {
		t.Errorf("RenderBuilder: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	el.RenderOpen(&buf)
	el.RenderClose(&buf)
	if buf.String() != want {
		t.Errorf("RenderOpen+RenderClose: got %q, want %q", buf.String(), want)
	}
}

func TestSetAttributeEscapes(t *testing.T) {
	el := primary.New()
	el.SetAttribute("data-sample", "\"><script>")
	got := string(el.RenderBytes())
	want := `<main data-sample="&#34;&gt;&lt;script&gt;"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAttributeRaw(t *testing.T) {
	el := primary.New()
	// A pre-escaped entity must render verbatim; SetAttribute would double-escape it.
	el.SetAttributeRaw("data-sample", "a&amp;b")
	got := string(el.RenderBytes())
	want := `<main data-sample="a&amp;b"></main>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextNoBreakout(t *testing.T) {
	got := primary.Text("\"><script>").RenderBytes()
	if bytes.Contains(got, []byte("\"><script>")) {
		t.Errorf("hostile value reached the output unescaped: %s", got)
	}
}

func TestTextfNoBreakout(t *testing.T) {
	got := primary.Textf("\"><script>").RenderBytes()
	if bytes.Contains(got, []byte("\"><script>")) {
		t.Errorf("hostile value reached the output unescaped: %s", got)
	}
}
