// Code generated by fluent generator. DO NOT EDIT.

package mark_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/mark"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
)


func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(mark.New().Render())
	want := `<mark></mark>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(mark.New(mark.New()).Render())
	want = `<mark><mark></mark></mark>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(mark.Text("<strong>important</strong> result").Render())
	want := `<mark>&lt;strong&gt;important&lt;/strong&gt; result</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(mark.Static("Hello World").Render())
	want := `<mark>Hello World</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(mark.RawText("<strong>important</strong> result").Render())
	want := `<mark><strong>important</strong> result</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	got := string(mark.Textf("Hello %s", "World").Render())
	want := `<mark>Hello World</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	got := string(mark.RawTextf("Hello <em>%s</em>", "World").Render())
	want := `<mark>Hello <em>World</em></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(mark.New().Class("test").Render())
	want := `<mark class="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(mark.New().Class("one").Class("two").Class("three").Render())
	want := `<mark class="one two three"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(mark.New().ID("test").Render())
	want := `<mark id="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(mark.New().Style("test").Render())
	want := `<mark style="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(mark.New().Style("one").Style("two").Style("three").Render())
	want := `<mark style="one; two; three"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(mark.New().Title("test").Render())
	want := `<mark title="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(mark.New().Hidden().Render())
	want := `<mark hidden="hidden"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(mark.New().TabIndex(42).Render())
	want := `<mark tabindex="42"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(mark.New().Role("test").Render())
	want := `<mark role="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(mark.New().Lang("test").Render())
	want := `<mark lang="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(mark.New().AccessKey("test").Render())
	want := `<mark accesskey="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(mark.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<mark accesskey="one two three"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(mark.New().Anchor("test").Render())
	want := `<mark anchor="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(mark.New().AriaLabel("test").Render())
	want := `<mark arialabel="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(mark.New().SetAria("label", "test-value").Render())
	want := `<mark aria-label="test-value"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(mark.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<mark autocapitalize="off"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(mark.New().AutoCorrect(autocorrect.On).Render())
	want := `<mark autocorrect="on"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(mark.New().AutoFocus().Render())
	want := `<mark autofocus="autofocus"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(mark.New().ContentEditable(contenteditable.True).Render())
	want := `<mark contenteditable="true"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(mark.New().SetData("user-id", "test-value").Render())
	want := `<mark data-user-id="test-value"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(mark.New().Dir(dir.LeftToRight).Render())
	want := `<mark dir="ltr"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(mark.New().Draggable().Render())
	want := `<mark draggable="draggable"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(mark.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<mark enterkeyhint="enter"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(mark.New().ExportParts("test").Render())
	want := `<mark exportparts="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(mark.New().Inert().Render())
	want := `<mark inert="inert"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(mark.New().InputMode(inputmode.None).Render())
	want := `<mark inputmode="none"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(mark.New().Is("test").Render())
	want := `<mark is="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(mark.New().ItemId("test").Render())
	want := `<mark itemid="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(mark.New().ItemProp("test").Render())
	want := `<mark itemprop="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(mark.New().ItemRef("test").Render())
	want := `<mark itemref="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(mark.New().ItemScope().Render())
	want := `<mark itemscope="itemscope"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(mark.New().ItemType("test").Render())
	want := `<mark itemtype="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(mark.New().Nonce("test").Render())
	want := `<mark nonce="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(mark.New().Part("test").Render())
	want := `<mark part="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(mark.New().Part("one").Part("two").Part("three").Render())
	want := `<mark part="one two three"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(mark.New().Popover(popover.Auto).Render())
	want := `<mark popover="auto"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(mark.New().Slot("test").Render())
	want := `<mark slot="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(mark.New().SpellCheck(spellcheck.True).Render())
	want := `<mark spellcheck="true"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(mark.New().Translate(translate.Yes).Render())
	want := `<mark translate="yes"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(mark.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<mark virtualkeyboardpolicy="auto"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(mark.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<mark writingsuggestions="true"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(mark.New().OnClick("test").Render())
	want := `<mark onclick="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(mark.New().OnChange("test").Render())
	want := `<mark onchange="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(mark.New().OnInput("test").Render())
	want := `<mark oninput="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(mark.New().OnFocus("test").Render())
	want := `<mark onfocus="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(mark.New().OnBlur("test").Render())
	want := `<mark onblur="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(mark.New().OnSubmit("test").Render())
	want := `<mark onsubmit="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(mark.New().OnLoad("test").Render())
	want := `<mark onload="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(mark.New().OnError("test").Render())
	want := `<mark onerror="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(mark.New().SetEvent("onclick", "test-value").Render())
	want := `<mark onclick="test-value"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(mark.New().OnAbort("test").Render())
	want := `<mark onabort="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(mark.New().OnAutoComplete("test").Render())
	want := `<mark onautocomplete="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(mark.New().OnAutoCompleteError("test").Render())
	want := `<mark onautocompleteerror="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(mark.New().OnCancel("test").Render())
	want := `<mark oncancel="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(mark.New().OnCanPlay("test").Render())
	want := `<mark oncanplay="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(mark.New().OnCanPlayThrough("test").Render())
	want := `<mark oncanplaythrough="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(mark.New().OnClose("test").Render())
	want := `<mark onclose="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(mark.New().OnContextMenu("test").Render())
	want := `<mark oncontextmenu="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(mark.New().OnCueChange("test").Render())
	want := `<mark oncuechange="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(mark.New().OnDblClick("test").Render())
	want := `<mark ondblclick="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(mark.New().OnDrag("test").Render())
	want := `<mark ondrag="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(mark.New().OnDragEnd("test").Render())
	want := `<mark ondragend="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(mark.New().OnDragEnter("test").Render())
	want := `<mark ondragenter="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(mark.New().OnDragLeave("test").Render())
	want := `<mark ondragleave="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(mark.New().OnDragOver("test").Render())
	want := `<mark ondragover="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(mark.New().OnDragStart("test").Render())
	want := `<mark ondragstart="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(mark.New().OnDrop("test").Render())
	want := `<mark ondrop="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(mark.New().OnDurationChange("test").Render())
	want := `<mark ondurationchange="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(mark.New().OnEmptied("test").Render())
	want := `<mark onemptied="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(mark.New().OnEnded("test").Render())
	want := `<mark onended="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(mark.New().OnInvalid("test").Render())
	want := `<mark oninvalid="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(mark.New().OnKeyDown("test").Render())
	want := `<mark onkeydown="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(mark.New().OnKeyPress("test").Render())
	want := `<mark onkeypress="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(mark.New().OnKeyUp("test").Render())
	want := `<mark onkeyup="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(mark.New().OnLoadedData("test").Render())
	want := `<mark onloadeddata="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(mark.New().OnLoadedMetadata("test").Render())
	want := `<mark onloadedmetadata="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(mark.New().OnLoadStart("test").Render())
	want := `<mark onloadstart="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(mark.New().OnMouseDown("test").Render())
	want := `<mark onmousedown="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(mark.New().OnMouseEnter("test").Render())
	want := `<mark onmouseenter="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(mark.New().OnMouseLeave("test").Render())
	want := `<mark onmouseleave="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(mark.New().OnMouseMove("test").Render())
	want := `<mark onmousemove="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(mark.New().OnMouseOut("test").Render())
	want := `<mark onmouseout="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(mark.New().OnMouseOver("test").Render())
	want := `<mark onmouseover="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(mark.New().OnMouseUp("test").Render())
	want := `<mark onmouseup="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(mark.New().OnMouseWheel("test").Render())
	want := `<mark onmousewheel="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(mark.New().OnPause("test").Render())
	want := `<mark onpause="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(mark.New().OnPlay("test").Render())
	want := `<mark onplay="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(mark.New().OnPlaying("test").Render())
	want := `<mark onplaying="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(mark.New().OnProgress("test").Render())
	want := `<mark onprogress="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(mark.New().OnRateChange("test").Render())
	want := `<mark onratechange="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(mark.New().OnReset("test").Render())
	want := `<mark onreset="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(mark.New().OnResize("test").Render())
	want := `<mark onresize="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(mark.New().OnScroll("test").Render())
	want := `<mark onscroll="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(mark.New().OnSeeked("test").Render())
	want := `<mark onseeked="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(mark.New().OnSeeking("test").Render())
	want := `<mark onseeking="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(mark.New().OnSelect("test").Render())
	want := `<mark onselect="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(mark.New().OnShow("test").Render())
	want := `<mark onshow="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(mark.New().OnSort("test").Render())
	want := `<mark onsort="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(mark.New().OnStalled("test").Render())
	want := `<mark onstalled="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(mark.New().OnSuspend("test").Render())
	want := `<mark onsuspend="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(mark.New().OnTimeUpdate("test").Render())
	want := `<mark ontimeupdate="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(mark.New().OnToggle("test").Render())
	want := `<mark ontoggle="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(mark.New().OnVolumeChange("test").Render())
	want := `<mark onvolumechange="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(mark.New().OnWaiting("test").Render())
	want := `<mark onwaiting="test"></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(mark.New(mark.New(), mark.New()).Render())
	want := `<mark><mark></mark><mark></mark></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := mark.New().Add(mark.New(), mark.New())

	// Test rendered output
	got := string(element.Render())
	want := `<mark><mark></mark><mark></mark></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := mark.New(mark.New(), mark.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(mark.New())

	// Test rendered output
	got := string(element.Render())
	want := `<mark><mark></mark></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(mark.New().Text("hello").Render())
	want := `<mark>hello</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(mark.New().Textf("hello %s", "world").Render())
	want := `<mark>hello world</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(mark.New().Static("static content").Render())
	want := `<mark>static content</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(mark.New().RawText("<em>bold</em>").Render())
	want := `<mark><em>bold</em></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(mark.New().RawTextf("<%s>test</%s>", "span", "span").Render())
	want := `<mark><span>test</span></mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(mark.New().Class("foo").Text("content").ID("bar").Render())
	want := `<mark class="foo" id="bar">content</mark>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

