// Code generated by fluent generator. DO NOT EDIT.

package button_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enctype"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/hidden"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/method"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/popovertargetaction"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/target"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/button"
)

func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(button.New().Render())
	want := `<button></button>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(button.New(button.New()).Render())
	want = `<button><button></button></button>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(button.Text("Click Me").Render())
	want := `<button>Click Me</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(button.Static("Submit").Render())
	want := `<button>Submit</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(button.RawText("<b>Submit</b>").Render())
	want := `<button><b>Submit</b></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	title := "Dashboard"
	got := string(button.Textf("Save %s", title).Render())
	want := `<button>Save Dashboard</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	icon := "★"
	got := string(button.RawTextf("<span class=\"icon\">%s</span> Save", icon).Render())
	want := `<button><span class="icon">★</span> Save</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSubmitCtor(t *testing.T) {
	got := string(button.Submit("Send Form").Render())
	want := `<button type="submit">Send Form</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestResetCtor(t *testing.T) {
	got := string(button.Reset("Clear Form").Render())
	want := `<button type="reset">Clear Form</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestButtonCtor(t *testing.T) {
	got := string(button.Button("Click Me").Render())
	want := `<button type="button">Click Me</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestCommandAttr(t *testing.T) {
	got := string(button.New().Command("test").Render())
	want := `<button command="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestCommandforAttr(t *testing.T) {
	got := string(button.New().Commandfor("test").Render())
	want := `<button commandfor="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDisabledAttr(t *testing.T) {
	got := string(button.New().Disabled().Render())
	want := `<button disabled></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFormAttr(t *testing.T) {
	got := string(button.New().Form("test").Render())
	want := `<button form="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFormactionAttr(t *testing.T) {
	got := string(button.New().Formaction("test").Render())
	want := `<button formaction="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFormenctypeAttr(t *testing.T) {
	got := string(button.New().Formenctype(enctype.UrlEncoded).Render())
	want := `<button formenctype="application/x-www-form-urlencoded"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFormmethodAttr(t *testing.T) {
	got := string(button.New().Formmethod(method.Get).Render())
	want := `<button formmethod="get"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFormnovalidateAttr(t *testing.T) {
	got := string(button.New().Formnovalidate().Render())
	want := `<button formnovalidate></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestFormtargetAttr(t *testing.T) {
	got := string(button.New().Formtarget(target.Self).Render())
	want := `<button formtarget="_self"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNameAttr(t *testing.T) {
	got := string(button.New().Name("test").Render())
	want := `<button name="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopOverTargetAttr(t *testing.T) {
	got := string(button.New().PopOverTarget("test").Render())
	want := `<button popovertarget="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopovertargetactionAttr(t *testing.T) {
	got := string(button.New().Popovertargetaction(popovertargetaction.Toggle).Render())
	want := `<button popovertargetaction="toggle"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTypeAttr(t *testing.T) {
	got := string(button.New().Type("test").Render())
	want := `<button type="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestValueAttr(t *testing.T) {
	got := string(button.New().Value("test").Render())
	want := `<button value="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(button.New().Class("test").Render())
	want := `<button class="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(button.New().Class("one").Class("two").Class("three").Render())
	want := `<button class="one two three"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(button.New().ID("test").Render())
	want := `<button id="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(button.New().Style("test").Render())
	want := `<button style="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(button.New().Style("one").Style("two").Style("three").Render())
	want := `<button style="one; two; three"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(button.New().Title("test").Render())
	want := `<button title="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(button.New().Hidden(hidden.True).Render())
	want := `<button hidden="true"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(button.New().TabIndex(42).Render())
	want := `<button tabindex="42"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(button.New().Role("test").Render())
	want := `<button role="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(button.New().Lang("test").Render())
	want := `<button lang="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(button.New().AccessKey("test").Render())
	want := `<button accesskey="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(button.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<button accesskey="one two three"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(button.New().Anchor("test").Render())
	want := `<button anchor="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(button.New().AriaLabel("test").Render())
	want := `<button aria-label="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(button.New().SetAria("label", "test-value").Render())
	want := `<button aria-label="test-value"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(button.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<button autocapitalize="off"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(button.New().AutoCorrect(autocorrect.On).Render())
	want := `<button autocorrect="on"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(button.New().AutoFocus().Render())
	want := `<button autofocus></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(button.New().ContentEditable(contenteditable.True).Render())
	want := `<button contenteditable="true"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(button.New().SetData("user-id", "test-value").Render())
	want := `<button data-user-id="test-value"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(button.New().Dir(dir.LeftToRight).Render())
	want := `<button dir="ltr"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(button.New().Draggable().Render())
	want := `<button draggable></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(button.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<button enterkeyhint="enter"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(button.New().ExportParts("test").Render())
	want := `<button exportparts="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(button.New().Inert().Render())
	want := `<button inert></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(button.New().InputMode(inputmode.None).Render())
	want := `<button inputmode="none"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(button.New().Is("test").Render())
	want := `<button is="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(button.New().ItemId("test").Render())
	want := `<button itemid="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(button.New().ItemProp("test").Render())
	want := `<button itemprop="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(button.New().ItemRef("test").Render())
	want := `<button itemref="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(button.New().ItemScope().Render())
	want := `<button itemscope></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(button.New().ItemType("test").Render())
	want := `<button itemtype="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(button.New().Nonce("test").Render())
	want := `<button nonce="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(button.New().Part("test").Render())
	want := `<button part="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(button.New().Part("one").Part("two").Part("three").Render())
	want := `<button part="one two three"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(button.New().Popover(popover.Auto).Render())
	want := `<button popover="auto"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(button.New().Slot("test").Render())
	want := `<button slot="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(button.New().SpellCheck(spellcheck.True).Render())
	want := `<button spellcheck="true"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(button.New().Translate(translate.Yes).Render())
	want := `<button translate="yes"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(button.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<button virtualkeyboardpolicy="auto"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(button.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<button writingsuggestions="true"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(button.New().OnClick("test").Render())
	want := `<button onclick="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(button.New().OnChange("test").Render())
	want := `<button onchange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(button.New().OnInput("test").Render())
	want := `<button oninput="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(button.New().OnFocus("test").Render())
	want := `<button onfocus="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(button.New().OnBlur("test").Render())
	want := `<button onblur="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(button.New().OnSubmit("test").Render())
	want := `<button onsubmit="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(button.New().OnLoad("test").Render())
	want := `<button onload="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(button.New().OnError("test").Render())
	want := `<button onerror="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(button.New().SetEvent("onclick", "test-value").Render())
	want := `<button onclick="test-value"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(button.New().OnAbort("test").Render())
	want := `<button onabort="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(button.New().OnAutoComplete("test").Render())
	want := `<button onautocomplete="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(button.New().OnAutoCompleteError("test").Render())
	want := `<button onautocompleteerror="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(button.New().OnCancel("test").Render())
	want := `<button oncancel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(button.New().OnCanPlay("test").Render())
	want := `<button oncanplay="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(button.New().OnCanPlayThrough("test").Render())
	want := `<button oncanplaythrough="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(button.New().OnClose("test").Render())
	want := `<button onclose="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(button.New().OnContextMenu("test").Render())
	want := `<button oncontextmenu="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(button.New().OnCueChange("test").Render())
	want := `<button oncuechange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(button.New().OnDblClick("test").Render())
	want := `<button ondblclick="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(button.New().OnDrag("test").Render())
	want := `<button ondrag="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(button.New().OnDragEnd("test").Render())
	want := `<button ondragend="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(button.New().OnDragEnter("test").Render())
	want := `<button ondragenter="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(button.New().OnDragLeave("test").Render())
	want := `<button ondragleave="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(button.New().OnDragOver("test").Render())
	want := `<button ondragover="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(button.New().OnDragStart("test").Render())
	want := `<button ondragstart="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(button.New().OnDrop("test").Render())
	want := `<button ondrop="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(button.New().OnDurationChange("test").Render())
	want := `<button ondurationchange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(button.New().OnEmptied("test").Render())
	want := `<button onemptied="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(button.New().OnEnded("test").Render())
	want := `<button onended="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(button.New().OnInvalid("test").Render())
	want := `<button oninvalid="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(button.New().OnKeyDown("test").Render())
	want := `<button onkeydown="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(button.New().OnKeyPress("test").Render())
	want := `<button onkeypress="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(button.New().OnKeyUp("test").Render())
	want := `<button onkeyup="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(button.New().OnLoadedData("test").Render())
	want := `<button onloadeddata="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(button.New().OnLoadedMetadata("test").Render())
	want := `<button onloadedmetadata="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(button.New().OnLoadStart("test").Render())
	want := `<button onloadstart="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(button.New().OnMouseDown("test").Render())
	want := `<button onmousedown="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(button.New().OnMouseEnter("test").Render())
	want := `<button onmouseenter="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(button.New().OnMouseLeave("test").Render())
	want := `<button onmouseleave="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(button.New().OnMouseMove("test").Render())
	want := `<button onmousemove="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(button.New().OnMouseOut("test").Render())
	want := `<button onmouseout="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(button.New().OnMouseOver("test").Render())
	want := `<button onmouseover="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(button.New().OnMouseUp("test").Render())
	want := `<button onmouseup="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(button.New().OnMouseWheel("test").Render())
	want := `<button onmousewheel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(button.New().OnPause("test").Render())
	want := `<button onpause="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(button.New().OnPlay("test").Render())
	want := `<button onplay="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(button.New().OnPlaying("test").Render())
	want := `<button onplaying="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(button.New().OnProgress("test").Render())
	want := `<button onprogress="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(button.New().OnRateChange("test").Render())
	want := `<button onratechange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(button.New().OnReset("test").Render())
	want := `<button onreset="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(button.New().OnResize("test").Render())
	want := `<button onresize="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(button.New().OnScroll("test").Render())
	want := `<button onscroll="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(button.New().OnSeeked("test").Render())
	want := `<button onseeked="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(button.New().OnSeeking("test").Render())
	want := `<button onseeking="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(button.New().OnSelect("test").Render())
	want := `<button onselect="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(button.New().OnShow("test").Render())
	want := `<button onshow="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(button.New().OnSort("test").Render())
	want := `<button onsort="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(button.New().OnStalled("test").Render())
	want := `<button onstalled="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(button.New().OnSuspend("test").Render())
	want := `<button onsuspend="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(button.New().OnTimeUpdate("test").Render())
	want := `<button ontimeupdate="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(button.New().OnToggle("test").Render())
	want := `<button ontoggle="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(button.New().OnVolumeChange("test").Render())
	want := `<button onvolumechange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(button.New().OnWaiting("test").Render())
	want := `<button onwaiting="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAuxClickAttr(t *testing.T) {
	got := string(button.New().OnAuxClick("test").Render())
	want := `<button onauxclick="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWheelAttr(t *testing.T) {
	got := string(button.New().OnWheel("test").Render())
	want := `<button onwheel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCopyAttr(t *testing.T) {
	got := string(button.New().OnCopy("test").Render())
	want := `<button oncopy="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCutAttr(t *testing.T) {
	got := string(button.New().OnCut("test").Render())
	want := `<button oncut="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPasteAttr(t *testing.T) {
	got := string(button.New().OnPaste("test").Render())
	want := `<button onpaste="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollEndAttr(t *testing.T) {
	got := string(button.New().OnScrollEnd("test").Render())
	want := `<button onscrollend="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFormDataAttr(t *testing.T) {
	got := string(button.New().OnFormData("test").Render())
	want := `<button onformdata="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationCancelAttr(t *testing.T) {
	got := string(button.New().OnAnimationCancel("test").Render())
	want := `<button onanimationcancel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationEndAttr(t *testing.T) {
	got := string(button.New().OnAnimationEnd("test").Render())
	want := `<button onanimationend="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationIterationAttr(t *testing.T) {
	got := string(button.New().OnAnimationIteration("test").Render())
	want := `<button onanimationiteration="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationStartAttr(t *testing.T) {
	got := string(button.New().OnAnimationStart("test").Render())
	want := `<button onanimationstart="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionCancelAttr(t *testing.T) {
	got := string(button.New().OnTransitionCancel("test").Render())
	want := `<button ontransitioncancel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionEndAttr(t *testing.T) {
	got := string(button.New().OnTransitionEnd("test").Render())
	want := `<button ontransitionend="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionRunAttr(t *testing.T) {
	got := string(button.New().OnTransitionRun("test").Render())
	want := `<button ontransitionrun="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionStartAttr(t *testing.T) {
	got := string(button.New().OnTransitionStart("test").Render())
	want := `<button ontransitionstart="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeToggleAttr(t *testing.T) {
	got := string(button.New().OnBeforeToggle("test").Render())
	want := `<button onbeforetoggle="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeInputAttr(t *testing.T) {
	got := string(button.New().OnBeforeInput("test").Render())
	want := `<button onbeforeinput="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeMatchAttr(t *testing.T) {
	got := string(button.New().OnBeforeMatch("test").Render())
	want := `<button onbeforematch="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCommandAttr(t *testing.T) {
	got := string(button.New().OnCommand("test").Render())
	want := `<button oncommand="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextLostAttr(t *testing.T) {
	got := string(button.New().OnContextLost("test").Render())
	want := `<button oncontextlost="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextRestoredAttr(t *testing.T) {
	got := string(button.New().OnContextRestored("test").Render())
	want := `<button oncontextrestored="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSecurityPolicyViolationAttr(t *testing.T) {
	got := string(button.New().OnSecurityPolicyViolation("test").Render())
	want := `<button onsecuritypolicyviolation="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSlotChangeAttr(t *testing.T) {
	got := string(button.New().OnSlotChange("test").Render())
	want := `<button onslotchange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerDownAttr(t *testing.T) {
	got := string(button.New().OnPointerDown("test").Render())
	want := `<button onpointerdown="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerUpAttr(t *testing.T) {
	got := string(button.New().OnPointerUp("test").Render())
	want := `<button onpointerup="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerMoveAttr(t *testing.T) {
	got := string(button.New().OnPointerMove("test").Render())
	want := `<button onpointermove="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerEnterAttr(t *testing.T) {
	got := string(button.New().OnPointerEnter("test").Render())
	want := `<button onpointerenter="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerLeaveAttr(t *testing.T) {
	got := string(button.New().OnPointerLeave("test").Render())
	want := `<button onpointerleave="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOverAttr(t *testing.T) {
	got := string(button.New().OnPointerOver("test").Render())
	want := `<button onpointerover="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOutAttr(t *testing.T) {
	got := string(button.New().OnPointerOut("test").Render())
	want := `<button onpointerout="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerCancelAttr(t *testing.T) {
	got := string(button.New().OnPointerCancel("test").Render())
	want := `<button onpointercancel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnGotPointerCaptureAttr(t *testing.T) {
	got := string(button.New().OnGotPointerCapture("test").Render())
	want := `<button ongotpointercapture="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLostPointerCaptureAttr(t *testing.T) {
	got := string(button.New().OnLostPointerCapture("test").Render())
	want := `<button onlostpointercapture="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchStartAttr(t *testing.T) {
	got := string(button.New().OnTouchStart("test").Render())
	want := `<button ontouchstart="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchEndAttr(t *testing.T) {
	got := string(button.New().OnTouchEnd("test").Render())
	want := `<button ontouchend="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchMoveAttr(t *testing.T) {
	got := string(button.New().OnTouchMove("test").Render())
	want := `<button ontouchmove="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchCancelAttr(t *testing.T) {
	got := string(button.New().OnTouchCancel("test").Render())
	want := `<button ontouchcancel="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectStartAttr(t *testing.T) {
	got := string(button.New().OnSelectStart("test").Render())
	want := `<button onselectstart="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectionChangeAttr(t *testing.T) {
	got := string(button.New().OnSelectionChange("test").Render())
	want := `<button onselectionchange="test"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(button.New(button.New(), button.New()).Render())
	want := `<button><button></button><button></button></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := button.New().Add(button.New(), button.New())

	// Test rendered output
	got := string(element.Render())
	want := `<button><button></button><button></button></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := button.New(button.New(), button.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(button.New())

	// Test rendered output
	got := string(element.Render())
	want := `<button><button></button></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(button.New().Text("hello").Render())
	want := `<button>hello</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(button.New().Textf("hello %s", "world").Render())
	want := `<button>hello world</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(button.New().Static("static content").Render())
	want := `<button>static content</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(button.New().RawText("<em>bold</em>").Render())
	want := `<button><em>bold</em></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(button.New().RawTextf("<%s>test</%s>", "span", "span").Render())
	want := `<button><span>test</span></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(button.New().Class("foo").Text("content").ID("bar").Render())
	want := `<button class="foo" id="bar">content</button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicKey(t *testing.T) {
	got := string(button.New().Dynamic("mykey").Render())
	want := `<button data-tether-key="mykey"></button>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicNoKey(t *testing.T) {
	el := button.New().Dynamic()
	if !el.IsDynamic() {
		t.Error("element should be dynamic after calling Dynamic()")
	}
	if el.DynamicKey() != "_" {
		t.Errorf("DynamicKey() should be \"_\", got %q", el.DynamicKey())
	}
	got := string(el.Render())
	want := `<button></button>`
	if got != want {
		t.Errorf("Dynamic() without key should not render data-tether-key: got %q, want %q", got, want)
	}
}

func TestNotDynamic(t *testing.T) {
	el := button.New()
	if el.IsDynamic() {
		t.Error("new element should not be dynamic")
	}
	if el.DynamicKey() != "" {
		t.Errorf("DynamicKey() should be empty, got %q", el.DynamicKey())
	}
}
