// Code generated by fluent generator. DO NOT EDIT.

package figcaption_test

import (
	"testing"

	"github.com/jpl-au/fluent/html5/figcaption"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
)


func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(figcaption.New().Render())
	want := `<figcaption></figcaption>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(figcaption.New(figcaption.New()).Render())
	want = `<figcaption><figcaption></figcaption></figcaption>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(figcaption.Text("<b>An elephant</b> at sunset").Render())
	want := `<figcaption>&lt;b&gt;An elephant&lt;/b&gt; at sunset</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(figcaption.Static("Hello World").Render())
	want := `<figcaption>Hello World</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(figcaption.RawText("<b>An elephant</b> at sunset").Render())
	want := `<figcaption><b>An elephant</b> at sunset</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	got := string(figcaption.Textf("Hello %s", "World").Render())
	want := `<figcaption>Hello World</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	got := string(figcaption.RawTextf("Hello <em>%s</em>", "World").Render())
	want := `<figcaption>Hello <em>World</em></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(figcaption.New().Class("test").Render())
	want := `<figcaption class="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(figcaption.New().Class("one").Class("two").Class("three").Render())
	want := `<figcaption class="one two three"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(figcaption.New().ID("test").Render())
	want := `<figcaption id="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(figcaption.New().Style("test").Render())
	want := `<figcaption style="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(figcaption.New().Style("one").Style("two").Style("three").Render())
	want := `<figcaption style="one; two; three"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(figcaption.New().Title("test").Render())
	want := `<figcaption title="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(figcaption.New().Hidden().Render())
	want := `<figcaption hidden="hidden"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(figcaption.New().TabIndex(42).Render())
	want := `<figcaption tabindex="42"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(figcaption.New().Role("test").Render())
	want := `<figcaption role="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(figcaption.New().Lang("test").Render())
	want := `<figcaption lang="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(figcaption.New().AccessKey("test").Render())
	want := `<figcaption accesskey="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(figcaption.New().AccessKey("one").AccessKey("two").AccessKey("three").Render())
	want := `<figcaption accesskey="one two three"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(figcaption.New().Anchor("test").Render())
	want := `<figcaption anchor="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(figcaption.New().AriaLabel("test").Render())
	want := `<figcaption arialabel="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(figcaption.New().SetAria("label", "test-value").Render())
	want := `<figcaption aria-label="test-value"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(figcaption.New().AutoCapitalize(autocapitalize.Off).Render())
	want := `<figcaption autocapitalize="off"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(figcaption.New().AutoCorrect(autocorrect.On).Render())
	want := `<figcaption autocorrect="on"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(figcaption.New().AutoFocus().Render())
	want := `<figcaption autofocus="autofocus"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(figcaption.New().ContentEditable(contenteditable.True).Render())
	want := `<figcaption contenteditable="true"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(figcaption.New().SetData("user-id", "test-value").Render())
	want := `<figcaption data-user-id="test-value"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(figcaption.New().Dir(dir.LeftToRight).Render())
	want := `<figcaption dir="ltr"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(figcaption.New().Draggable().Render())
	want := `<figcaption draggable="draggable"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(figcaption.New().EnterKeyHint(enterkeyhint.Enter).Render())
	want := `<figcaption enterkeyhint="enter"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(figcaption.New().ExportParts("test").Render())
	want := `<figcaption exportparts="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(figcaption.New().Inert().Render())
	want := `<figcaption inert="inert"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(figcaption.New().InputMode(inputmode.None).Render())
	want := `<figcaption inputmode="none"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(figcaption.New().Is("test").Render())
	want := `<figcaption is="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(figcaption.New().ItemId("test").Render())
	want := `<figcaption itemid="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(figcaption.New().ItemProp("test").Render())
	want := `<figcaption itemprop="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(figcaption.New().ItemRef("test").Render())
	want := `<figcaption itemref="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(figcaption.New().ItemScope().Render())
	want := `<figcaption itemscope="itemscope"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(figcaption.New().ItemType("test").Render())
	want := `<figcaption itemtype="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(figcaption.New().Nonce("test").Render())
	want := `<figcaption nonce="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(figcaption.New().Part("test").Render())
	want := `<figcaption part="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(figcaption.New().Part("one").Part("two").Part("three").Render())
	want := `<figcaption part="one two three"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(figcaption.New().Popover(popover.Auto).Render())
	want := `<figcaption popover="auto"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(figcaption.New().Slot("test").Render())
	want := `<figcaption slot="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(figcaption.New().SpellCheck(spellcheck.True).Render())
	want := `<figcaption spellcheck="true"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(figcaption.New().Translate(translate.Yes).Render())
	want := `<figcaption translate="yes"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(figcaption.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).Render())
	want := `<figcaption virtualkeyboardpolicy="auto"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(figcaption.New().WritingSuggestions(writingsuggestions.True).Render())
	want := `<figcaption writingsuggestions="true"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(figcaption.New().OnClick("test").Render())
	want := `<figcaption onclick="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(figcaption.New().OnChange("test").Render())
	want := `<figcaption onchange="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(figcaption.New().OnInput("test").Render())
	want := `<figcaption oninput="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(figcaption.New().OnFocus("test").Render())
	want := `<figcaption onfocus="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(figcaption.New().OnBlur("test").Render())
	want := `<figcaption onblur="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(figcaption.New().OnSubmit("test").Render())
	want := `<figcaption onsubmit="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(figcaption.New().OnLoad("test").Render())
	want := `<figcaption onload="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(figcaption.New().OnError("test").Render())
	want := `<figcaption onerror="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(figcaption.New().SetEvent("onclick", "test-value").Render())
	want := `<figcaption onclick="test-value"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(figcaption.New().OnAbort("test").Render())
	want := `<figcaption onabort="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(figcaption.New().OnAutoComplete("test").Render())
	want := `<figcaption onautocomplete="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(figcaption.New().OnAutoCompleteError("test").Render())
	want := `<figcaption onautocompleteerror="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(figcaption.New().OnCancel("test").Render())
	want := `<figcaption oncancel="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(figcaption.New().OnCanPlay("test").Render())
	want := `<figcaption oncanplay="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(figcaption.New().OnCanPlayThrough("test").Render())
	want := `<figcaption oncanplaythrough="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(figcaption.New().OnClose("test").Render())
	want := `<figcaption onclose="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(figcaption.New().OnContextMenu("test").Render())
	want := `<figcaption oncontextmenu="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(figcaption.New().OnCueChange("test").Render())
	want := `<figcaption oncuechange="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(figcaption.New().OnDblClick("test").Render())
	want := `<figcaption ondblclick="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(figcaption.New().OnDrag("test").Render())
	want := `<figcaption ondrag="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(figcaption.New().OnDragEnd("test").Render())
	want := `<figcaption ondragend="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(figcaption.New().OnDragEnter("test").Render())
	want := `<figcaption ondragenter="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(figcaption.New().OnDragLeave("test").Render())
	want := `<figcaption ondragleave="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(figcaption.New().OnDragOver("test").Render())
	want := `<figcaption ondragover="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(figcaption.New().OnDragStart("test").Render())
	want := `<figcaption ondragstart="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(figcaption.New().OnDrop("test").Render())
	want := `<figcaption ondrop="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(figcaption.New().OnDurationChange("test").Render())
	want := `<figcaption ondurationchange="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(figcaption.New().OnEmptied("test").Render())
	want := `<figcaption onemptied="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(figcaption.New().OnEnded("test").Render())
	want := `<figcaption onended="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(figcaption.New().OnInvalid("test").Render())
	want := `<figcaption oninvalid="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(figcaption.New().OnKeyDown("test").Render())
	want := `<figcaption onkeydown="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(figcaption.New().OnKeyPress("test").Render())
	want := `<figcaption onkeypress="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(figcaption.New().OnKeyUp("test").Render())
	want := `<figcaption onkeyup="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(figcaption.New().OnLoadedData("test").Render())
	want := `<figcaption onloadeddata="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(figcaption.New().OnLoadedMetadata("test").Render())
	want := `<figcaption onloadedmetadata="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(figcaption.New().OnLoadStart("test").Render())
	want := `<figcaption onloadstart="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseDown("test").Render())
	want := `<figcaption onmousedown="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseEnter("test").Render())
	want := `<figcaption onmouseenter="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseLeave("test").Render())
	want := `<figcaption onmouseleave="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseMove("test").Render())
	want := `<figcaption onmousemove="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseOut("test").Render())
	want := `<figcaption onmouseout="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseOver("test").Render())
	want := `<figcaption onmouseover="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseUp("test").Render())
	want := `<figcaption onmouseup="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(figcaption.New().OnMouseWheel("test").Render())
	want := `<figcaption onmousewheel="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(figcaption.New().OnPause("test").Render())
	want := `<figcaption onpause="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(figcaption.New().OnPlay("test").Render())
	want := `<figcaption onplay="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(figcaption.New().OnPlaying("test").Render())
	want := `<figcaption onplaying="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(figcaption.New().OnProgress("test").Render())
	want := `<figcaption onprogress="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(figcaption.New().OnRateChange("test").Render())
	want := `<figcaption onratechange="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(figcaption.New().OnReset("test").Render())
	want := `<figcaption onreset="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(figcaption.New().OnResize("test").Render())
	want := `<figcaption onresize="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(figcaption.New().OnScroll("test").Render())
	want := `<figcaption onscroll="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(figcaption.New().OnSeeked("test").Render())
	want := `<figcaption onseeked="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(figcaption.New().OnSeeking("test").Render())
	want := `<figcaption onseeking="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(figcaption.New().OnSelect("test").Render())
	want := `<figcaption onselect="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(figcaption.New().OnShow("test").Render())
	want := `<figcaption onshow="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(figcaption.New().OnSort("test").Render())
	want := `<figcaption onsort="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(figcaption.New().OnStalled("test").Render())
	want := `<figcaption onstalled="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(figcaption.New().OnSuspend("test").Render())
	want := `<figcaption onsuspend="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(figcaption.New().OnTimeUpdate("test").Render())
	want := `<figcaption ontimeupdate="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(figcaption.New().OnToggle("test").Render())
	want := `<figcaption ontoggle="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(figcaption.New().OnVolumeChange("test").Render())
	want := `<figcaption onvolumechange="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(figcaption.New().OnWaiting("test").Render())
	want := `<figcaption onwaiting="test"></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(figcaption.New(figcaption.New(), figcaption.New()).Render())
	want := `<figcaption><figcaption></figcaption><figcaption></figcaption></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := figcaption.New().Add(figcaption.New(), figcaption.New())

	// Test rendered output
	got := string(element.Render())
	want := `<figcaption><figcaption></figcaption><figcaption></figcaption></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := figcaption.New(figcaption.New(), figcaption.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(figcaption.New())

	// Test rendered output
	got := string(element.Render())
	want := `<figcaption><figcaption></figcaption></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(figcaption.New().Text("hello").Render())
	want := `<figcaption>hello</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(figcaption.New().Textf("hello %s", "world").Render())
	want := `<figcaption>hello world</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(figcaption.New().Static("static content").Render())
	want := `<figcaption>static content</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(figcaption.New().RawText("<em>bold</em>").Render())
	want := `<figcaption><em>bold</em></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(figcaption.New().RawTextf("<%s>test</%s>", "span", "span").Render())
	want := `<figcaption><span>test</span></figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(figcaption.New().Class("foo").Text("content").ID("bar").Render())
	want := `<figcaption class="foo" id="bar">content</figcaption>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

