package input

// Byte constants for HTML rendering.
var (
	TagOpen = []byte("<input")

	AttrName                = []byte(" name=\"")
	AttrValue               = []byte(" value=\"")
	AttrType                = []byte(" type=\"")
	AttrSrc                 = []byte(" src=\"")
	AttrAccept              = []byte(" accept=\"")
	AttrAlt                 = []byte(" alt=\"")
	AttrAutoComplete        = []byte(" autocomplete=\"")
	AttrCapture             = []byte(" capture=\"")
	AttrChecked             = []byte(" checked")
	AttrDirName             = []byte(" dirname=\"")
	AttrDisabled            = []byte(" disabled")
	AttrForm                = []byte(" form=\"")
	AttrFormAction          = []byte(" formaction=\"")
	AttrFormEncType         = []byte(" formenctype=\"")
	AttrFormMethod          = []byte(" formmethod=\"")
	AttrFormNoValidate      = []byte(" formnovalidate")
	AttrFormTarget          = []byte(" formtarget=\"")
	AttrHeight              = []byte(" height=\"")
	AttrList                = []byte(" list=\"")
	AttrMax                 = []byte(" max=\"")
	AttrMaxLength           = []byte(" maxlength=\"")
	AttrMin                 = []byte(" min=\"")
	AttrMinLength           = []byte(" minlength=\"")
	AttrMultiple            = []byte(" multiple")
	AttrPattern             = []byte(" pattern=\"")
	AttrPlaceholder         = []byte(" placeholder=\"")
	AttrPopoverTarget       = []byte(" popovertarget=\"")
	AttrPopoverTargetAction = []byte(" popovertargetaction=\"")
	AttrReadOnly            = []byte(" readonly")
	AttrRequired            = []byte(" required")
	AttrSize                = []byte(" size=\"")
	AttrStep                = []byte(" step=\"")
	AttrWidth               = []byte(" width=\"")
	AttrAlpha               = []byte(" alpha")
	AttrColorSpace          = []byte(" colorspace=\"")
)
