// Code generated by fluent generator. DO NOT EDIT.

package meter_test

import (
	"bytes"
	"testing"

	"github.com/jpl-au/fluent/html5/attr/autocapitalize"
	"github.com/jpl-au/fluent/html5/attr/autocorrect"
	"github.com/jpl-au/fluent/html5/attr/contenteditable"
	"github.com/jpl-au/fluent/html5/attr/dir"
	"github.com/jpl-au/fluent/html5/attr/enterkeyhint"
	"github.com/jpl-au/fluent/html5/attr/hidden"
	"github.com/jpl-au/fluent/html5/attr/inputmode"
	"github.com/jpl-au/fluent/html5/attr/popover"
	"github.com/jpl-au/fluent/html5/attr/spellcheck"
	"github.com/jpl-au/fluent/html5/attr/translate"
	"github.com/jpl-au/fluent/html5/attr/virtualkeyboardpolicy"
	"github.com/jpl-au/fluent/html5/attr/writingsuggestions"
	"github.com/jpl-au/fluent/html5/meter"
)

func TestNewCtor(t *testing.T) {
	// Test empty element
	got := string(meter.New().RenderBytes())
	want := `<meter></meter>`
	if got != want {
		t.Errorf("empty: got %q, want %q", got, want)
	}

	// Test nested element
	got = string(meter.New(meter.New()).RenderBytes())
	want = `<meter><meter></meter></meter>`
	if got != want {
		t.Errorf("nested: got %q, want %q", got, want)
	}
}

func TestTextCtor(t *testing.T) {
	got := string(meter.Text("6 out of 10").RenderBytes())
	want := `<meter>6 out of 10</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticCtor(t *testing.T) {
	got := string(meter.Static("75%").RenderBytes())
	want := `<meter>75%</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextCtor(t *testing.T) {
	got := string(meter.RawText("<strong>6</strong> out of 10").RenderBytes())
	want := `<meter><strong>6</strong> out of 10</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfCtor(t *testing.T) {
	current := 7
	total := 10
	got := string(meter.Textf("%d out of %d", current, total).RenderBytes())
	want := `<meter>7 out of 10</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfCtor(t *testing.T) {
	current := 7
	total := 10
	got := string(meter.RawTextf("<strong>%d</strong> out of %d", current, total).RenderBytes())
	want := `<meter><strong>7</strong> out of 10</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestValueMaxCtor(t *testing.T) {
	got := string(meter.ValueMax(6, 10).RenderBytes())
	want := `<meter value="6" max="10"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestValueAttr(t *testing.T) {
	got := string(meter.New().Value(3.14).RenderBytes())
	want := `<meter value="3.14"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestMinAttr(t *testing.T) {
	got := string(meter.New().Min(3.14).RenderBytes())
	want := `<meter min="3.14"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestMaxAttr(t *testing.T) {
	got := string(meter.New().Max(3.14).RenderBytes())
	want := `<meter max="3.14"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLowAttr(t *testing.T) {
	got := string(meter.New().Low(3.14).RenderBytes())
	want := `<meter low="3.14"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHighAttr(t *testing.T) {
	got := string(meter.New().High(3.14).RenderBytes())
	want := `<meter high="3.14"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOptimumAttr(t *testing.T) {
	got := string(meter.New().Optimum(3.14).RenderBytes())
	want := `<meter optimum="3.14"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassAttr(t *testing.T) {
	got := string(meter.New().Class("test").RenderBytes())
	want := `<meter class="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestClassMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(meter.New().Class("one").Class("two").Class("three").RenderBytes())
	want := `<meter class="one two three"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIDAttr(t *testing.T) {
	got := string(meter.New().ID("test").RenderBytes())
	want := `<meter id="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleAttr(t *testing.T) {
	got := string(meter.New().Style("test").RenderBytes())
	want := `<meter style="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStyleMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(meter.New().Style("one").Style("two").Style("three").RenderBytes())
	want := `<meter style="one; two; three"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTitleAttr(t *testing.T) {
	got := string(meter.New().Title("test").RenderBytes())
	want := `<meter title="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenAttr(t *testing.T) {
	got := string(meter.New().Hidden(hidden.True).RenderBytes())
	want := `<meter hidden="true"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestHiddenCustom(t *testing.T) {
	got := string(meter.New().Hidden(hidden.Custom("custom-value")).RenderBytes())
	want := `<meter hidden="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTabIndexAttr(t *testing.T) {
	got := string(meter.New().TabIndex(42).RenderBytes())
	want := `<meter tabindex="42"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRoleAttr(t *testing.T) {
	got := string(meter.New().Role("test").RenderBytes())
	want := `<meter role="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLangAttr(t *testing.T) {
	got := string(meter.New().Lang("test").RenderBytes())
	want := `<meter lang="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyAttr(t *testing.T) {
	got := string(meter.New().AccessKey("test").RenderBytes())
	want := `<meter accesskey="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAccessKeyMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(meter.New().AccessKey("one").AccessKey("two").AccessKey("three").RenderBytes())
	want := `<meter accesskey="one two three"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAnchorAttr(t *testing.T) {
	got := string(meter.New().Anchor("test").RenderBytes())
	want := `<meter anchor="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAriaLabelAttr(t *testing.T) {
	got := string(meter.New().AriaLabel("test").RenderBytes())
	want := `<meter aria-label="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAriaAttr(t *testing.T) {
	got := string(meter.New().SetAria("label", "test-value").RenderBytes())
	want := `<meter aria-label="test-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeAttr(t *testing.T) {
	got := string(meter.New().AutoCapitalize(autocapitalize.Off).RenderBytes())
	want := `<meter autocapitalize="off"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCapitalizeCustom(t *testing.T) {
	got := string(meter.New().AutoCapitalize(autocapitalize.Custom("custom-value")).RenderBytes())
	want := `<meter autocapitalize="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectAttr(t *testing.T) {
	got := string(meter.New().AutoCorrect(autocorrect.On).RenderBytes())
	want := `<meter autocorrect="on"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoCorrectCustom(t *testing.T) {
	got := string(meter.New().AutoCorrect(autocorrect.Custom("custom-value")).RenderBytes())
	want := `<meter autocorrect="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusAttr(t *testing.T) {
	got := string(meter.New().AutoFocus().RenderBytes())
	want := `<meter autofocus></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAutoFocusFalse(t *testing.T) {
	got := string(meter.New().AutoFocus().AutoFocus(false).RenderBytes())
	want := `<meter></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableAttr(t *testing.T) {
	got := string(meter.New().ContentEditable(contenteditable.True).RenderBytes())
	want := `<meter contenteditable="true"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestContentEditableCustom(t *testing.T) {
	got := string(meter.New().ContentEditable(contenteditable.Custom("custom-value")).RenderBytes())
	want := `<meter contenteditable="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetDataAttr(t *testing.T) {
	got := string(meter.New().SetData("user-id", "test-value").RenderBytes())
	want := `<meter data-user-id="test-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirAttr(t *testing.T) {
	got := string(meter.New().Dir(dir.LeftToRight).RenderBytes())
	want := `<meter dir="ltr"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDirCustom(t *testing.T) {
	got := string(meter.New().Dir(dir.Custom("custom-value")).RenderBytes())
	want := `<meter dir="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDraggableAttr(t *testing.T) {
	got := string(meter.New().Draggable(true).RenderBytes())
	want := `<meter draggable="true"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintAttr(t *testing.T) {
	got := string(meter.New().EnterKeyHint(enterkeyhint.Enter).RenderBytes())
	want := `<meter enterkeyhint="enter"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestEnterKeyHintCustom(t *testing.T) {
	got := string(meter.New().EnterKeyHint(enterkeyhint.Custom("custom-value")).RenderBytes())
	want := `<meter enterkeyhint="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestExportPartsAttr(t *testing.T) {
	got := string(meter.New().ExportParts("test").RenderBytes())
	want := `<meter exportparts="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertAttr(t *testing.T) {
	got := string(meter.New().Inert().RenderBytes())
	want := `<meter inert></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInertFalse(t *testing.T) {
	got := string(meter.New().Inert().Inert(false).RenderBytes())
	want := `<meter></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeAttr(t *testing.T) {
	got := string(meter.New().InputMode(inputmode.None).RenderBytes())
	want := `<meter inputmode="none"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestInputModeCustom(t *testing.T) {
	got := string(meter.New().InputMode(inputmode.Custom("custom-value")).RenderBytes())
	want := `<meter inputmode="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestIsAttr(t *testing.T) {
	got := string(meter.New().Is("test").RenderBytes())
	want := `<meter is="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemIdAttr(t *testing.T) {
	got := string(meter.New().ItemId("test").RenderBytes())
	want := `<meter itemid="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemPropAttr(t *testing.T) {
	got := string(meter.New().ItemProp("test").RenderBytes())
	want := `<meter itemprop="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemRefAttr(t *testing.T) {
	got := string(meter.New().ItemRef("test").RenderBytes())
	want := `<meter itemref="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeAttr(t *testing.T) {
	got := string(meter.New().ItemScope().RenderBytes())
	want := `<meter itemscope></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemScopeFalse(t *testing.T) {
	got := string(meter.New().ItemScope().ItemScope(false).RenderBytes())
	want := `<meter></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestItemTypeAttr(t *testing.T) {
	got := string(meter.New().ItemType("test").RenderBytes())
	want := `<meter itemtype="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNonceAttr(t *testing.T) {
	got := string(meter.New().Nonce("test").RenderBytes())
	want := `<meter nonce="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartAttr(t *testing.T) {
	got := string(meter.New().Part("test").RenderBytes())
	want := `<meter part="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPartMulti(t *testing.T) {
	// Test multiple chained calls
	got := string(meter.New().Part("one").Part("two").Part("three").RenderBytes())
	want := `<meter part="one two three"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverAttr(t *testing.T) {
	got := string(meter.New().Popover(popover.Auto).RenderBytes())
	want := `<meter popover="auto"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestPopoverCustom(t *testing.T) {
	got := string(meter.New().Popover(popover.Custom("custom-value")).RenderBytes())
	want := `<meter popover="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSlotAttr(t *testing.T) {
	got := string(meter.New().Slot("test").RenderBytes())
	want := `<meter slot="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckAttr(t *testing.T) {
	got := string(meter.New().SpellCheck(spellcheck.True).RenderBytes())
	want := `<meter spellcheck="true"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSpellCheckCustom(t *testing.T) {
	got := string(meter.New().SpellCheck(spellcheck.Custom("custom-value")).RenderBytes())
	want := `<meter spellcheck="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateAttr(t *testing.T) {
	got := string(meter.New().Translate(translate.Yes).RenderBytes())
	want := `<meter translate="yes"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTranslateCustom(t *testing.T) {
	got := string(meter.New().Translate(translate.Custom("custom-value")).RenderBytes())
	want := `<meter translate="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyAttr(t *testing.T) {
	got := string(meter.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Auto).RenderBytes())
	want := `<meter virtualkeyboardpolicy="auto"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestVirtualKeyboardPolicyCustom(t *testing.T) {
	got := string(meter.New().VirtualKeyboardPolicy(virtualkeyboardpolicy.Custom("custom-value")).RenderBytes())
	want := `<meter virtualkeyboardpolicy="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsAttr(t *testing.T) {
	got := string(meter.New().WritingSuggestions(writingsuggestions.True).RenderBytes())
	want := `<meter writingsuggestions="true"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestWritingSuggestionsCustom(t *testing.T) {
	got := string(meter.New().WritingSuggestions(writingsuggestions.Custom("custom-value")).RenderBytes())
	want := `<meter writingsuggestions="custom-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnClickAttr(t *testing.T) {
	got := string(meter.New().OnClick("test").RenderBytes())
	want := `<meter onclick="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnChangeAttr(t *testing.T) {
	got := string(meter.New().OnChange("test").RenderBytes())
	want := `<meter onchange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInputAttr(t *testing.T) {
	got := string(meter.New().OnInput("test").RenderBytes())
	want := `<meter oninput="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFocusAttr(t *testing.T) {
	got := string(meter.New().OnFocus("test").RenderBytes())
	want := `<meter onfocus="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBlurAttr(t *testing.T) {
	got := string(meter.New().OnBlur("test").RenderBytes())
	want := `<meter onblur="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSubmitAttr(t *testing.T) {
	got := string(meter.New().OnSubmit("test").RenderBytes())
	want := `<meter onsubmit="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadAttr(t *testing.T) {
	got := string(meter.New().OnLoad("test").RenderBytes())
	want := `<meter onload="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnErrorAttr(t *testing.T) {
	got := string(meter.New().OnError("test").RenderBytes())
	want := `<meter onerror="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetEventAttr(t *testing.T) {
	got := string(meter.New().SetEvent("onclick", "test-value").RenderBytes())
	want := `<meter onclick="test-value"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAbortAttr(t *testing.T) {
	got := string(meter.New().OnAbort("test").RenderBytes())
	want := `<meter onabort="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteAttr(t *testing.T) {
	got := string(meter.New().OnAutoComplete("test").RenderBytes())
	want := `<meter onautocomplete="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAutoCompleteErrorAttr(t *testing.T) {
	got := string(meter.New().OnAutoCompleteError("test").RenderBytes())
	want := `<meter onautocompleteerror="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCancelAttr(t *testing.T) {
	got := string(meter.New().OnCancel("test").RenderBytes())
	want := `<meter oncancel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayAttr(t *testing.T) {
	got := string(meter.New().OnCanPlay("test").RenderBytes())
	want := `<meter oncanplay="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCanPlayThroughAttr(t *testing.T) {
	got := string(meter.New().OnCanPlayThrough("test").RenderBytes())
	want := `<meter oncanplaythrough="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCloseAttr(t *testing.T) {
	got := string(meter.New().OnClose("test").RenderBytes())
	want := `<meter onclose="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextMenuAttr(t *testing.T) {
	got := string(meter.New().OnContextMenu("test").RenderBytes())
	want := `<meter oncontextmenu="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCueChangeAttr(t *testing.T) {
	got := string(meter.New().OnCueChange("test").RenderBytes())
	want := `<meter oncuechange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDblClickAttr(t *testing.T) {
	got := string(meter.New().OnDblClick("test").RenderBytes())
	want := `<meter ondblclick="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragAttr(t *testing.T) {
	got := string(meter.New().OnDrag("test").RenderBytes())
	want := `<meter ondrag="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEndAttr(t *testing.T) {
	got := string(meter.New().OnDragEnd("test").RenderBytes())
	want := `<meter ondragend="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragEnterAttr(t *testing.T) {
	got := string(meter.New().OnDragEnter("test").RenderBytes())
	want := `<meter ondragenter="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragLeaveAttr(t *testing.T) {
	got := string(meter.New().OnDragLeave("test").RenderBytes())
	want := `<meter ondragleave="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragOverAttr(t *testing.T) {
	got := string(meter.New().OnDragOver("test").RenderBytes())
	want := `<meter ondragover="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDragStartAttr(t *testing.T) {
	got := string(meter.New().OnDragStart("test").RenderBytes())
	want := `<meter ondragstart="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDropAttr(t *testing.T) {
	got := string(meter.New().OnDrop("test").RenderBytes())
	want := `<meter ondrop="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnDurationChangeAttr(t *testing.T) {
	got := string(meter.New().OnDurationChange("test").RenderBytes())
	want := `<meter ondurationchange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEmptiedAttr(t *testing.T) {
	got := string(meter.New().OnEmptied("test").RenderBytes())
	want := `<meter onemptied="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnEndedAttr(t *testing.T) {
	got := string(meter.New().OnEnded("test").RenderBytes())
	want := `<meter onended="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnInvalidAttr(t *testing.T) {
	got := string(meter.New().OnInvalid("test").RenderBytes())
	want := `<meter oninvalid="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyDownAttr(t *testing.T) {
	got := string(meter.New().OnKeyDown("test").RenderBytes())
	want := `<meter onkeydown="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyPressAttr(t *testing.T) {
	got := string(meter.New().OnKeyPress("test").RenderBytes())
	want := `<meter onkeypress="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnKeyUpAttr(t *testing.T) {
	got := string(meter.New().OnKeyUp("test").RenderBytes())
	want := `<meter onkeyup="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedDataAttr(t *testing.T) {
	got := string(meter.New().OnLoadedData("test").RenderBytes())
	want := `<meter onloadeddata="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadedMetadataAttr(t *testing.T) {
	got := string(meter.New().OnLoadedMetadata("test").RenderBytes())
	want := `<meter onloadedmetadata="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLoadStartAttr(t *testing.T) {
	got := string(meter.New().OnLoadStart("test").RenderBytes())
	want := `<meter onloadstart="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseDownAttr(t *testing.T) {
	got := string(meter.New().OnMouseDown("test").RenderBytes())
	want := `<meter onmousedown="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseEnterAttr(t *testing.T) {
	got := string(meter.New().OnMouseEnter("test").RenderBytes())
	want := `<meter onmouseenter="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseLeaveAttr(t *testing.T) {
	got := string(meter.New().OnMouseLeave("test").RenderBytes())
	want := `<meter onmouseleave="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseMoveAttr(t *testing.T) {
	got := string(meter.New().OnMouseMove("test").RenderBytes())
	want := `<meter onmousemove="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOutAttr(t *testing.T) {
	got := string(meter.New().OnMouseOut("test").RenderBytes())
	want := `<meter onmouseout="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseOverAttr(t *testing.T) {
	got := string(meter.New().OnMouseOver("test").RenderBytes())
	want := `<meter onmouseover="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseUpAttr(t *testing.T) {
	got := string(meter.New().OnMouseUp("test").RenderBytes())
	want := `<meter onmouseup="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnMouseWheelAttr(t *testing.T) {
	got := string(meter.New().OnMouseWheel("test").RenderBytes())
	want := `<meter onmousewheel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPauseAttr(t *testing.T) {
	got := string(meter.New().OnPause("test").RenderBytes())
	want := `<meter onpause="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayAttr(t *testing.T) {
	got := string(meter.New().OnPlay("test").RenderBytes())
	want := `<meter onplay="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPlayingAttr(t *testing.T) {
	got := string(meter.New().OnPlaying("test").RenderBytes())
	want := `<meter onplaying="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnProgressAttr(t *testing.T) {
	got := string(meter.New().OnProgress("test").RenderBytes())
	want := `<meter onprogress="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnRateChangeAttr(t *testing.T) {
	got := string(meter.New().OnRateChange("test").RenderBytes())
	want := `<meter onratechange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResetAttr(t *testing.T) {
	got := string(meter.New().OnReset("test").RenderBytes())
	want := `<meter onreset="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnResizeAttr(t *testing.T) {
	got := string(meter.New().OnResize("test").RenderBytes())
	want := `<meter onresize="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollAttr(t *testing.T) {
	got := string(meter.New().OnScroll("test").RenderBytes())
	want := `<meter onscroll="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekedAttr(t *testing.T) {
	got := string(meter.New().OnSeeked("test").RenderBytes())
	want := `<meter onseeked="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSeekingAttr(t *testing.T) {
	got := string(meter.New().OnSeeking("test").RenderBytes())
	want := `<meter onseeking="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectAttr(t *testing.T) {
	got := string(meter.New().OnSelect("test").RenderBytes())
	want := `<meter onselect="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnShowAttr(t *testing.T) {
	got := string(meter.New().OnShow("test").RenderBytes())
	want := `<meter onshow="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSortAttr(t *testing.T) {
	got := string(meter.New().OnSort("test").RenderBytes())
	want := `<meter onsort="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnStalledAttr(t *testing.T) {
	got := string(meter.New().OnStalled("test").RenderBytes())
	want := `<meter onstalled="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSuspendAttr(t *testing.T) {
	got := string(meter.New().OnSuspend("test").RenderBytes())
	want := `<meter onsuspend="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTimeUpdateAttr(t *testing.T) {
	got := string(meter.New().OnTimeUpdate("test").RenderBytes())
	want := `<meter ontimeupdate="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnToggleAttr(t *testing.T) {
	got := string(meter.New().OnToggle("test").RenderBytes())
	want := `<meter ontoggle="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnVolumeChangeAttr(t *testing.T) {
	got := string(meter.New().OnVolumeChange("test").RenderBytes())
	want := `<meter onvolumechange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWaitingAttr(t *testing.T) {
	got := string(meter.New().OnWaiting("test").RenderBytes())
	want := `<meter onwaiting="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAuxClickAttr(t *testing.T) {
	got := string(meter.New().OnAuxClick("test").RenderBytes())
	want := `<meter onauxclick="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnWheelAttr(t *testing.T) {
	got := string(meter.New().OnWheel("test").RenderBytes())
	want := `<meter onwheel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCopyAttr(t *testing.T) {
	got := string(meter.New().OnCopy("test").RenderBytes())
	want := `<meter oncopy="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCutAttr(t *testing.T) {
	got := string(meter.New().OnCut("test").RenderBytes())
	want := `<meter oncut="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPasteAttr(t *testing.T) {
	got := string(meter.New().OnPaste("test").RenderBytes())
	want := `<meter onpaste="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnScrollEndAttr(t *testing.T) {
	got := string(meter.New().OnScrollEnd("test").RenderBytes())
	want := `<meter onscrollend="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnFormDataAttr(t *testing.T) {
	got := string(meter.New().OnFormData("test").RenderBytes())
	want := `<meter onformdata="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationCancelAttr(t *testing.T) {
	got := string(meter.New().OnAnimationCancel("test").RenderBytes())
	want := `<meter onanimationcancel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationEndAttr(t *testing.T) {
	got := string(meter.New().OnAnimationEnd("test").RenderBytes())
	want := `<meter onanimationend="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationIterationAttr(t *testing.T) {
	got := string(meter.New().OnAnimationIteration("test").RenderBytes())
	want := `<meter onanimationiteration="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnAnimationStartAttr(t *testing.T) {
	got := string(meter.New().OnAnimationStart("test").RenderBytes())
	want := `<meter onanimationstart="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionCancelAttr(t *testing.T) {
	got := string(meter.New().OnTransitionCancel("test").RenderBytes())
	want := `<meter ontransitioncancel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionEndAttr(t *testing.T) {
	got := string(meter.New().OnTransitionEnd("test").RenderBytes())
	want := `<meter ontransitionend="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionRunAttr(t *testing.T) {
	got := string(meter.New().OnTransitionRun("test").RenderBytes())
	want := `<meter ontransitionrun="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTransitionStartAttr(t *testing.T) {
	got := string(meter.New().OnTransitionStart("test").RenderBytes())
	want := `<meter ontransitionstart="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeToggleAttr(t *testing.T) {
	got := string(meter.New().OnBeforeToggle("test").RenderBytes())
	want := `<meter onbeforetoggle="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeInputAttr(t *testing.T) {
	got := string(meter.New().OnBeforeInput("test").RenderBytes())
	want := `<meter onbeforeinput="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnBeforeMatchAttr(t *testing.T) {
	got := string(meter.New().OnBeforeMatch("test").RenderBytes())
	want := `<meter onbeforematch="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnCommandAttr(t *testing.T) {
	got := string(meter.New().OnCommand("test").RenderBytes())
	want := `<meter oncommand="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextLostAttr(t *testing.T) {
	got := string(meter.New().OnContextLost("test").RenderBytes())
	want := `<meter oncontextlost="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnContextRestoredAttr(t *testing.T) {
	got := string(meter.New().OnContextRestored("test").RenderBytes())
	want := `<meter oncontextrestored="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSecurityPolicyViolationAttr(t *testing.T) {
	got := string(meter.New().OnSecurityPolicyViolation("test").RenderBytes())
	want := `<meter onsecuritypolicyviolation="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSlotChangeAttr(t *testing.T) {
	got := string(meter.New().OnSlotChange("test").RenderBytes())
	want := `<meter onslotchange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerDownAttr(t *testing.T) {
	got := string(meter.New().OnPointerDown("test").RenderBytes())
	want := `<meter onpointerdown="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerUpAttr(t *testing.T) {
	got := string(meter.New().OnPointerUp("test").RenderBytes())
	want := `<meter onpointerup="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerMoveAttr(t *testing.T) {
	got := string(meter.New().OnPointerMove("test").RenderBytes())
	want := `<meter onpointermove="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerEnterAttr(t *testing.T) {
	got := string(meter.New().OnPointerEnter("test").RenderBytes())
	want := `<meter onpointerenter="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerLeaveAttr(t *testing.T) {
	got := string(meter.New().OnPointerLeave("test").RenderBytes())
	want := `<meter onpointerleave="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOverAttr(t *testing.T) {
	got := string(meter.New().OnPointerOver("test").RenderBytes())
	want := `<meter onpointerover="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerOutAttr(t *testing.T) {
	got := string(meter.New().OnPointerOut("test").RenderBytes())
	want := `<meter onpointerout="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnPointerCancelAttr(t *testing.T) {
	got := string(meter.New().OnPointerCancel("test").RenderBytes())
	want := `<meter onpointercancel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnGotPointerCaptureAttr(t *testing.T) {
	got := string(meter.New().OnGotPointerCapture("test").RenderBytes())
	want := `<meter ongotpointercapture="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnLostPointerCaptureAttr(t *testing.T) {
	got := string(meter.New().OnLostPointerCapture("test").RenderBytes())
	want := `<meter onlostpointercapture="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchStartAttr(t *testing.T) {
	got := string(meter.New().OnTouchStart("test").RenderBytes())
	want := `<meter ontouchstart="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchEndAttr(t *testing.T) {
	got := string(meter.New().OnTouchEnd("test").RenderBytes())
	want := `<meter ontouchend="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchMoveAttr(t *testing.T) {
	got := string(meter.New().OnTouchMove("test").RenderBytes())
	want := `<meter ontouchmove="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnTouchCancelAttr(t *testing.T) {
	got := string(meter.New().OnTouchCancel("test").RenderBytes())
	want := `<meter ontouchcancel="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectStartAttr(t *testing.T) {
	got := string(meter.New().OnSelectStart("test").RenderBytes())
	want := `<meter onselectstart="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestOnSelectionChangeAttr(t *testing.T) {
	got := string(meter.New().OnSelectionChange("test").RenderBytes())
	want := `<meter onselectionchange="test"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestNewMulti(t *testing.T) {
	got := string(meter.New(meter.New(), meter.New()).RenderBytes())
	want := `<meter><meter></meter><meter></meter></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestAdd(t *testing.T) {
	element := meter.New().Add(meter.New(), meter.New())

	// Test rendered output
	got := string(element.RenderBytes())
	want := `<meter><meter></meter><meter></meter></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes, got %d", len(element.Nodes()))
	}
}

func TestReplace(t *testing.T) {
	// Create element with 2 children
	element := meter.New(meter.New(), meter.New())

	// Verify initial state
	if len(element.Nodes()) != 2 {
		t.Errorf("expected 2 nodes initially, got %d", len(element.Nodes()))
	}

	// Replace with 1 child
	element.Replace(meter.New())

	// Test rendered output
	got := string(element.RenderBytes())
	want := `<meter><meter></meter></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}

	// Test Nodes() returns correct count after replace
	if len(element.Nodes()) != 1 {
		t.Errorf("expected 1 node after replace, got %d", len(element.Nodes()))
	}
}

func TestTextMethod(t *testing.T) {
	got := string(meter.New().Text("hello").RenderBytes())
	want := `<meter>hello</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextfMethod(t *testing.T) {
	got := string(meter.New().Textf("hello %s", "world").RenderBytes())
	want := `<meter>hello world</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestStaticMethod(t *testing.T) {
	got := string(meter.New().Static("static content").RenderBytes())
	want := `<meter>static content</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextMethod(t *testing.T) {
	got := string(meter.New().RawText("<em>bold</em>").RenderBytes())
	want := `<meter><em>bold</em></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestRawTextfMethod(t *testing.T) {
	got := string(meter.New().RawTextf("<%s>test</%s>", "span", "span").RenderBytes())
	want := `<meter><span>test</span></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestTextChaining(t *testing.T) {
	got := string(meter.New().Class("foo").Text("content").ID("bar").RenderBytes())
	want := `<meter class="foo" id="bar">content</meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestDynamicKey(t *testing.T) {
	got := string(meter.New().Dynamic("mykey").RenderBytes())
	want := `<meter data-fluent-key="mykey"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestMemoiseKey(t *testing.T) {
	el := meter.New()
	if el.MemoiseKey() != nil {
		t.Error("new element should have no memoise version")
	}
	el.Memoise(7)
	if el.MemoiseKey() != 7 {
		t.Errorf("MemoiseKey() = %v, want 7", el.MemoiseKey())
	}
}

func TestNotDynamic(t *testing.T) {
	el := meter.New()
	if el.IsDynamic() {
		t.Error("new element should not be dynamic")
	}
	if el.DynamicKey() != "" {
		t.Errorf("DynamicKey() should be empty, got %q", el.DynamicKey())
	}
}

func TestRenderMethodsMatch(t *testing.T) {
	el := meter.New()
	el.SetAttribute("data-check", "render")
	want := string(el.RenderBytes())

	var buf bytes.Buffer
	el.Render(&buf)
	if buf.String() != want {
		t.Errorf("Render: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	n, err := el.WriteTo(&buf)
	if err != nil {
		t.Fatalf("WriteTo: %v", err)
	}
	if buf.String() != want {
		t.Errorf("WriteTo: got %q, want %q", buf.String(), want)
	}
	if n != int64(len(want)) {
		t.Errorf("WriteTo returned %d bytes, want %d", n, len(want))
	}

	buf.Reset()
	el.RenderBuilder(&buf)
	if buf.String() != want {
		t.Errorf("RenderBuilder: got %q, want %q", buf.String(), want)
	}

	buf.Reset()
	el.RenderOpen(&buf)
	el.RenderClose(&buf)
	if buf.String() != want {
		t.Errorf("RenderOpen+RenderClose: got %q, want %q", buf.String(), want)
	}
}

func TestSetAttributeEscapes(t *testing.T) {
	el := meter.New()
	el.SetAttribute("data-sample", "\"><script>")
	got := string(el.RenderBytes())
	want := `<meter data-sample="&#34;&gt;&lt;script&gt;"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestSetAttributeRaw(t *testing.T) {
	el := meter.New()
	// A pre-escaped entity must render verbatim; SetAttribute would double-escape it.
	el.SetAttributeRaw("data-sample", "a&amp;b")
	got := string(el.RenderBytes())
	want := `<meter data-sample="a&amp;b"></meter>`
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}
