// Code generated by fluent generator. DO NOT EDIT.

// Package rel defines the [Rel] type and its predefined values.
//
// Describes the relationship between a document and a linked resource.
// Some values describe hyperlinks. Others cause link elements to fetch external
// resources. Choose values supported by the element carrying the relationship.
package rel

import (
	"github.com/jpl-au/fluent/node"
)

// Rel is a typed value for the HTML rel attribute.
//
// Describes the relationship between a document and a linked resource.
// Some values describe hyperlinks. Others cause link elements to fetch external
// resources. Choose values supported by the element carrying the relationship.
type Rel []byte

// Variables for Rel values
var (
	// Stylesheet CSS stylesheet resource for styling the document. The browser loads and applies CSS
	// rules to the current page for visual presentation and layout.
	Stylesheet = Rel("stylesheet")

	// Icon Icon resource representing the document or site. Displayed in browser tabs, bookmarks,
	// and application interfaces. Supports various image formats and sizes.
	Icon = Rel("icon")

	// Preload Requests an early fetch for a resource needed by the current page. Set as
	// to its destination and match the eventual request so the fetched resource
	// can be reused. Preload does not itself apply or execute the resource.
	Preload = Rel("preload")

	// Prefetch Low-priority resource likely to be needed in future navigation. Browser may fetch
	// resource during idle time for performance optimisation of subsequent pages.
	Prefetch = Rel("prefetch")

	// DnsPrefetch Resolve DNS for external domain before resource is actually needed. Reduces connection
	// latency for future requests to the specified domain.
	DnsPrefetch = Rel("dns-prefetch")

	// Preconnect Establish early connection to external origin including DNS, TCP, and TLS negotiation.
	// Optimises performance for resources from third-party domains.
	Preconnect = Rel("preconnect")

	// Canonical Identifies the preferred URL for equivalent document content. It is a hint
	// to consumers such as search engines. It does not redirect requests or guarantee indexing.
	Canonical = Rel("canonical")

	// Alternate Alternative representation of current document. May specify different language, format,
	// or media type version of the same content for accessibility and internationalisation.
	Alternate = Rel("alternate")

	// Prev Previous document in a sequence or series. Helps users and search engines understand
	// document relationships and navigate through sequential content.
	Prev = Rel("prev")

	// Next Identifies the next document in a sequence, such as the following page of
	// an article. It does not itself request prefetching.
	Next = Rel("next")

	// Help Help documentation or support resource related to current document. Provides contextual
	// assistance and user guidance for the current page or application.
	Help = Rel("help")

	// License Copyright license covering current document content. Legal information about content
	// usage rights and redistribution terms for the document.
	License = Rel("license")

	// Manifest Links to a web app manifest containing application metadata such as names,
	// icons, and launch settings. Offline behaviour requires separate implementation.
	Manifest = Rel("manifest")

	// ModulePreload JavaScript module to preload for improved performance. Browser fetches and compiles
	// ES modules early in the page lifecycle for faster execution.
	ModulePreload = Rel("modulepreload")

	// Author Link to the author of the current document or article. Helps search engines
	// and readers identify who created the content.
	Author = Rel("author")

	// Bookmark Provides a permalink for the nearest ancestor article, or for the section
	// most closely associated with the link when there is no ancestor article.
	Bookmark = Rel("bookmark")

	// Expect Identifies a document fragment expected during parsing. Combined with
	// blocking="render" on a link element, it delays rendering while the expected
	// fragment has not yet been parsed.
	Expect = Rel("expect")

	// External Identifies a link to a resource outside the current site. This describes
	// a site relationship. It does not necessarily imply a different domain or origin.
	External = Rel("external")

	// Me Indicates the linked resource represents the person who owns the current document.
	// Used for identity verification and IndieWeb authentication patterns.
	Me = Rel("me")

	// NoFollow Indicates that the author does not endorse the referenced document or that
	// the link has a primarily commercial relationship. Search engines determine
	// how they use this hint.
	NoFollow = Rel("nofollow")

	// NoOpener Prevents the opened page from accessing window.opener. Security measure for links
	// opening new tabs to prevent reverse tabnapping attacks.
	NoOpener = Rel("noopener")

	// NoReferrer No Referer header sent when following the link. Provides privacy by hiding the
	// source page URL from the destination. Implies noopener behaviour.
	NoReferrer = Rel("noreferrer")

	// Opener Requests an opener relationship for a newly opened browsing context,
	// allowing a window.opener reference where browser isolation policies permit it.
	Opener = Rel("opener")

	// PrivacyPolicy Link to the privacy policy governing data collection on the current page.
	// Helps users and automated tools locate privacy documentation.
	PrivacyPolicy = Rel("privacy-policy")

	// Search Link to a search interface for the current site or related resources.
	// Enables browsers and tools to discover the site's search functionality.
	Search = Rel("search")

	// Tag Indicates the linked resource is a tag or keyword describing the current document.
	// Used for content categorisation and topic tagging.
	Tag = Rel("tag")

	// TermsOfService Link to the terms of service governing use of the current page or site.
	// Helps users and automated tools locate legal documentation.
	TermsOfService = Rel("terms-of-service")

	// AppleTouchIcon Apple-specific icon for iOS devices. Used when users add website to home screen
	// or bookmark on Apple devices. Supports various sizes and resolutions.
	AppleTouchIcon = Rel("apple-touch-icon")
)

// Custom allows setting a custom Rel value for edge cases or future specifications.
// Use this when the predefined constants don't cover your specific use case.
func Custom(value string) Rel {
	return Rel(node.EscapeAttribute(value))
}
